### ISSUE TITLE
Pull request instructions

### ISSUE THREAD

**Issue by theMichaelB** [Azure/enterprise-azure-policy-as-code#102]
I created a pull request with a small fix, but I don't think it worked (at least I can't see any evidence of it!) Are there any instructions to follow to successfully do this?

**Comment by techlake** [comment]
I don'tt see the PR. Can you send me a screenshot **(make sure you redact any personal info)**

Alternatively, email me the content ("ill contact you directly with the info).

**Comment by theMichaelB** [comment]
I suspect I did something dumb somewhere along the way, I'll redo the PR and pay more attention. This issue is more focused on having a set of step by step instructions for people who are new to contributing (to MS Projects) on Github

**Comment by techlake** [comment]
Let's leave the issue open and I'll try to find an expert on PRs to write instructions for me.
