### ISSUE TITLE
Least privilege improvement for the planning stage of the deployments

### ISSUE THREAD

**Issue by Patchfox** [Azure/enterprise-azure-policy-as-code#107]
Hi, 
in the documentation of epac the permission 
_Microsoft.Management/register/action_
is required for the custom role _EPAC Policy Reader role_. 
According to our current testing and knowledge, the Reader Role would be sufficient for the planning stage. 
However, this would require to add a _--no-register_ parameter in the scripts for the command 
`az account management-group show --name LH_Management_Group --expand --recurse `
Like this: 
`az account management-group show --name LH_Management_Group --expand --recurse --no-register`

Is there some unknown reason to keep this permission in the custom role?

**Comment by techlake** [comment]
Thank you for the great feedback and your research. In the imminent release of v6.0 (planned this week) we changed from az cli to PowerShell Az module for all our code (previously this was mix and match).  We are now using resource graph queries for the above functionality. We will investigate if a similar flag is available for a graph query (this will happen after V6.0 release. I will keep this issue open to track progress.

**Comment by techlake** [comment]
Thank you for the great feedback and your research. In the imminent release of v6.0 (planned this week) we changed from az cli to PowerShell Az module for all our code (previously this was mix and match).  We are now using resource graph queries for the above functionality. We will investigate if a similar flag is available for a graph query (this will happen after V6.0 release. I will keep this issue open to track progress.

**Comment by techlake** [comment]
We are now using Search-AzGraphAllItems and it does appear to require register action:
    $resourceContainers = Search-AzGraphAllItems `
        -query "ResourceContainers" `
        -scope $scope

I'm closing this issue since the improved v6.0 is not relying on the same technology.
