### ISSUE TITLE
Question Feature: Always Assign Policy to Dev or Test PacEnv

### ISSUE THREAD

**Issue by martyh888** [Azure/enterprise-azure-policy-as-code#117]
I am not sure if this is possible or maybe the documentation doesn't explain this option to me but I have been looking through the code to see how to make it mandatory that a policy is assigned to an EPAC-dev Environment even if the user forgot to add a scope defined in the policyAssignments.

This feature or need is to make sure the Assignment has been passed through Dev / Test before it can reach production in the pipeline stages

**Comment by anwather** [comment]
I would say this is more of a process issue than a technical issue. What you could do is in your pipeline is test each assignment file to ensure that each scope block has a required environment key in there?

**Comment by techlake** [comment]
You could achieve that with an additional script. I do not see a generic need. However, if you write the script and a documentaion file: I'll accept it as a contributions.

**Comment by martyh888** [comment]
I will handle this in the process document and should be something that is picked up on the merge request/approval stages.
