### ISSUE TITLE
Feature: Strategy to include Keeping Policy / Definitions For Dev Test

### ISSUE THREAD

**Issue by martyh888** [Azure/enterprise-azure-policy-as-code#119]
I have a use case where we have multiple teams working in 1 repo on a policy change feature branch for a single tenant and for dev/test purposes it would be helpful to keep policies deployed so that they are not destroyed whilst testing policies (especially with the time it can take for a policy to action along with remediation actions)

My thought for adding this type of feature would be 

```
in Global-settings.jsonc allowing

"desiredState": {
        // [optional]
        "strategy": "keep",
        

in Get-GlobalSettings.ps1 - Adding "keep" as an option

            $strategy = $desired.strategy
            if ($null -ne $strategy) {
                $valid = @("full", "ownedOnly", "keep")

in Confirm-DeleteForStrategy.ps1 Add if else or something like below

    if($strategy -eq "keep"){
        $shallDelete = $false
    }
    else {
        $shallDelete = switch ($pacOwner) {
            "thisPaC" {
                $true
                break
            }
            "otherPaC" {
                $false
                break
            }
            "unknownOwner" {
                $strategy -eq "full"
                break
            }
        }
    }
```
I can some issue with this above

1. How to delete them (Manually or running a cleanup PacEnv where it will remove them using strategy full)
2. This could probably be also achieved by Merge Requests to a Branch which may be the correct way to do this

**Comment by techlake** [comment]
IMO your CI/CD process is broken. You may want to do one of the following:

- Split the repo along team lines and have two separate repos. pacOwnerId will keep the different Policies intact.
- Use different naming for the feature branches and have separate testing areas (pacEnvironments)

**Does this work, or do you still request the change?**

**Comment by martyh888** [comment]
I will Close this

I am keen to initially keep it in the same repo until we see a real need for splitting, so for allowing longer testing for some (which would generally be only 1 at a time) I will go with point 2 and add a pipeline approval stage / manual trigger for testing leveraging its own pacEnvironment.
