### ISSUE TITLE
Multi-tenant pipelines has possible syntax error in naming

### ISSUE THREAD

**Issue by artisticcheese** [Azure/enterprise-azure-policy-as-code#120]
It does not look like that Azure DevOps Pipelines allow `-` as part of pipeline dependency name. Getting following error trying to run https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Pipelines/AzureDevOps/multi-tenant-pipeline.yml

`An error occurred while loading the YAML build pipeline. Unexpected symbol: 'tenantPlanMainStage-1'. Located at position 53 within expression: and(not(failed()), not(canceled()), eq(dependencies.tenantPlanMainStage-2.outputs['planJob.planStep.deployPolicyChanges'], 'yes'), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/main')). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996
`

I think stages and dependencies should not have `-`

**Comment by techlake** [comment]
Will be fixed in v6.1 due 1/23/2023 by EOB US CST
