### ISSUE TITLE
Are environments supposed to be automatically created during YAML run?

### ISSUE THREAD

**Issue by artisticcheese** [Azure/enterprise-azure-policy-as-code#126]
Hello,

I run YAML and it did create PAC-DEV environment but none of the other environments mentioned were created and instead following errors were thrown `Job deployPolicyJob: Environment PAC-POLICY could not be found. The environment does not exist or has not been authorized for use.`
![image](https://user-images.githubusercontent.com/13176884/214183354-3c25c904-785c-4f50-845b-23955371f8a9.png)

**Comment by techlake** [comment]
No, they are not. Environments help you control approval gates and are therefore purposly handled outside of the pipeline definition.https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops.

Do you think we should add some documentation or at least a reference to this article?

**Comment by artisticcheese** [comment]
I'm confused about use of environments in pipeline. Dev one was automatically created because it was mentioned in pipeline and per this document that's how it's supposed to work (https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#:~:text=When%20you%20author%20a%20YAML%20pipeline%20and%20refer%20to%20an%20environment%20that%20does%20not%20exist%2C%20Azure%20Pipelines%20automatically%20creates%20the%20environment%20when%20the%20user%20performing%20the%20operation%20is%20known%20and%20permissions%20can%20be%20assigned) but none of the others were automatically created and error message above appeared.
