### ISSUE TITLE
Feature: User-assigned managed identity of Azure Policy Assignments

### ISSUE THREAD

**Issue by Patchfox** [Azure/enterprise-azure-policy-as-code#127]
Currently, when planning the deployment (i.e. generating the plan files), we receive an error message regarding policies in policysets with user-assigned managed identities. 
![2023-01-24 13_18_17-Get-AzPolicyResources ps1 - Policies - Visual Studio Code](https://user-images.githubusercontent.com/22965843/214290896-c3df0d48-f1d6-4145-aef6-f74f04641a72.png)
When debugging, we discovered that the principalId field for user-assigned managed identities is a nested object and is therefore not handled as expected in the script (like system assigned managed identities). 
Could this be a bug or did we forget something for v.6.

**Comment by johnpetersjr** [comment]
Did this really get closed and implemented two days ago?  I am looking to implement this feature, ideally I want to hardcode a user-managed identity for DeployIfNotExists policy assignments... can you provide a link to a document on how to do this?  Awesome job!

**Comment by johnpetersjr** [comment]
Is this what I'm looking for? https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/Docs/policy-assignments.md#user-assigned-managed-identities

**Comment by techlake** [comment]
Yes, this really was released two days ago.
