### ISSUE TITLE
Wrong references for service connections in multi-tenant pipeline

### ISSUE THREAD

**Issue by artisticcheese** [Azure/enterprise-azure-policy-as-code#128]
References are using non-existent variables
https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Pipelines/AzureDevOps/multi-tenant-pipeline.yml

`There was a resource authorization issue: "The pipeline is not valid. Job planJob: Step planStep input ConnectedServiceNameARM references service connection $(tenantPlanServiceConnection) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. Job planJob: Step planStep input ConnectedServiceNameARM references service connection $(tenantPlanServiceConnection) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."`

I assume those shall be refering to tenant `$(tenantXPlanServiceConnection)` instead

**Comment by techlake** [comment]
Correct. Currently, I do not have a multi-tenant environment at my disposition which makes it hard to tesr. Thank you for finding the issues. I will add it to the next minor release. Probably v6.1.1

**Comment by techlake** [comment]
Fixed starter kit in v6.1.1
