### ISSUE TITLE
Is it possible to add built-in policy definition into custom initiative?

### ISSUE THREAD

**Issue by artisticcheese** [Azure/enterprise-azure-policy-as-code#130]
Hello,

I'm a little confused since there is no example (or at least I did not find one) showing how to add built-in policy definition into custom initiative definition. Example is below of what I would like to be inside custom policy definition.

```
 {
      "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/564feb30-bf6a-4854-b4bb-0d2d2d1e6c66",
      "parameters": {
        "effect": {
          "value": "Deny"
        }
      },
      "policyDefinitionReferenceId": "Enforce use of WAF on application gateways",
      "groupNames": []
    }
```

**Comment by techlake** [comment]
Yes, that is allowed

**Comment by techlake** [comment]
I created a new issue to track improving the documentation. I'm closing this issue.

**Comment by techlake** [comment]
You can use one of the following two approaches:

1. `policyDefinitionId` - this is the preferred way for built-ins - Do NOT use for custom - Completely remove `policyDefinitionName`
2. `policyDefinitionName` this works for built-ins  and is the only way for custom
