### ISSUE TITLE
Additional Role Assignment does not work as expected

### ISSUE THREAD

**Issue by Patchfox** [Azure/enterprise-azure-policy-as-code#131]
However, if the additionalRoleAssignments parameter is set in the assignment.json file, no additional role assignment will be scheduled. 
This is how the section in the assignment file looks like: 
```
...
 "additionalRoleAssignments": [
        {
            "roleDefinitionId" : "/subscriptions/1111-1111-1111-1111-11111/providers/Microsoft.Authorization/roleDefinitions/11111-1111-1111-1111-111111111",
            "scope": "/subscriptions/11111-1111-1111-1111-111111111"
        }
        
    ]
...
```

When i am in debug mode the following selectors (roleDefinitionId and scope) are used in file Build-AssignmentDefinitionNode.ps1 in line 220: 
E.g: 
![image](https://user-images.githubusercontent.com/22965843/214686361-13097af9-77af-4861-a7d0-b12e7a7b35bf.png)

The further statements are not executed anymore, because the first if statement in the foreach loop already returns a false. thus no additional role assignment is created. 

Should that be so? 

Maybe I am doing something wrong.

**Comment by techlake** [comment]
### We have both: a bug in my code AND your doing something wrong. I'll check the fixed code in shortly

### For you, you need to fix the json:
additionalRoleAssignments like scopes and notScopes are specific to an EPAC environment as indicated by a pacEnvironmentSelector (that's your code in the debugger). You can either specify a pacSelector (see global-settings.jsonc). Legal ways of doing this are:

``` json
 "additionalRoleAssignments": {
  "*": [
      {
            "roleDefinitionId" : "/subscriptions/1111-1111-1111-111111111/providers/Microsoft.Authorization/roleDefinitions/11111-1111-1111-1111-111111111",
            "scope": "/subscriptions/11111-1111-1111-1111-111111111"
      }
  ]
}
```

or

``` jsonc
 "additionalRoleAssignments": {
  "epac-dev": [
      {
            "roleDefinitionId" : "/subscriptions/1111-1111-1111-1111-11111/providers/Microsoft.Authorization/roleDefinitions/11111-1111-1111-1111-111111111",
            "scope": "/subscriptions/11111-1111-1111-1111-111111111"
      }
  ]
}
```

                            "additionalRoleAssignments": {
                                "*": [

**Comment by techlake** [comment]
I also will keep this issue open to add additional documentation later

**Comment by techlake** [comment]
Fixed in v6.1.1

**Comment by Patchfox** [comment]
Thanks for the quick info and implementation with the new minor version. For me the selector variable was still a question mark. But now I understand it. I will test it directly with the new version.

**Comment by Patchfox** [comment]
UPDATE; I have performed a test with the version 6.1.1. It works now that the additional roleAssignment is planned in the defined scope. Furthermore the same role assignment remains on the MGBranch in which the PolicySet should be assigned. I know, the name _additionalRoleAssignments_ already says that it is an additional role assignment. Is there nevertheless already the possibility to assign certain role assignments exclusively in additional scopes (outside the MGBranch of the policy assignment)? For us it is a gamebreaker if a role assignment is created in a scope where the managed identity is not supposed to have any privileges (least privileges)

**Comment by techlake** [comment]
Looking at how DINE Policies use the permissions, the `roleDefinitionIds` from the Policy definition must be assigned at the same scope to allow the remediation. However, I'm planning to add user assigned identities in the next major release (7.0). For user assigned MIs, the onus of granting permission is not on EPAC. They are managed separately.
