### ISSUE TITLE
Need guidance on policy exclusion

### ISSUE THREAD

**Issue by fslef** [Azure/enterprise-azure-policy-as-code#140]
Hi team,

I'm testing the EPAC to deploy my policies.
I gone through the documentation but this is unclear for me how to setup the policy assignmment exclusion.

Let's take the example from the starter kit.
What if I wan't to exclude all 'tag policies' assignments?

I tried to update my `global-settings.jsonc` to add this to my pac environment. :

``` json
  "excludedPolicyAssignments": [
      "/Tags/*"
  ]
```

but this code seems to not have the expected effect and my assignments are still there.
Any guidance on how to setup such exceptions / or on the issue i'm facing ?

Thanks a lot in advance for your help.

**Comment by fslef** [comment]
Thanks a lot for your response.

I see what you've explained but I wanted to config. Let's take a concrete example.
let's consider the configuration from the [Starter Kit](https://github.com/Azure/enterprise-azure-policy-as-code/tree/main/StarterKit)

In the [assignment documentation](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/Docs/policy-assignments.md#assignment-structure) it is specified the following:

- Assignment file [security-baseline-assignments.jsonc](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Definitions/policyAssignments/security-baseline-assignments.jsonc) contains 2 levels of hierarchy containing the root node and 2 child nodes`
- So the root node is '/Security/', and the following childs are 'Prod/' 'Test/' 'Dev/' 'Sandbox/' (well, except if I'm mistaken, this is 4 children)

So how to setup in the [global-settings.jsonc](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Definitions/global-settings.jsonc), the excludedPolicyAssignments. I tried as you proposed to specify the `"*/providers/Microsoft.Authorization/policyAssignments/Security*"`, (plus other similar try) but it was unsuccessful.

Anything I've missed ?
Thank you.

**Comment by techlake** [comment]
The exclusions are not related to the layers in an assignment. The tree structure in the assignment file is used to avoid copy/paste of JSON.

Exclusions are based on and assignment id. The structure of an assignment id is
{scope}//providers/Microsoft.Authorization/policyAssignments/{assignmentName}. In the starter kit example, the assignment name is labelled as such and is concatenated from the entire branch of the tree.

Q: Why would you exclude an assignment you created?
