### ISSUE TITLE
New-EPACPolicyAssignmentDefinition.ps1 - No Reference to ConvertTo-HashTable Function

### ISSUE THREAD

**Issue by martyh888** [Azure/enterprise-azure-policy-as-code#143]
The Script did not have a reference to the Helpers Script ConvertTo-HashTable.ps1

![image](https://user-images.githubusercontent.com/17297403/215964931-16f1792f-2305-4e88-a0a0-1140fccb33cc.png)

```powershell

# Add the following so it can use this function
. "$PSScriptRoot/../Helpers/ConvertTo-HashTable.ps1"
```

**Comment by techlake** [comment]
Same here: see #142
