### ISSUE TITLE
https://github.com/Azure/enterprise-azure-policy-as-code using 'Starter Kit ' is not up-to-date and Azure DevOps pipeline produces failures

### ISSUE THREAD

**Issue by isgo-golgo13** [Azure/enterprise-azure-policy-as-code#151]
As of 2/24/2023 using the provided 'Starter Kit' with the included Azure DevOps pipeline for Single Tenant does not result in a successful pipeline stage run. We have appropriately followed  this page to plug in our tenant IDs and all required changes to the 'globalSetting.jsonc' file to match our environment.

Here is the document we followed:
https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/azure-enterprise-policy-as-code-a-new-approach/ba-p/3607843

It appears during the Azure DevOps pipeline shows that there are errors in provided policies and that policySetDefintion in the 'Starter Kit' are outdated.

Is there another reference on how to apply this EPAC to the management group level?

**Comment by techlake** [comment]
Hi, thank you for reporting an issue. Can you send me the error message, please? It might be related to a change in the underlying API causing an error when parameters start with an uppercase letter.

**Comment by isgo-golgo13** [comment]
@techlake Here is one of them. 

===================================================================================================
Create new Policy Sets (2)
---------------------------------------------------------------------------------------------------
Enable Azure Cosmos DB throughput policy
Loaded Module 'Az.Accounts'
Loaded Module 'Az.MSGraph'
Loaded Module 'Az.Accounts'
Loaded Module 'Az.Authorization'
New-AzPolicySetDefinition: /home/vsts/work/1/s/Scripts/Deploy/Deploy-PolicyPlan.ps1:217
Line |
 217 |              $null = New-AzPolicySetDefinition @policySetDefinition
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | UnsupportedApiVersion : The property 'DefinitionVersion' is not
     | supported in API version '2021-06-01'. Please use API version
     | '2022-10-01' or higher. CorrelationId:
     | 8a861d77-7753-49b6-8a9c-7ca9b65c2011

##[error]PowerShell exited with code '1'.

I add a Github available Azure Policy Set Definition to the `StarterKit'/Definitions/policySetDefinitions` folder and eitherI get a `Conflict` error or `the error you see above`. The PS1 scripts using the Az CLI either don't like the latest azure policyset definition files or when the azure policyset definition files have a defined version it results in a failed AzDO pipeline run.

**Comment by isgo-golgo13** [comment]
@techlake Here is the setup and workflow we are trying to do.
We ideally like to use goal focused and related grouping of Azure PolicySet Definitions (PSDs) and drop these into the EPAC provided `StarterKit/Definitions/policySetDefinitions` directory. The one thing I see which is good is that I can organize the PSDs by their domain (Kubernetes, Azure Storage, Azure Networking, ....) using child directories under the `policySetDefinitions` folder like `*/policySetDefinitons/aks` or `*/policySetDefintions/az-storage`. You get the idea. I don't want to mix all the PSDs and lump them sloppily into the flat policySetDefintions` folder. Also to test the StarterKit I am using the following Github repo https://github.com/Azure/azure-policy/tree/master/built-in-policies to pull the PSDs so I don't have to write from scratch. The issue I see is that the PSD JSON/JSONC files look different across various PSD samples I see when I search for samples like the JSON schema has changed from one version to the next. This appears to contribute to the EPAC instability. 

If PSDs (Azure Policy Iniatives) won't work, we would have to follow a non-scalable approach of adding in one-by-one the PolicyDefintions and target a large range of different policyAssignment targets and do a lot of non-DRY copy-and-paste which is going into anti-pattern territory.

We copied your provided StarterKit AzDo pipeline and tailored it minimally to point to our env. This appears to pick up everything we drop in so no issues with the pipeline itself.

`variables:
  # This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
  PAC_OUTPUT_FOLDER: "./Output"
  PAC_DEFINITIONS_FOLDER: "./StarterKit/Definitions"
  
  # Future directory of Azure Policy Set Definitions
  #PAC_DEFINITIONS_DIRECTORY: "./ODP/Definitions"

  # Use the plain text name of each service connection as a reference
  devServiceConnection: "svc-azure-epac"
  tenantPlanServiceConnection: "svc-azure-epac"
  tenantDeployServiceConnection: "svc-azure-epac"
  tenantRolesServiceConnection: "svc-azure-epac"


trigger:
  branches:
    include:
      - /*
  paths:
    include:
      - /*

pr: none


stages:
  - stage: devStage
    displayName: "DEV Plan, Deploy and Roles"
    #condition: and(in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), not(contains(variables['Build.SourceBranch'], 'refs/heads/main')))
    variables:
      pacEnvironmentSelector: epac-dev
    jobs:
      - deployment: allJob
        environment: PAC-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzurePowerShell@5
                  name: planStep
                  displayName: Plan
                  inputs:
                    azureSubscription: $(devServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Build-DeploymentPlans.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -devOpsType "ado" `
                      -InformationAction Continue


                # Publish pipeline Artifact for ADO Service
                - publish: "$(PAC_OUTPUT_FOLDER)/plans-$(pacEnvironmentSelector)"
                  artifact: "plans-$(pacEnvironmentSelector)"
                  condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))



                - task: AzurePowerShell@5
                  displayName: Deploy PAC-DEV Policy
                  condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))
                  inputs:
                    azureSubscription: $(devServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-PolicyPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue


                - task: AzurePowerShell@5
                  displayName: Deploy PAC-DEV Role Assignments
                  condition: and(not(failed()), not(canceled()), eq(variables['planStep.deployRoleChanges'], 'yes'))
                  inputs:
                    azureSubscription: $(devServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-RolesPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue


  - stage: tenantPlanFeatureStage
    displayName: "Tenant Plan - Feature Branch"
    dependsOn:
      - devStage
    condition: and(not(failed()), not(canceled()), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), not(contains(variables['Build.SourceBranch'], 'refs/heads/main')))
    variables:
      pacEnvironmentSelector: epac-preprod
    jobs:
      - job: planJob
        steps:
          - checkout: self

          - task: AzurePowerShell@5
            name: planStep
            displayName: Plan
            inputs:
              azureSubscription: $(tenantPlanServiceConnection)
              pwsh: true
              azurePowerShellVersion: LatestVersion
              ScriptPath: "Scripts/Deploy/Build-DeploymentPlans.ps1"
              ScriptArguments:
                -pacEnvironmentSelector $(pacEnvironmentSelector) `
                -devOpsType "ado" `
                -InformationAction Continue


          # Publish pipeline Artifact for ADO Service
          - publish: "$(PAC_OUTPUT_FOLDER)/plans-$(pacEnvironmentSelector)"
            artifact: "plans-feature-branch-$(pacEnvironmentSelector)"
            condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))




  - stage: tenantPlanMainStage
    displayName: "Tenant Plan - Main Branch"
    dependsOn:
      - tenantPlanFeatureStage
    condition: and(not(failed()), not(canceled()), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      pacEnvironmentSelector: epac-preprod
    jobs:
      - job: planJob
        steps:
          - checkout: self
          - task: AzurePowerShell@5
            name: planStep
            displayName: Plan
            inputs:
              azureSubscription: $(tenantPlanServiceConnection)
              pwsh: true
              azurePowerShellVersion: LatestVersion
              ScriptPath: "Scripts/Deploy/Build-DeploymentPlans.ps1"
              ScriptArguments:
                -pacEnvironmentSelector $(pacEnvironmentSelector) `
                -devOpsType "ado" `
                -InformationAction Continue
          # Publish pipeline Artifact for ADO Service
          - publish: "$(PAC_OUTPUT_FOLDER)/plans-$(pacEnvironmentSelector)"
            artifact: "plans-$(pacEnvironmentSelector)"
            condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))



  - stage: tenantDeployPolicyStage
    displayName: "Tenant Deploy Policy"
    dependsOn:
      - tenantPlanMainStage
    condition: and(not(failed()), not(canceled()), eq(dependencies.tenantPlanMainStage.outputs['planJob.planStep.deployPolicyChanges'], 'yes'), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      pacEnvironmentSelector: epac-preprod
      PAC_INPUT_FOLDER: "$(Pipeline.Workspace)"
    jobs:
      - deployment: deployPolicyJob
        environment: PAC-POLICY
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzurePowerShell@5
                  name: deployStep
                  displayName: Deploy Tenant1 Policy
                  inputs:
                    azureSubscription: $(tenantDeployServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-PolicyPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue


  - stage: tenantRolesStage
    displayName: "Tenant Deploy Role Assignments"
    dependsOn:
      - tenantDeployPolicyStage
    condition: and(not(failed()), not(canceled()), eq(dependencies.tenantPlanMainStage.outputs['planJob.planStep.deployRoleChanges'], 'yes'), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      pacEnvironmentSelector: epac-preprod
      PAC_INPUT_FOLDER: "$(Pipeline.Workspace)"
    jobs:
      - deployment: rolesJob
        environment: PAC-ROLES
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - task: AzurePowerShell@5
                  displayName: Deploy Tenant1 Role Assignments
                  inputs:
                    azureSubscription: $(tenantRolesServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-RolesPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue
                  condition: succeeded()`


Also and interesting error that resulted was I removed the two additional PSDs (aks and az cosmodb) samples and reset the PSD folder to ONLY have the EPAC provided `allowed_locations.json` and its policyAssignments that were part of the Github repo packaging and now I see after running the pipeline we get `Conflict` errors.

`PowerShell Versions: 7.2.10
***************************************************************************************************
Deploy Role assignments from plan in file './Output/plans-epac-dev/roles-plan.json'
Plan created on 2023-03-10 12:41:09Z.
***************************************************************************************************
===================================================================================================
Add (5) new Role assignments
---------------------------------------------------------------------------------------------------
: Contributor(b24988ac-6180-42a0-ab88-20f7382dd24c) at /providers/Microsoft.Management/managementGroups/epac-dev
Loaded Module 'Az.Accounts'
Loaded Module 'Az.MSGraph'
Loaded Module 'Az.Accounts'
Loaded Module 'Az.Authorization'
New-AzRoleAssignment: /home/vsts/work/1/s/Scripts/Deploy/Deploy-RolesPlan.ps1:102
Line |
 102 |  …   $result = New-AzRoleAssignment @splat -WarningAction SilentlyContin …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Conflict'

##[error]PowerShell exited with code '1'.
`

**Comment by isgo-golgo13** [comment]
@techlake "You should not make modifications to PAC_DEFINITIONS_FOLDER: "./StarterKit/Definitions". The sync script will override this folder on updating the repo from here. Instead, copy files you like to the Pipeline and Definitions folder at the repo root."

So for clarity, it is not recommended to add a subdirectory under `StarterKit/Definitions/` to group related PSDs (subdir aks, subdir az-storage, subdir az-networking)? 

Also you recommend we create our own top level `Definitions` folder and NOT use `StarterKit/Definitions` or use the `StarterKit/Defintions` and forgo the subdirectory PSD folders and just drop all of the PSDs into the `StarterKit/Definitions/policySetDefinitions` even if they are all of mixed domains (aks, az-storage, az-networking)?

**Comment by techlake** [comment]
Not what I said. You should never add or remove anything from StarterKit. Create new directries to the root of the repo called Pipelines and Definitions. Copy any items you want as staring points from the equivalen starter kit directories. You can than nest folders under policyDeinitions, policySetDefinitions and PolicyAssignments as deep as you like..

**Comment by techlake** [comment]
Please share the additional conflicts. I'll help you with fixes (and if necessary) bug fixes.

**Comment by techlake** [comment]
Also do not clone built-in Policies and Policy Sets EVER. You can use them as satrting points. do NOT clone them verbatim.

**Comment by isgo-golgo13** [comment]
Can we do a MS Teams call to share a screen to make it easier to understand the workflow vs pasting fragments. I will have to leave out sensitive info such as our subscription and mgmnt group ids. Or is stepped copy and paste threads of config snapshots the only way? 

Also shall I do any Git pulls from the fork we have ? Have there been any latest merges to the upstream EPAC gh repo?

**Comment by techlake** [comment]
Sure. Yes, we had an upstream merge yesterday. Minor bug fixes.

**Comment by isgo-golgo13** [comment]
@techlake I have not pulled from the fork yet and I think in error I did not fork properly. I also have the following structure to not reference directly the `StarterKit/`. Please see the following to ensure I am on the right path. At the root of our branch I created an organized structure as follows.

At the root of the EPAC repo I have created.

**ODCorpPipelines/**
   **azure-pipelienes.yaml**

**ODCorpDefinitions/**
    global-settings.jsonc

  **-> PolicySetDefinitions/**
          **allowed_locations.jsonc**

  **-> PolicyAssignments/**
             **allowed-locations-assignments.jsonc**

  **-> PolicyExemptions/**
          **-> None right now**

  **-> PolicyDocumentations/**
          **->   None right now**

    

The `ODCorpPIpelines/azure-pipelines.yaml` is as follows:

`variables:
  # This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
  PAC_OUTPUT_FOLDER: "./ODCorp-Output"
  PAC_DEFINITIONS_FOLDER: "..//ODCorpDefinitions"
  
  # Future directory of Azure Policy Set Definitions
  #PAC_DEFINITIONS_DIRECTORY: "./ODP/Definitions"

  # Use the plain text name of each service connection as a reference
  devServiceConnection: "svc-azure-epac"
  tenantPlanServiceConnection: "svc-azure-epac"
  tenantDeployServiceConnection: "svc-azure-epac"
  tenantRolesServiceConnection: "svc-azure-epac"


trigger:
  branches:
    include:
      - /*
  paths:
    include:
      - /*

pr: none


stages:
  - stage: devStage
    displayName: "DEV Plan, Deploy and Roles"
    #condition: and(in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), not(contains(variables['Build.SourceBranch'], 'refs/heads/main')))
    variables:
      pacEnvironmentSelector: epac-dev
    jobs:
      - deployment: allJob
        environment: PAC-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzurePowerShell@5
                  name: planStep
                  displayName: Plan
                  inputs:
                    azureSubscription: $(devServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Build-DeploymentPlans.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -devOpsType "ado" `
                      -InformationAction Continue


                # Publish pipeline Artifact for ADO Service
                - publish: "$(PAC_OUTPUT_FOLDER)/plans-$(pacEnvironmentSelector)"
                  artifact: "plans-$(pacEnvironmentSelector)"
                  condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))



                - task: AzurePowerShell@5
                  displayName: Deploy PAC-DEV Policy
                  condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))
                  inputs:
                    azureSubscription: $(devServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-PolicyPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue


                - task: AzurePowerShell@5
                  displayName: Deploy PAC-DEV Role Assignments
                  condition: and(not(failed()), not(canceled()), eq(variables['planStep.deployRoleChanges'], 'yes'))
                  inputs:
                    azureSubscription: $(devServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-RolesPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue


  - stage: tenantPlanFeatureStage
    displayName: "Tenant Plan - Feature Branch"
    dependsOn:
      - devStage
    condition: and(not(failed()), not(canceled()), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), not(contains(variables['Build.SourceBranch'], 'refs/heads/main')))
    variables:
      pacEnvironmentSelector: epac-preprod
    jobs:
      - job: planJob
        steps:
          - checkout: self

          - task: AzurePowerShell@5
            name: planStep
            displayName: Plan
            inputs:
              azureSubscription: $(tenantPlanServiceConnection)
              pwsh: true
              azurePowerShellVersion: LatestVersion
              ScriptPath: "Scripts/Deploy/Build-DeploymentPlans.ps1"
              ScriptArguments:
                -pacEnvironmentSelector $(pacEnvironmentSelector) `
                -devOpsType "ado" `
                -InformationAction Continue


          # Publish pipeline Artifact for ADO Service
          - publish: "$(PAC_OUTPUT_FOLDER)/plans-$(pacEnvironmentSelector)"
            artifact: "plans-feature-branch-$(pacEnvironmentSelector)"
            condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))




  - stage: tenantPlanMainStage
    displayName: "Tenant Plan - Main Branch"
    dependsOn:
      - tenantPlanFeatureStage
    condition: and(not(failed()), not(canceled()), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      pacEnvironmentSelector: epac-preprod
    jobs:
      - job: planJob
        steps:
          - checkout: self
          - task: AzurePowerShell@5
            name: planStep
            displayName: Plan
            inputs:
              azureSubscription: $(tenantPlanServiceConnection)
              pwsh: true
              azurePowerShellVersion: LatestVersion
              ScriptPath: "Scripts/Deploy/Build-DeploymentPlans.ps1"
              ScriptArguments:
                -pacEnvironmentSelector $(pacEnvironmentSelector) `
                -devOpsType "ado" `
                -InformationAction Continue
          # Publish pipeline Artifact for ADO Service
          - publish: "$(PAC_OUTPUT_FOLDER)/plans-$(pacEnvironmentSelector)"
            artifact: "plans-$(pacEnvironmentSelector)"
            condition: and(succeeded(), eq(variables['planStep.deployPolicyChanges'], 'yes'))



  - stage: tenantDeployPolicyStage
    displayName: "Tenant Deploy Policy"
    dependsOn:
      - tenantPlanMainStage
    condition: and(not(failed()), not(canceled()), eq(dependencies.tenantPlanMainStage.outputs['planJob.planStep.deployPolicyChanges'], 'yes'), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      pacEnvironmentSelector: epac-preprod
      PAC_INPUT_FOLDER: "$(Pipeline.Workspace)"
    jobs:
      - deployment: deployPolicyJob
        environment: PAC-POLICY
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzurePowerShell@5
                  name: deployStep
                  displayName: Deploy Tenant1 Policy
                  inputs:
                    azureSubscription: $(tenantDeployServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-PolicyPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue


  - stage: tenantRolesStage
    displayName: "Tenant Deploy Role Assignments"
    dependsOn:
      - tenantDeployPolicyStage
    condition: and(not(failed()), not(canceled()), eq(dependencies.tenantPlanMainStage.outputs['planJob.planStep.deployRoleChanges'], 'yes'), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      pacEnvironmentSelector: epac-preprod
      PAC_INPUT_FOLDER: "$(Pipeline.Workspace)"
    jobs:
      - deployment: rolesJob
        environment: PAC-ROLES
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - task: AzurePowerShell@5
                  displayName: Deploy Tenant1 Role Assignments
                  inputs:
                    azureSubscription: $(tenantRolesServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptPath: "Scripts/Deploy/Deploy-RolesPlan.ps1"
                    ScriptArguments:
                      -pacEnvironmentSelector $(pacEnvironmentSelector) `
                      -InformationAction Continue
                  condition: succeeded()`



When I run the pipeline I get the following:

*********************************************************************************************
Generating script.
Formatted command: . '/home/vsts/work/1/s/Scripts/Deploy/Build-DeploymentPlans.ps1' -pacEnvironmentSelector epac-dev ` -devOpsType "ado" ` -InformationAction Continue
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/cb1e06fb-391a-433e-8e58-54e287ab0b9b.ps1'
Saved!
Import-Module -Name /usr/share/az_9.3.0/Az.Accounts/2.12.1/Az.Accounts.psd1 -Global
Clear-AzContext -Scope Process
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Connect-AzAccount -ServicePrincipal -Tenant b0e0d312-bd1b-4314-a355-9ff726ed1063 -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope

===================================================================================================
Read global settings from '..//ODCorpDefinitions/global-settings.jsonc'.
===================================================================================================
Get-Content: /home/vsts/work/1/s/Scripts/Helpers/Get-GlobalSettings.ps1:27
Line |
  27 |      $Json = Get-Content -Path $globalSettingsFile -Raw -ErrorAction S …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | **Cannot find path
     | '/home/vsts/work/1/ODCorpDefinitions/global-settings.jsonc' because it
     | does not exist.**

***************************************************************

I look at the PS file in `Scripts/Helpers/Get-GlobalSettings.ps1 on line 27 and see this:

`Write-Information ""
    Write-Information "==================================================================================================="
    Write-Information "Read global settings from '$globalSettingsFile'."
    Write-Information "==================================================================================================="

    **_$Json = Get-Content -Path $globalSettingsFile -Raw -ErrorAction Stop_**
    if (!(Test-Json $Json)) {
        Write-Error "JSON file ""$($globalSettingsFile)"" is not valid = $Json" -ErrorAction Stop
    }`

Since I copied new global-settings.jsonc file into new `ODCorpDefinitions/` as originally it was in `StarterKit/Definitions` do I need to alter this PS script to prefix the path to `ODCorpDefinitions/` ? As I am not using the one in the `StarterKit/Definitions'/ root for this run.

Everything else is as it was with Scripts folder top-level still there not changing that. The `StarterKit` folder is just juxtaposed to the new ODPCorpDefinitons and ODPCorpPipelnes file at the root.

drwxr-xr-x  15 tomwallick  staff    480 Mar 15 15:22 .git
drwxr-xr-x   3 tomwallick  staff     96 Feb 16 15:29 .github
-rw-r--r--   1 tomwallick  staff     11 Feb 21 20:41 .gitignore
-rw-r--r--   1 tomwallick  staff    444 Feb 21 20:30 CODE_OF_CONDUCT.md
drwxr-xr-x  20 tomwallick  staff    640 Feb 21 20:30 Docs
-rw-r--r--   1 tomwallick  staff   1141 Feb 21 20:30 LICENSE
**drwxr-xr-x   8 tomwallick  staff    256 Mar 15 14:30 ODCorpDefinitions**
**drwxr-xr-x   3 tomwallick  staff     96 Mar 15 14:14 ODCorpPipelines**
-rw-r--r--   1 tomwallick  staff  14244 Feb 21 20:47 README.md
-rw-r--r--   1 tomwallick  staff   2781 Feb 21 20:30 SECURITY.md
-rw-r--r--   1 tomwallick  staff    388 Feb 21 20:30 SUPPORT.md
drwxr-xr-x   6 tomwallick  staff    192 Feb 21 20:30 Scripts
drwxr-xr-x   4 tomwallick  staff    128 Feb 21 20:30 StarterKit.       ---------> Not using this
-rw-r--r--   1 tomwallick  staff   3790 Feb 21 20:30 Sync-Repo.ps1



Doing a `tree` command at the top level on the `ODCorpPipelines` directory I have this:
`ODCorpPipelines
└── azure-pipelines.yaml

Doing a `tree` command at the top level of the `ODCorpDefinitions` directory I have this:
`ODCorpDefinitions
├── PolicyAssignments
│   └── az-org-governance
│       └── allowed-locations-assignments.jsonc
├── PolicyDefinitons
├── PolicyDocumentations
├── PolicyExemptions
├── PolicySetDefinitions
│   └── az-org-governance
│       └── allowed-locations.jsonc
└── global-settings.jsonc`

**Comment by techlake** [comment]
Depending on OS (Linux) you need to use the right vases for policyDefinitions, policySetDefinition, .... PS: Git will not fix this if you change it on a Windows machine for editing. It should work on a Linux workstation.

**Comment by techlake** [comment]
PS: When including code (such as json or ps1) ring fence it with triple back ticks (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) formats the code blocks. Use triple backtick and the type of code (without a space between the backticks and the word); some valid names are json, jsonc, ps1 and md. I used this below to show you the results.

```markdown
# Test

* Bullet
* Two
```

```jsonc
{
    "text": "value"
}
```
```ps1
$x = $null
New-Item $x -Type "folder"
```

**Comment by isgo-golgo13** [comment]
@techlake I got the Azure Pipeline to provision a full CIS benchmark and verify its deployment in the Azure Portal. However I now like apply a Azure Policy Assignment scope to a given management group and I dropped the following assignment policy and get an error like this:

`===================================================================================================
Processing Policy Assignments JSON files in folder './ODCorp/Definitions/policyAssignments'
===================================================================================================
Number of Policy Assignment files = 2
Loaded Module 'Az.Accounts'
Loaded Module 'Az.MSGraph'
Loaded Module 'Az.Accounts'
Loaded Module 'Az.Authorization'
Calculating effect parameters for 2883 Policies.
Calculating effect parameters for 94 Policy Sets.
Processing file '/home/vsts/work/1/s/ODCorp/Definitions/policyAssignments/az-org-governance/allowed-locations-assignments.jsonc'
Processing file '/home/vsts/work/1/s/ODCorp/Definitions/policyAssignments/az-org-governance/cis-1.4-benchmark-assignments.jsonc'
Build-AssignmentDefinitionNode: /home/vsts/work/1/s/Scripts/Helpers/Build-AssignmentPlan.ps1:101
Line |
 101 |  …       $hasErrors, $assignmentsList = Build-AssignmentDefinitionNode `
     |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |     Missing nodeName at child of //Unknown//
`

The policy assignment is a copy with only value changes to the properties of the CIS benchmark. 

{
    "nodeName": "/CIS_Azure_1_4_0/",
    "assignment": {
        "name": "CIS Microsoft Azure Foundations Benchmark v1.4.0",
        "displayName": "CIS Microsoft Azure Foundations Benchmark v1.4.0 Policy Assignment",
        "description": "CIS Microsoft Azure Foundations Benchmark v1.4.0 Policy Assignment"
    },
    "definitionEntry": {
        "policySetName": "CIS Microsoft Azure Foundations Benchmark v1.4.0",
    },
    "parameters": {
        "AllowedLocations": [
            "eastus2"
        ]
    },
    "scope": {
        "epac-dev": [
            "/providers/Microsoft.Management/managementGroups/epac-dev"
        ]
        // "tenant": [
        //     "/providers/Microsoft.Management/managementGroups/epac-preprod"
        // ]
    }
}

if you compare this to the one you offer in the Starter Kit for `allowed-locations-assignments.jsonc`, the key part that one I am trying to push has its `nodeName` value differ ofcourse.  

Do you have any other known sites or examples of how to apply an assignment jsonc file ?? What is this error ? **`Missing nodeName at child of //Unknown// ??**

**Comment by techlake** [comment]
It would appear (I'm not at my desk until tomorrow, that the error message is wrong (maybe a copy/paste issue on my part). The only thing I see wrong with your JSON, is the assignment.name. It needs to be no longer than 24 characters (Azure limit). Please shorten the name.

PS: Which version are you using.

**Comment by isgo-golgo13** [comment]
Looks like now I got the pipeline to work. I see the assignment provisioned.
