### ISSUE TITLE
Documentation is unclear on how to use exemptions

### ISSUE THREAD

**Issue by artisticcheese** [Azure/enterprise-azure-policy-as-code#154]
I'm confused about how do I create/manage exemptions with PAC.
Documentation mentions folder `exemptions` but neither `starter kit` no any examples are shown where the folder shall be located at and what hierarchy shall look like. Supplemental scripts are not working either (submitted PR for those). I do have now export of existing exemption definitions but not sure what to do with them.

**Comment by techlake** [comment]
Create a folder for each EPAC Environment (see global-settings.jsonc) -- names must match exactly. Create a CSV file with the exemptions.

**Comment by artisticcheese** [comment]
1. Can be either CSV or JSON?
2. Folder will be under Definitions? Like below?
3. What file shall be used or it does not matter? Output produced 2 files named `active-exemptions` and `all-exemptions`, what is difference between those?

![image](https://user-images.githubusercontent.com/13176884/222196500-d5a33ec6-b507-4e98-82de-8c3bc4c415f4.png)

**Comment by techlake** [comment]
<img width="179" alt="image" src="https://user-images.githubusercontent.com/6719941/222197865-5238b661-8b71-46a8-a70b-54a4e0d83420.png">

**Comment by techlake** [comment]
1. Or both (I recommend you pick CSV
2. I showed you in the above screen shot.
3. I would use active-exemptions. It removes expired exemptions (they are included in the all-exemptions file), allowing EPAC to clean it up (delete the expired ones)
4. I tagged this issue with "documentation" and will address the gap in v7.0 (ETA next two weeks)

**Comment by artisticcheese** [comment]
Having both JSON and CSV located in the same folder would not cause issues with logic? My undestanding it's the same data, just in different format.

**Comment by techlake** [comment]
It will calculate the union (eliminating duplicates). I would stick with one file in one format. Or if it get too large, stick with one format.

**Comment by artisticcheese** [comment]
Yes, I planned to use only one but your example shown that you have both under `policyExemptions` folder.

**Comment by techlake** [comment]
Keeping it open as awork item
