### ISSUE TITLE
Getting several errors when running policy extractor

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#173]
When running Build-DefinitionsFolders.ps1 I am getting the following errors

Line |
32 |                  $definedHashtable = $definedObj.Clone()
    |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    | Method invocation failed because [System.Collections.Specialized.OrderedDictionary] does not contain a method named 'Clone'.
Remove-EmptyFields: C:\Code\Architecture\Azure\enterprise-azure-policy-as-code\Scripts\Helpers\Confirm-ObjectValueEqualityDeep.ps1:33
Line |
33 |                  Remove-EmptyFields -definition $definedHashtable
    |                  ~~~~~~~~~~~~~~~~~~
    | The term 'Remove-EmptyFields' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
InvalidOperation: C:\Code\Architecture\Azure\enterprise-azure-policy-as-code\Scripts\Helpers\Confirm-ObjectValueEqualityDeep.ps1:45
Line |
45 |                  $existingHashtable = $existingObj.Clone()
    |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    | Method invocation failed because [System.Collections.Specialized.OrderedDictionary] does not contain a method named 'Clone'.
Remove-EmptyFields: C:\Code\Architecture\Azure\enterprise-azure-policy-as-code\Scripts\Helpers\Confirm-ObjectValueEqualityDeep.ps1:46
Line |
46 |                  Remove-EmptyFields -definition $existingHashtable
    |                  ~~~~~~~~~~~~~~~~~~
    | The term 'Remove-EmptyFields' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

__________________________________________________________________________
Edit
__________________________________________________________________________

The Remove-EmptyFields -definition error was fixed by updating Build-DefinitionsFolders.ps1 to use Add-HelperScripts.ps1 instead of the common functions list.  

Still getting the clone() method error

**Comment by anwather** [comment]
Was this using the modified version of Build-DefinitionsFolders.ps1 I gave you yesterday?

**Comment by anwather** [comment]
@gregslack78 - please try with the version of [Build-DefinitionsFolder.ps1](https://gist.github.com/anwather/6aa9552660e3f0b4d6f49d0a4908e9a7) and this updated version of [Confirm-ObjectValueEqualityDeep.ps1](https://gist.github.com/anwather/6c12b16ece7485d9093693230e506ec9) . It is working for me at the moment - if it gets you past the issue I'll push a new module version containing both fixes. This functionality will be replaced in V7.0 though....

**Comment by gregslack78** [comment]
Getting the same issue.  Also getting this

InvalidOperation: C:\Code\Architecture\Azure\enterprise-azure-policy-as-code\Scripts\Helpers\Get-AzPolicyResources.ps1:250
Line |
250 |                          $uniquePrincipalIds[$principalId] = $true
    |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    | Index operation failed; the array index evaluated to null.

Want to also note that the errors originally reported were happening in the policy assignment extraction.

**Comment by techlake** [comment]
Policy extractor is a work in process. I'll try to get to it soon.

**Comment by anwather** [comment]
I'm unable to replicate this right now - so let's just wait until V7.0 is released (very soon) to continue this.

**Comment by anwather** [comment]
> @gregslack78 - please try with the version of [Build-DefinitionsFolder.ps1](https://gist.github.com/anwather/6aa9552660e3f0b4d6f49d0a4908e9a7) and this updated version of [Confirm-ObjectValueEqualityDeep.ps1](https://gist.github.com/anwather/6c12b16ece7485d9093693230e506ec9) . It is working for me at the moment - if it gets you past the issue I'll push a new module version containing both fixes. This functionality will be replaced in V7.0 though....

@techlake - this is what I did yesterday to try and fix the issue although I think it has caused other problems - will leave it alone now and just wait for V7.0
