### ISSUE TITLE
Release package format

### ISSUE THREAD

**Issue by arnaud-tincelin** [Azure/enterprise-azure-policy-as-code#179]
We are using EPAC in a gitlab pipeline and to ease things we have created a docker image with EPAC installed. This is the dockerfile we are using:

```docker
FROM mcr.microsoft.com/azure-powershell:ubuntu-22.04

RUN apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/* 

ARG EPAC_VERSION
RUN wget -qO - https://github.com/Azure/enterprise-azure-policy-as-code/archive/refs/tags/${EPAC_VERSION}.tar.gz | tar -xvz \
  && mv ./enterprise-azure-policy-as-code-${EPAC_VERSION} /epac

ENTRYPOINT []
```

This dockerfile was working fine for releases before v7.0.0 as they were not prefixed with "v". The download link used to be in the format https://github.com/Azure/enterprise-azure-policy-as-code/archive/refs/tags/x.x.x.tar.gz and at the root of this archive there was a folder named in the format `enterprise-azure-policy-as-code-x.x.x`.

Starting from v7.0.0, the last part of the url changed to tags/**v**x.x.x.tar.gz (note the `v` before x.x.x), but the folder within remains the same as for previous versions (no `v`), hence this dockerfile is not working anymore.

Would it be possible to:
1. keep the same release naming convention (i.e. no `v` prefix)
1. have all archive files directly at the root of the archive file (remove the root folder `enterprise-azure-policy-as-code-x.x.x`) as this first folder is redundant (we already know we are downloading version x.x.x) and not very convenient to use in a CI/CD pipeline since the name changes

Thank you

**Comment by anwather** [comment]
@arnaud-tincelin - apologies - this is now fixed.

You can use the PowerShell module instead of downloading the release. This will also solve your archive folder issue. 

Be aware of the changes to some parameters (must specify -outputFolder and -inputFolder where required) https://azure.github.io/enterprise-azure-policy-as-code/powershell-module/
