### ISSUE TITLE
Support for EnforcementMode on policy assignments

### ISSUE THREAD

**Issue by louis-boro** [Azure/enterprise-azure-policy-as-code#20]
Hello, 

I am trying to make the [EnforcementMode](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#enforcement-mode) property working on policy assignment but it does not seem to be supported from the examples in this repository. 

I would like to be able to assign the same policy with different EnforcementMode per environment. For instance, I would like to assign a 'DeployIfNoExists' policy with EnforcementMode ='Default' in development and  EnforcementMode ='DoNotEnforce' in production.

I have investigated the PowerShell deployment code and my finding is the following : The parameter is passed to the New-AzPolicyAssigment and Set-AzPolicyAssigment commands, but the actual EnforcementMode is not defined in the deployment plan and it looks like it is ignored. 

I would expect something similar to the assigment file below to take the enforcementMode property into account during the assigment : 
```json
{
  "nodeName": "ParentNode",
  },
  "definitionEntry": {
    "policyName": "{policyGuid}",
    "friendlyNameToDocumentIfGuid": "Sets allowed location for CosmosDB"
  },
  "children": [
    {
      "nodeName": "ChildNode",
      "enforcementMode": "doNotEnforce",
      "parameters": {
        "policyEffect": "deny"
      },
      "assignment": {
        "Name": "Allowed Locations - DEV",
        "displayName": "Allowed Locations for CosmosDB",
        "description": "Sets the allowed locations for Cosmos DB"
      },
      "scope": {
        "PAC-DEV-001": ["/subscriptions/{subscriptionId}"]
      }
    }
```

Here is an example of the deployment plan for the assigment above, note that the EnforcementMode is not stored in the newAssigments collection : 

```json
  "replacedAssignments": {},
  "replacedInitiativeDefinitions": {},
  "updatedInitiativeDefinitions": {},
  "createdOn": "2022-02-03 16:41:19Z",
  "removedIdentities": {},
  "rootScope": "/subscriptions/{subscriptionGuid}",
  "updatedPolicyDefinitions": {},
  "newAssignments": {
    "/subscriptions/{subscriptionGuid}/providers/Microsoft.Authorization/policyAssignments/Allowed Locations - DEV": {
      "Scope": "/subscriptions/{subscriptionGuid}",
      "Metadata": {},
      "policyId": "/subscriptions/{subscriptionGuid}/providers/Microsoft.Authorization/policyDefinitions/{policyGuid}",
      "DefinitionEntry": {
        "policyName": "{policyGuid}",
        "friendlyNameToDocumentIfGuid": "Sets allowed location for CosmosDB"
      },
      "Description": "Sets the allowed locations for Cosmos DB",
      "DisplayName": "Allowed Locations for CosmosDB",
      "identityRequired": false,
      "managedIdentityLocation": "eastus2",
      "PolicyParameterObject": {
        "policyEffect": "deny",
        "listOfAllowedLocations": [
          "centralus",
          "eastus",
          "eastus2",
          "southcentralus"
        ]
      },
      "Id": "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/policyAssignments/Allowed Locations - DEV",
      "Name": "Allowed Locations - DEV"
    }
  },
  "noChanges": false,
  "newPolicyDefinitions": {}

```

**Comment by techlake** [comment]
We purposely didn't use enforcementMode since it was broken at the time. Instead, we use the "ignoreBranch" flag to not deploy the Policy at all.

**Comment by louis-boro** [comment]
> We purposely didn't use enforcementMode since it was broken at the time. Instead, we use the "ignoreBranch" flag to not deploy the Policy at all.

Thank you for the quick answer, is the feature considered fixed now? If so, would it be possible to support it in the future?

Thanks again.

**Comment by techlake** [comment]
I don't know. I would use the ignoreBranch. It works great. However, if you have a reason for needing enforcementMode  to satisfy your use case then we will investigate and consider a change.

**Comment by louis-boro** [comment]
> I don't know. I would use the ignoreBranch. It works great. However, if you have a reason for needing enforcementMode to satisfy your use case then we will investigate and consider a change.

I have a client which relies heavily on the enforcementMode as part of their Azure policy rollout and they would like to stick with the same process (rolling out the policy in production with enforcementMode = DoNotEnforce).

I think supporting this use case would make the transition easier for them. Also, since the enforcementMode is a feature that is deployable when using PowerShell or ARM/Bicep when doing Policy Assignment, I would argue that supporting it in this project will further improve on an already amazing product. 

As for the ignoreBranch feature, thank you for the information. Unfortunately, without your comment I would not have been able to use it as it is not referenced in the documentation or the examples. 

I have recently come across this project and I am very satisfied with the results. I want to make sure this project remains the greatest way to deploy policies in Azure.

Thanks again.

**Comment by techlake** [comment]
Got It. I will add enforcementMode after next PR.  I'm currently focused on getting the operational script improvements integrated.

PS: I really appreciate your detailed bug repro steps. This is a great example on how to file bugs and feature requests.

**Comment by techlake** [comment]
I tagged the issue as an enhancement.

**Comment by techlake** [comment]
@louis-boro can you please confirm that the fix works for your scenario. thank you!
