### ISSUE TITLE
Array parameters causing assignment failures

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#211]
It looks like recent changes are causing array parameters in assignments to not process properly.  An assignment that worked about a week ago is no longer functioning with the following error

Write-Error: /agent/_work/1/s/Scripts/Deploy/Deploy-PolicyPlan.ps1:272
Line |
 272 |  … splayName = Set-AzPolicyAssignmentRestMethod -assignment $_ -currentD …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Assignment error 400 --
     | {"error":{"code":"InvalidPolicyParameters","message":"A function or
     | parameter in policy set or assignment '1d48f6dd699943a4b9a56b4d'
     | associated with the policy definition 'vnet-peer-to-matching-hub-region'
     | could not be validated. If using template functions, try following the
     | tips in: https://aka.ms/policy-avoiding-template-failures. The inner
     | exception 'The language expression property 'hublist' doesn't exist,
     | available properties are 'environment'.'."}}

The plan file appears to show the correct structure for the parameter array and matches what is in the assignment file....

"/providers/Microsoft.Management/managementGroups/EPaC-XX-intranet/providers/Microsoft.Authorization/policyAssignments/1d48f6dd699943a4b9a56b4d": {
        "parameters": {
          "app_service_must_use_vnet_integration_Effect": "deny",
          "route_tables_must_have_hub_firewall_as_default_next_hop_NextHopIPs": [
            "10.10.10.10",
          ],
          "AKS_must_have_outBoundType_of_UDR_Effect": "deny",
          "vnet_peer_to_match_hub_region_Effect": "deny",
          "route_tables_must_have_hub_firewall_as_default_next_hop_Effect": "deny",
          "VNet_Peer_To_Matching_Hub_Region_HubIDs_By_Environment": [
            {
              "environment": "SecureSandbox",
              "hublist": [
                "/subscriptions/xxxxxxxx-dbb3-45e8-bd7a-b8b557bb8c94/resourceGroups/a203578-dt1-musea1-rg001-UC/providers/Microsoft.Network/virtualNetworks/a203578-dt1-musea1-vnet001-UC",
                "/subscriptions/xxxxxxxxx-e987-4793-939d-450d3f17c252/resourceGroups/a211249-d1-musea1-rg001/providers/Microsoft.Network/virtualNetworks/a211249-d1-musea1-vn001"
              ]
            },
            {
              "environment": "DevTest",
              "hublist": [
                "/subscriptions/xxxxxxxxx-dbb3-45e8-bd7a-b8b557bb8c94/resourceGroups/a203578-dt1-musea1-rg001-UC/providers/Microsoft.Network/virtualNetworks/a203578-dt1-musea1-vnet001-UC",
                "/subscriptions/xxxxxxx-e987-4793-939d-450d3f17c252/resourceGroups/a211249-d1-musea1-rg001/providers/Microsoft.Network/virtualNetworks/a211249-d1-musea1-vn001"
              ]
            },
            {
              "environment": "Prod"
            }
          ],

Relevant section of the policySet

      {
        "policyDefinitionReferenceId": "VNet peer to matching hub region_1",
        "policyDefinitionName": "vnet-peer-to-matching-hub-region",
        "parameters": {
          "effect": {
            "value": "[parameters('vnet_peer_to_match_hub_region_Effect')]"
          },
          "hubIds": {
            "value": "[parameters('VNet_Peer_To_Matching_Hub_Region_HubIDs_By_Environment')]"
          }
        }
      },

Relevant section of policy with some redactions....

      "hubIds": {
        "allowedValues": null,
        "defaultValue": [
          {
            "environment": "DevTest",
            "hublist": []
          },
          {
            "environment": "Prod",
            "hublist": []
          }
        ],
          "displayName": "HubIds list by assignment location",
          "portalReview": true
        },
        "type": "Array",
        "schema": null
      }

**Comment by techlake** [comment]
Looks like a bug. The whole array handling is painful in PowerShell. Before I ask you for a redacted copy of the actual Policy to recreate in my environment, I would like to get some more debugging output.

Just to confirm, you are using v7.1.4

In file Scripts/Helpers/Set-AzPolicyAssignmentRestMethod.ps1, please replace the for loop starting on line 18 with this enlarged code:

```ps1
    foreach ($parameterName in $parametersTemp.Keys) {
        $value = $parametersTemp.$parameterName
        if ($parameterName -eq 'hublist') {
            Write-Information "  parameter $parameterName ="
            Write-Information "    inp: $(ConvertTo-Json $value -Depth 5 -Compress)"
        }
        $parameters.$parameterName = @{
            value = $value
        }
        if ($parameterName -eq 'hublist') {
            Write-Information "  parameter $parameterName ="
            Write-Information "    mod: $(ConvertTo-Json $value -Depth 5 -Compress)"
        }
    }
```
Can you also check if the Policy definition and Initiative definition in the portal are correct?

If you for some reason can modify the code, please send the actual Policy definition and I reproduce it in my test environment.

**Comment by techlake** [comment]
I may have found the culprit. Q: 
In the defaultValue for hublist parameter in the policySet (Initiative) definition, are there empty arrays?

If you look in the Portal at the Initiative definition is the parameter definition correct?

**Comment by gregslack78** [comment]
In the defaultValue for hublist parameter in the policySet (Initiative) definition, are there empty arrays?

Yes

      "VNet_Peer_To_Matching_Hub_Region_HubIDs_By_Environment": {
        "allowedValues": null,
        "defaultValue": [
          {
            "environment": "DevTest",
            "hublist": [
              ""
            ]
          },
          {
            "environment": "Prod",
            "hublist": [
              ""
            ]
          }
        ],
        "metadata": {
          "displayName": "VNet Peer To Matching Hub Region HubIDs By Environment",
          "description": "Resource IDs for vnet Hub by environment.  Example: {\"environment\": \"DevTest\", \"hublist\": [\"/subscriptions/xxxxxxx-80bb-48f7-a60b-xxxxxxxx1/resourceGroups/abc-d1-musea2-rg001/providers/Microsoft.Network/virtualNetworks/VNet-hub-eus2\", \"/subscriptions/xxxxxxxx-80bb-48f7-a60b-xxxxxxxxxxxx/resourceGroups/abc-d1-musea2-rg001/providers/Microsoft.Network/virtualNetworks/VNet-hub-eus\", \"VNet-hub-eus2\"]}",
          "portalReview": true
        },
        "schema": null,
        "type": "array"
      },


If you look in the Portal at the Initiative definition is the parameter definition correct?

It appears to be.

[cid:fadef050-f039-4202-806d-d4b262f38b28]

________________________________

**Comment by techlake** [comment]
There goes that idea :-(. I'm reworking something and trying to get an updated version out tonight. If you don't mind being the test case, can you test it tomorrow, please? It will also contain your fix for the Export function with user-assigned MIs.

**Comment by gregslack78** [comment]
Happy to test anything you like.  We're looking at things on our end as well.  I'm running an EPaC lab tomorrow morning but can get to this in the afternoon.

________________________________

**Comment by techlake** [comment]
Fix has passed testing. We are waiting for #212 testing to complete before releasing an updated version.
