### ISSUE TITLE
Failures caused when user assigned managed identities are attached to assignments

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#212]
I received errors when attempting extracts and deployments when user assigned identities were a part of assignments.  The fix was in Get-AzPolicyResources.ps1 at approximately line 247 

![image](https://user-images.githubusercontent.com/85254974/234432236-3e9e476d-a193-4d96-838f-c567ea8b99bc.png)

                    $null = $policyAssignmentsTable.all.Add($id, $policyResource)
                    $null = $policyAssignmentsTable.managed.Add($id, $policyResource)
                    if ($policyResource.identity -and $policyResource.identity.type -ne "None") {
                        if($policyResource.identity.type -eq "SystemAssigned"){
                            $principalId = $policyResource.identity.principalId
                        } else {
                            $userAssignedIdentityId = $policyResource.identity.userAssignedIdentities.PSObject.Properties.Name
                            $principalId = $policyResource.identity.userAssignedIdentities.$userAssignedIdentityId.principalId
                        }
                        $null = $assignmentsWithIdentity.Add($id, $policyResource)
                        Set-UniqueRoleAssignmentScopes `
                            -scopeId $scope `

**Comment by anwather** [comment]
I can take a look at this one later today

**Comment by anwather** [comment]
@techlake the code above does stop the error - however the managed identity is not present in the assignment file.

**Comment by techlake** [comment]
I'll take a look. I already added the above code

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by techlake** [comment]
We are testing the fix.
