### ISSUE TITLE
Getting error when extracting exemptions

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#229]
Using latest as of about an hour ago, I'm getting the following error when running .\Export-AzPolicyResources.ps1 -exemptionFiles 'json'

======================================================================================
Output Exemption list (1)
======================================================================================
d----            5/4/2023  3:55 PM                epac-test
Output active Exemption list (1) for epac environment 'epac-test'
InvalidArgument: C:\Users\gregslack\Repositories\EPaC-3\Scripts\Helpers\Out-PolicyExemptions.ps1:83:21
Line |
  83 |                      $outputJson = @{
     |                      ~~~~~~~~~~~~~~~~
     | Cannot create object of type "System.Management.Automation.SwitchParameter". The property 'exemptions' was not found for the
     | 'System.Management.Automation.SwitchParameter' object. There is no settable property available.

It works fine when not specifying json format.

Getting the same error when running .\Get-AzExemptions.ps1 but this does generate the csvs fine.

In both cases it is creating the appropriate active exemptions files but the content is

{
  "IsPresent": true
}

**Comment by gregslack78** [comment]
Calling it quits for the day so I haven't been able to thoroughly test this, but updating $outputJson to $outputJsonSwith an lines 8 and 66 fixed it for my one exemption at one scope.  Coming back to this tomorrow.

**Comment by anwather** [comment]
Fixed in v7.1.12
