### ISSUE TITLE
Exception handling enhancement for role assignments

### ISSUE THREAD

**Issue by leilatazi** [Azure/enterprise-azure-policy-as-code#23]
Hello,

I am trying to deploy a policy assignment with the effect deployIfNotExists, which requires assigning a role definition Id to the policy assignment. The first deployment went through without issues but the subsequent deployments fail with the below error message. 

Please note that I am using the suppressDeletes flag in the pipeline because I am not in a greenfield environment.

Here is the error I am getting from the pipeline (using Microsoft Hosted Agent with the latest PS version): 

```
New-AzRoleAssignment: /home/vsts/work/1/s/Scripts/Deploy/Deploy-AzPoliciesInitiativesAssignmentsFromPlan.ps1:310
Line |
 310 |  …     $null = New-AzRoleAssignment -Scope $scope -ObjectId $identity.Pr …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Conflict'
```

My understanding is that the below code extract from the Deploy-AzPoliciesInitiativesAssignmentsFromPlan.ps1 script is not catching properly the error above.

```
 try {
                    $null = New-AzRoleAssignment -Scope $scope -ObjectId $identity.PrincipalId -RoleDefinitionId $roleDefinitionId
                    $needToRetry = $false
                }
                catch {
                    If ($_.Exception.Message.Contains("role assignment already exists")) {
                        # Write-Host "##[warning] Role assignment already existed: New-AzRoleAssignment -Scope $($scope) -ObjectId $($identity.PrincipalId) -RoleDefinitionId $roleDefinitionId"
                        $needToRetry = $false
                    }
```

I reproduced the error on my side and here is what I found. When the role assignment already exists, the New-AzRoleAssignment command returns the following when using -Debug:

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : 18bab13e-6f34-4db0-9c63-577b528e381c
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Set-Cookie                    : x-ms-gateway-slice=Production; path=/; secure; samesite=none; httponly
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 8971e555-a448-4cc6-8954-e3994e71692f
x-ms-routing-request-id       : EASTUS:20220218T135107Z:8971e555-a448-4cc6-8954-e3994e71692f
Date                          : Fri, 18 Feb 2022 13:51:06 GMT

Body:
{
  "error": {
    "code": "RoleAssignmentExists",
    "message": "The role assignment already exists."
  }
}

---------------------------------------------------------------------------------------------------------------------------
```

When looking at the exception message this returned: 

```
PS /home/leila> $error.Exception.Message
Operation returned an invalid status code 'Conflict'
```

When looking at the error specified in the body of the exception, this is returned: 

```
PS /home/leila> $error.Exception.Body.Error.Message
The role assignment already exists.
```

I replaced the exception catch in my version of the code and it works properly.

I am new on GitHub, should I submit a PR to fix the bug or should I let your team push the fix?

Thank you 
Very happy with your policy deployment framework so far!

**Comment by techlake** [comment]
Hi Louis, thank you for submitting the issue and a Fix. Unfortunately, I'm doing a change to that section and moved to az cli; However, based on your feedback, I'll go back to PS Az Module and use your solution. I should have a merged solution within a week.

**Comment by techlake** [comment]
I solved the issue differently. az cli does not generate the error in question.
