### ISSUE TITLE
Error: invalidlocationupdate The existing assignment location cannot be changed from "uksouth" to "."

### ISSUE THREAD

**Issue by rowbot-99** [Azure/enterprise-azure-policy-as-code#246]
Hi, update policy assignments with null identity type seems to have the error above, all other assignments with system assigned or user assigned don't have this error. Any idea what could be causing this issue?

**Comment by anwather** [comment]
Can you provide clear repro steps and I can take a look?

**Comment by fabdi00** [comment]
Hey, yh so I had enterprise scale deploy the policies, now I'm trying to manage the policies using this tool going forward. I pulled down the existing policies using export-azurepolicyresources and moved the folders inside the definitions folder. I ran the build pipeline which produced deploy.json and now I get this error during deploy stage.

**Comment by anwather** [comment]
OK it could be the managed identities for those policies, they may be deployed in a different region to what you have specified in your global-settings.json.

Can you check a managed identity location for one of the deployed policies and see if it matches what you have specified?

Other way to fix it may be to rename the assignment files in the definition folder, run the deploy which will remove all the assignments. Then name them back to json files and redeploy them

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
Also post your global settings file so I can take a look.

**Comment by fabdi00** [comment]
actually the pipeline fails when it starts processing the policies that doesn't use idenities: identity: none, the ones that have identity: system assigned are fine. I just checked one of identities used and the location is uksouth. 

This is my global settings file
```
{
    "pacOwnerId": "11111111-2222-3333-4444-555555555555",
    "pacEnvironments": [
        {
            "pacSelector": "epac-dev",
            "cloud": "AzureCloud",
            "tenantId": "id",
            "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/lz"
        }
        
    ],
    "managedIdentityLocations": {
        "*": "uksouth"
    },
    "globalNotScopes": {
        "*": [
            "/resourceGroupPatterns/excluded-rg*",
        ],
        "tenant": [
            "/providers/Microsoft.Management/managementGroups/EPAC-Dev"
        ]
    }
}
```
an example of failing assignment is Deny-Public-IP

Thanks

**Comment by anwather** [comment]
Ah I think I know what is happening, can you post the assignment file for that Deny-Public-IP assignment? It probably is putting in a null entry for identity which needs to be removed from the file....

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fabdi00** [comment]
This is it from my policy-plan.json
```
"/providers/Microsoft.Management/managementGroups/lz-identity/providers/Microsoft.Authorization/policyAssignments/Deny-Public-IP": {
          "metadata": {
            "pacOwnerId": "11111111-2222-3333-4444-555555555555"
          },
          "id": "/providers/Microsoft.Management/managementGroups/lz-identity/providers/Microsoft.Authorization/policyAssignments/Deny-Public-IP",
          "notScopes": [],
          "parameters": {
            "listOfResourceTypesNotAllowed": [
              "Microsoft.Network/publicIPAddresses"
            ]
          },
          "identity": {
            "type": "None"
          },
          "enforcementMode": "DoNotEnforce",
          "displayName": "Deny the creation of public IP",
          "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/6c112d4e-5bc7-47ae-a041-ea2d9dccd749",
          "description": "This policy denies creation of Public IPs under the assigned scope.",
          "scope": "/providers/Microsoft.Management/managementGroups/lz-identity",
          "name": "Deny-Public-IP",
          "identityRequired": false,
          "nonComplianceMessages": [
            {
              "message": "Public IPs should not be created under this scope."

            }
          ]
        },
```
Thanks

**Comment by anwather** [comment]
Can you check the assignment files which have been extracted from the environment - remove any ```managedIdentityLocations``` keys in those files? Also any ```roles``` sections in the ```metadata``` keys?

**Comment by fabdi00** [comment]
The original assignment I extracted from my environment for deny public ip
doesn’t have neither of those properties, No metadata or
managedidentitylocations in the file.

**Comment by anwather** [comment]
OK weird can you download the latest version of the module and try again?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
Let me try and take another look at this one tomorrow for you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
I would recommend deleting the assignment in the portal and letting EPAC recreate it - the policy assignments deployed by ALZ seem to have a location property available on them - while policy assignments deployed by EPAC do not. This causes the policy API to throw an error when deploying. This property is only required for policies which have a managed identity assigned to them however all of the policies deployed by ALZ have this for some reason. Since this is going to be a specific edge case I would recommend just deleting them and recreating them ..

**Comment by rowbot-99** [comment]
Ok, could do that. Maybe worth adding this to the documentation, surely I won't be the only one trying to do something similar. 

Thanks for your help.

**Comment by rowbot-99** [comment]
I have been playing around with this and was thinking the following could be added to resolve this issue, what do you think?

```
if ($assignmentObj.identityRequired -eq $true) {
  $assignment.location = $assignmentObj.managedidentityLocation
} elseif ($assignmentObj.identityRequired -eq $false) {
  if (Get-AzPolicyAssignment - Name $assignmentObj.name -Scope $assignmentObj.scope -ErrorAction SilentlyContinue) {
  $assignment.Location = (Get-AzPolicyAssignment - Name $assignmentObj.name -Scope $assignmentObj.scope).Location
} else {
  write-information ''The Azure platform does not contain the requested assignment ('$($assignmentObj.name)')"
```

**Comment by techlake** [comment]
This used to work way back in the pre-OSS days and more importantly pre-User-Assigned-Identity. I'll investigate fixing this. The underlying API cannot change the location of the identity.

**Comment by anwather** [comment]
@techlake - let's discuss tomorrow - this is a really weird edge case - no identities are involved which makes it different

**Comment by soupercomputer** [comment]
+1 on this, i get the same issue. It seems to be a buggy API issue where it is storing a location against a Policy that doesnt need one. Ive seen similar issues to this on other Azure APIs when deploying with bicep. The API throws an error if you seem to be trying to change a value it shouldnt care about. Seems like an interim robust way to handle it would simply be to alter the code so that updates pass in location even if its not needed, i will use this fix myself for now - but then if the API gets fixed it will fail again.

**Comment by anwather** [comment]
@soupercomputer just curious as to how you deployed the policies causing issues? Were they part of Azure Landing Zones deployments?

**Comment by soupercomputer** [comment]
yep, was just evaluating the approach so built a LZ using the ESLZ Accelerator, its picking up those standard policies with the erroneous location codes. There also seems to be an issue deleting the assignments a) they dont all show up in the Policy assignments on the portal, though they do in Graph queries, and b) obviously they cant all be deleted in the poral as they dont show up, but it seems they cant be deleted by Remove-AzPolicyAssignment either. It comes back without error but the assignment persists. So a code workaround is the only way.

**Comment by techlake** [comment]
I might have a fix. If so, would you mind testing it?

Q: are you using the sync-repo method or the PowerShell market version?
