### ISSUE TITLE
Errors when trying to get User Assigned Identities

### ISSUE THREAD

**Issue by tellitube** [Azure/enterprise-azure-policy-as-code#252]
The following scripts need to be modified to cater for the user assigned identities:

Build-AssignmentIdentityChanges.ps1
The following error occurs in the pipeline 
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/39484634/bdc48559-3af3-427d-8cfe-d72f4381b04c)

This section of the script needs to be changed to avoid this error
`if ($hasExistingIdentity) {
        $existingIdentityType = $existingIdentity.type
        if ($existingIdentityType -eq "UserAssigned") {
            $existingUserAssignedIdentity = $existingIdentity.userAssignedIdentities.Keys[0]
        }
        $existingPrincipalId = $existingIdentity.principalId
        $existingLocation = $existing.location
        if ($deployedRoleAssignmentsByPrincipalId.ContainsKey($existingPrincipalId)) {
            $existingRoleAssignments = $deployedRoleAssignmentsByPrincipalId.$existingPrincipalId
        }
    }
    if ($identityRequired ) {
        $definedIdentity = $assignment.identity
        $definedIdentityType = $definedIdentity.type
        if ($definedIdentityType -eq "UserAssigned") {
            $definedUserAssignedIdentity = $definedIdentity.userAssignedIdentities.Keys[0]
        }
        $definedLocation = $assignment.managedIdentityLocation
        $requiredRoleDefinitions = $assignment.metadata.roles
    }`

Needs to be changed to this so it can access the user assigned identity properties
`if ($hasExistingIdentity) {
        $existingIdentityType = $existingIdentity.type
        if ($existingIdentityType -eq "UserAssigned") {
            $existingUserAssignedIdentity = ($existingIdentity.userAssignedIdentities | get-member)[-1].Name
        }
        if ($existingIdentityType -eq "UserAssigned") {
            $existingPrincipalId = $existingIdentity.userAssignedIdentities.$existingUserAssignedIdentity.principalId
        }else{
            $existingPrincipalId = $existingIdentity.principalId
        }
        $existingLocation = $existing.location
        if ($deployedRoleAssignmentsByPrincipalId.ContainsKey($existingPrincipalId)) {
            $existingRoleAssignments = $deployedRoleAssignmentsByPrincipalId.$existingPrincipalId
        }
    }
    if ($identityRequired ) {
        $definedIdentity = $assignment.identity
        $definedIdentityType = $definedIdentity.type
        if ($definedIdentityType -eq "UserAssigned") {
            $definedUserAssignedIdentity = ($definedIdentity.userAssignedIdentities | get-member)[-1].Name
        }
        $definedLocation = $assignment.managedIdentityLocation
        $requiredRoleDefinitions = $assignment.metadata.roles
    }`

The property $existingIdentity.userAssignedIdentities is a psobject not a hashtable so this was the way to get the key out of the object. Keys[0] does not work on psobjects only on hasthables. I have tested this and receive no errors

**Comment by anwather** [comment]
Can you please add steps in to repro this issue so I can test the proposed code?

**Comment by anwather** [comment]
@tellitube - it does fix that issue thanks - however it is still recommending a replace on the policy instead of no change - will look into how this is working
