### ISSUE TITLE
failing to update nonComplainceMessages

### ISSUE THREAD

**Issue by rowbot-99** [Azure/enterprise-azure-policy-as-code#253]
The build pipeline adds the following to the plan.json file

```
"nonComplianceMessages": [
    { 
       "Key": "message",
      "Value": "message"
    }
]
```

here is a snippet of my original assignment:

```
"definitionEntry": {
  "displayName": "Allowed Locations",
  "policyId": "/providers/Microsoft.Authorization/policyDefinitions/<id>
), 
"assignment": {
   "name": "allowed-locations",
   "displayName": "Allowed Locations"
}, 
"nonComplianceMessages": [
  {
     "message": "message"
  }
]
```
the deploy pipeline gives me this error

`"error": ("code": "InvalidRequest Content", "message": "The request content was invalid and could not be deserialized: Could not find member 'Key' on object of type 'NonComplianceMessage'. Path  'properties.nonComplianceMessages[0].key "}`

**Comment by anwather** [comment]
I've tested this on version 7.2.7 and cannot replicate - what version are you using?
