### ISSUE TITLE
Exemption Bug when updating policy reference ids

### ISSUE THREAD

**Issue by tellitube** [Azure/enterprise-azure-policy-as-code#254]
when adding to policy reference ids to existing exemptions they fail to update get the following error 
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/39484634/1126be66-38e9-477d-ac67-2703c595ab3e)
This is because we are not passing in policyDefinitionReferenceIds into theh splat transform strings so it doesnt get updated

Need to replace the code in the script Build-ExemptionsPlan.ps1
`# One or more properties have changed
                        $splatTransformStrings = @( "id/Id" )
                        if (!$displayNameMatches) {
                            $changesStrings += "displayName"
                            $splatTransformStrings += "displayName/DisplayName"
                        }
                        if (!$descriptionMatches) {
                            $changesStrings += "description"
                            $splatTransformStrings += "description/Description"
                        }
                        if (!$metadataMatches) {
                            $changesStrings += "metadata"
                            $splatTransformStrings += "metadata/Metadata"
                        }
                        if (!$exemptionCategoryMatches) {
                            $changesStrings += "exemptionCategory"
                            $splatTransformStrings += "exemptionCategory/ExemptionCategory"
                        }
                        if ($clearExpiration) {
                            $changesStrings += "clearExpiration"
                            $splatTransformStrings += "clearExpiration/ClearExpiration"
                        }
                        elseif (!$expiresOnMatches) {
                            $changesStrings += "expiresOn"
                            $splatTransformStrings += "expiresOn/ExpiresOn"
                        }
                        $changesString = $changesStrings -join ","
                        $splatTransformString = $splatTransformStrings -join " "
                        $exemption.splatTransform = $splatTransformString
                        $exemptions.numberOfChanges++
                        $null = $exemptions.update.Add($id, $exemption)
                        Write-Information "Update($changesString) '$($name)', '$($scope)'"`
With
`$splatTransformStrings = @( "id/Id" )
                        if (!$displayNameMatches) {
                            $changesStrings += "displayName"
                            $splatTransformStrings += "displayName/DisplayName"
                        }
                        if (!$descriptionMatches) {
                            $changesStrings += "description"
                            $splatTransformStrings += "description/Description"
                        }
                        if (!$policyDefinitionReferenceIdsMatches) {
                            $changesStrings += "policyDefinitionReferenceIds"
                            $splatTransformStrings += "policyDefinitionReferenceIds/PolicyDefinitionReferenceId"
                        }
                        if (!$metadataMatches) {
                            $changesStrings += "metadata"
                            $splatTransformStrings += "metadata/Metadata"
                        }
                        if (!$exemptionCategoryMatches) {
                            $changesStrings += "exemptionCategory"
                            $splatTransformStrings += "exemptionCategory/ExemptionCategory"
                        }
                        if ($clearExpiration) {
                            $changesStrings += "clearExpiration"
                            $splatTransformStrings += "clearExpiration/ClearExpiration"
                        }
                        elseif (!$expiresOnMatches) {
                            $changesStrings += "expiresOn"
                            $splatTransformStrings += "expiresOn/ExpiresOn"
                        }
                        $changesString = $changesStrings -join ","
                        $splatTransformString = $splatTransformStrings -join " "
                        $exemption.splatTransform = $splatTransformString
                        $exemptions.numberOfChanges++
                        $null = $exemptions.update.Add($id, $exemption)
                        Write-Information "Update($changesString) '$($name)', '$($scope)'"`

**Comment by techlake** [comment]
Sorry for the delay. I will tackle this one next. Thank you for also providing a fix.
