### ISSUE TITLE
Enable-DDoS-Vnet role being removed

### ISSUE THREAD

**Issue by rowbot-99** [Azure/enterprise-azure-policy-as-code#257]
Hello, Me again. I have a strange issue where the above role is always being picked for removal when i try to delete assignments that are not related. For eg i just created a dummy assignment using builtin definition with deny effect and now when i try to remove the assignment, the roles-plan is picking the above role for removal and the role is managed by pac.

**Comment by techlake** [comment]
Can we setup a debugging session?

**Comment by techlake** [comment]
Or send me a reacted plan file, policy definition and assignment file.

**Comment by rowbot-99** [comment]
Hey, i just tried it on a different environment and i can't replicate this,Please feel free to close this issue for now. Thanks
