### ISSUE TITLE
Export hanging at the Optimizing Policy Assignment Trees during export

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#258]
Getting stuck in the optimizing policy assignment tree step in export-AzPolicyAssignments.ps1.  The only param being used is to specify which EPaC environment to extract and I'm taking defaults on everything else.  I pulled latest scripts folder yesterday.

=========================================
Optimizing 127 Policy Assignment trees
=========================================

**Comment by techlake** [comment]
Greg, can you contact me at Heinrich dot Gantenbein atsign Microsoft dot com to arrange for a private chat about your issue.

**Comment by techlake** [comment]
I'm assuming this is resolved and is not a bug
