### ISSUE TITLE
Parameters propagation on policyAssignments policy

### ISSUE THREAD

**Issue by Hulk-101** [Azure/enterprise-azure-policy-as-code#260]
When deploying an assignment with the new version (_v.7.2.8_), the parameters are not propagated to the children nodes.

In the following example, the parameters `**paramA**` and `**paramB**` are not propagated to the children node name `**DEV**`.

Please note that this implementation worked in _v.5.3.9_.

Example, you have the following **assignment** .. 
<pre>
{
  "nodeName": "rootNode",
  "definitionEntry": {
    "initiativeName": "initiativeX",
    "friendlyNameToDocumentIfGuid": "Initiative X"
  },
  "assignment": {
    "name": "initiativex",
    "displayName": "Initiative assignment X",
    "description": "This initiative contains multiple policies."
  },
  "parameters": {
    "paramA": "a",
    "paramB": "b"
  },
  "children": [
    {
        "nodeName": "DEV",
        "parameters": {
          "paramC": "c",
          "paramD": "d"
        },
        "scope": {
          "dev": [
            "/providers/Microsoft.Management/managementGroups/DEV"
          ]
        }
    }
  ]
}
</pre>

And the following **definition** ..
<pre>
{
  "name": "initiativex",
  "properties": {
    "displayName": "Initiative X definition",
    "description": "This initiative contains policies.",
    "metadata": {},
    "parameters": {
        "paramA": {
          "type": "String"
        },
        "paramB": {
          "type": "String"
        },
        "paramC": {
          "type": "String"
        },
        "paramD": {
          "type": "String"
        }
    },
    "policyDefinitions": [
      {
        "policyDefinitionReferenceId": "Policy Definition 1",
        "policyDefinitionName": "policydef1",
        "parameters": {
          "A": {
              "value": "[parameters('paramA')]"
          },
          "C": {
            "value": "[parameters('paramC')]"
          }
        }
      },
      {
        "policyDefinitionReferenceId": "Policy Definition 2",
        "policyDefinitionName": "policydef2",
        "parameters": {
          "B": {
            "value": "[parameters('paramB')]"
          },
          "D": {
            "value": "[parameters('paramD')]"
          }
        }
      }
    ]
  }
}
</pre>

**Comment by techlake** [comment]
This works for me in the latest version; however, I did just fix a problem with integers in parameters. Are those parameters in the real assignment (as opposed to the simplified copy above) integers? can you send me the actual snippets.

I need the following:
* parameters block from the initiative definition
* The assignment file with the assignment name and scope redacted

**Comment by Hulk-101** [comment]
I sent you the information by email at `heinrich.gantenbein@microsoft.com`.

**Comment by techlake** [comment]
I found the problem. It happens when no default value and the assignment parameter is an empty string.
