### ISSUE TITLE
Pipeline succeeds while job failed

### ISSUE THREAD

**Issue by donk-msft** [Azure/enterprise-azure-policy-as-code#264]
Job 'Deploy PAC-DEV Policy succeeds while job failed. My Policy assignment file contained two "assignment" sections. One at the root and one at the child scope. This resulted in assignment names that are too long.

![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/17045753/94607e98-e316-4e10-808b-d58db110d49d)

**Comment by GitHubUser1339** [comment]
After update to EPAC v7.0 the job fails as it should on this error.
