### ISSUE TITLE
Exemptions Breaking with latest code release

### ISSUE THREAD

**Issue by johnpetersjr** [Azure/enterprise-azure-policy-as-code#267]
Hello,

We previously had some JSON exemptions that worked fine, but now that we took the latest version of code [v7.2.12] they no longer work -- we were on version 7.15, now our ADO pipeline is throwing the following error:

```
Set-AzPolicyExemption: /home/vsts/work/1/s/Scripts/Deploy/Deploy-PolicyPlan.ps1:374
Line |
 374 |              $null = Set-AzPolicyExemption @filteredExemption
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | InvalidPolicyDefinitionReference : The policy exemption 'Exempting Redis
     | Policy until pipeline upgrade happens' create request is invalid. The
     | associated policy assignment is an assignment of a policy definition.
     | The policy definition reference is only valid for policy assignments of
     | policy set definitions. CorrelationId:
     | <snip>

##[error]PowerShell exited with code '1'.
```

And here is the existing exemption JSON that no longer works: (sanitized):
```
{
    "exemptions": [
        {
            "name": "Exempting Redis Policy",
            "displayName": "Exempting Redis Policy until pipeline upgrade happens",
            "description": "Exempting Redis Policy until pipeline upgrade happens ",
            "exemptionCategory": "Waiver",
            "expiresOn": "2023-06-25T21:00:00.000Z",
            "scope": "/providers/Microsoft.Management/managementGroups/my-mgmt-grp",
            "policyAssignmentId": "/providers/Microsoft.Management/managementGroups/azure-redco/providers/Microsoft.Authorization/policyAssignments/my-custom-policy-name",
            "metadata": {
                "stuff": "listed,here"
            }
        }
    ]
  }
```

Any thoughts?  I am confused by [exceptions documentation](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/Docs/policy-exemptions.md) because the CSV and JSON have different field names for policy assignment ID, assignmentId for CSV, and policyAssignmentId for JSON -- Maybe I'm the only one doing JSON exceptions still?

**Comment by brianmooremsft** [comment]
Investigating

**Comment by johnpetersjr** [comment]
FYI - we have backed out the upgrade of the latest EPAC Scripts, and we are still having the issue, so there's a good chance my issue is not relevant to the upgrade.  We are investigating as well (maybe our policy  assignment ID changed, or the backend API changed recently?)

**Comment by brianmooremsft** [comment]
Thx for update, was just about to pull your earlier version for repro.  still investigating...

**Comment by techlake** [comment]
We thought we had the issue. However, after building a test bed for your scenario, we cannot replicate the problem. Therefore, we need more information from your own investigation. If it yields nothing useful, we can do a debugging session. Please contact me at heinrich  ___dot___ gantenbein ___at-signy thing__ microsoft __dottie_ com to set up a debugging session over Teams.

**Comment by techlake** [comment]
Thank you for the debugging session. It appears that this is a bug in the underlying Az Module with Set-AzPolicyExemption. We will rewrite this with Invoke-AzRestmethod instead.
