### ISSUE TITLE
Exemptions not working correctly starting with v7.4.4

### ISSUE THREAD

**Issue by ptmetcalf** [Azure/enterprise-azure-policy-as-code#285]
I was able to get it partially working by adjusting line 253 in "Scripts/Deploy/Build-DeploymentPlans.ps1" from:
`if ($exemptionsAreManaged) {`

to

`if ($null -ne $pacEnvironment.policyExemptionsFolderr) {`

That fixed the issue I had in the summary which reported "Policy Exemptions not managed by EPAC.". However, it's reporting that all of my exemptions are "New" which shouldn't be the case. It looks like some changes to the "Build-ExemptionsPlan.ps1" file might to blame there but I haven't done any additional troubleshooting. Downgrading to v7.4.3 resolves the issue for me.

**Comment by techlake** [comment]
Thank you for reporting this. We'll try to get a fix in place this week.

**Comment by techlake** [comment]
Buh confirmed. It was a display error only,  the plan is still updating. We are in the middle of some other change (hopefully completed today). We will release 7.5 (likely tomorrow).

**Comment by techlake** [comment]
Fixed in 7.5
