### ISSUE TITLE
Request more details in documentation about exclusions

### ISSUE THREAD

**Issue by GitHubUser1339** [Azure/enterprise-azure-policy-as-code#286]
I'd like to request some additional details in the [documentation](https://azure.github.io/enterprise-azure-policy-as-code/policy-assignments/#assignment-scopes-and-excluded-scopes) about exclusions and notScopes.

I'd like to see an example how excluded scopes are cumulative and how not to define them at any child node (right vs wrong way).

In addition, the difference between globalNotScopes and excludedScopes in globalSettings.jsonc could use some clarification imho.

**Comment by techlake** [comment]
Added to the teams backlog
