### ISSUE TITLE
Unexpected Update of Policy Set

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#299]
I am deploying numerous policy sets and policies with EPAC. For some reason, even though I never change the policySetDefinitions, two of my policy sets **always** get updated on every run. See output below. Can someone point me in the right direction to understand what change is being discovered? I tracked it down to the Confirm-PolicyDefinitionsMatch helper script, but what I go through all of the equality checks for deployed vs. defined policy set defintions, I do not see any differences. 

In the output below, the first policy set is a built-in, and the second one is custom. So, it doesn't seem to be related to using a built-in vs. custom policy set. 

> ===================================================================================================
Processing Policy Set JSON files in folder 'Definitions/policySetDefinitions'
===================================================================================================
Number of Policy Set files = 14
Update (policies) 'Enforce Azure Compute Security Benchmark compliance auditing'
Update (policies) 'Audit VMs for CrowdStrike application'
Number of unchanged Policy SetPolicy Sets definition = 12
>

**Comment by techlake** [comment]
Can you share the policy set definition file? We heard of some issues with changes in capitalization when a definition is deployed but have not been able to pinpoint. If you're uncomfortable with sharing the definition publicly here:
Email me directly at first.last at-sign microsoft.com. You can get my first and last from my profile. I have tagged the issue as a bug for now.

**Comment by glsutter** [comment]
I'll email to you. I don't believe there's anything sensitive, but my company is a little paranoid about sharing our code publicly.

**Comment by techlake** [comment]
Would you mind doing a debugging session with me? I need to better understand how this fails.

I'm really eager to fix this.

**Comment by glsutter** [comment]
That would be great. Available for at least 30 minutes now. Or we can schedule something later today. Teams?

**Comment by techlake** [comment]
This is related on how Azure Graph return parameter names which are PascalCase in the original definition. They are returned as camelCase. A short-term fix is to change your definition. We are working on a code-based fix.

**Comment by techlake** [comment]
I fixed the issue for Policy Set definition's policyDefinitions parameter case sensitivity on PascalCase versus camelCase returned by resource graph queries. It will be v7.8.2 to be released tonight. I used the Policy Set definition provided and reproduced the error followed by fixing the "issue".

@glsutter please retest tomorrow with the latest update. Thank you.
