### ISSUE TITLE
Create a script to hydrate the environment

### ISSUE THREAD

**Issue by techlake** [Azure/enterprise-azure-policy-as-code#306]
### Ask questions

- CI/CD system (ADO, GH)
- logical name per (loop) tenant (pacSelector)
  - tenantId
  - cloud
  - root mg to use for definition
  - allow for multiple tenants
- epac-dev
  - tenantId
  - cloud
  - epac dev environment root
- Do you want starter definition
- or do you want to extract existing Policy object (via Export-AzPolicyResources)
- Which pipeline will you use

### When using PowerShell module

- Ideally, we could deliver the starter kit as a binary payload
- Or get it dynamically from GH

### Hydrate

- Pipeline (yaml only)
- Definitions
  - `global-settings.json`
  - `policyDefinitions`
  - `policySetDefinitions`
  - `policyAssignments`
  - `policyExemptions`
  - `policyDoocumentations`

**Comment by jeremiahhoward** [comment]
Down to integration debugging

**Comment by techlake** [comment]
Hi @jeremiahhoward Jeremiah, can you give an update.

**Comment by jeremiahhoward** [comment]
Prototype uploaded for review @techlake

**Comment by jeremiahhoward** [comment]
This is complete at long last!
