### ISSUE TITLE
Issue building plan using DevOps Pipelines.

### ISSUE THREAD

**Issue by BigWellies** [Azure/enterprise-azure-policy-as-code#308]
Hi, 

In order to thoroughly test EPAC before we start using it, I am attempting to run each step (build, deploy, rbac) individually and confirm it is behaving as intended. I am currently running into an issue where the script runs fine, but fails on line 20 of Build-AssignmentPlan.ps1 with the following error:

Get-AzRoleDefinition: /home/vsts/.local/share/powershell/Modules/EnterprisePolicyAsCode/7.8.3/internal/functions/Build-AssignmentPlan.ps1:20
Line |
  20 |      $roleDefinitionList = Get-AzRoleDefinition
     |                            ~~~~~~~~~~~~~~~~~~~~
     | Object reference not set to an instance of an object.

If I attempt build the plan locally (through VSCode as appose to DevOps), I run into no issues. Is there anything you're able to point out?

I did have a look through other issues and can't find anything related. If you'd rather I raise this with support as appose to an issue, I can do that.

Thanks.

**Comment by techlake** [comment]
This is a permission issue for the Service Principal.

**Comment by BigWellies** [comment]
I stood up a new dev tenant and re-configured the permissions on the tenant root group, and it has run fine now. Thanks for pointing me in the correct direction.
