### ISSUE TITLE
Integrate Bas's remediation tasks script into Create-AzRemediationTasks

### ISSUE THREAD

**Issue by techlake** [Azure/enterprise-azure-policy-as-code#309]
- Create-AzRemediationTasks is more sophisticated in creating the tasks
- Bas's script has interesting features dealing with task failures: https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/use-powershell-to-remediate-non-compliant-policy-definitions/ba-p/3878321

This task is to combine them to gain the best of both approaches.
Stretch: support GitHub Issues (in addition to ADO work items

**Comment by techlake** [comment]
I like the approach. Separate scripts for GH and ADO is the better approach.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by basvanbennekommsft** [comment]
Done!
