### ISSUE TITLE
Strategy to handle massive remediations

### ISSUE THREAD

**Issue by techlake** [Azure/enterprise-azure-policy-as-code#310]
@JulianHayward please add info here.

**Comment by JulianHayward** [comment]
100 remediation tasks can be ran simultaneously in the tenant. [ref](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/remediation-structure#resource-count-and-parallel-deployments)
It seems you can still trigger more than 100 remediation tasks (I guess those hitting the limit get queued) but waiting for the remediation task results may cause loooong wait/run time (depending..). @basvanbennekommsft @techlake

**Comment by jesseloudon** [comment]
could something be done with allowing a gradual rollout of a definition/initiative (that potentially has a very large non-compliant scopep to remediate) via the policy assignment's resource selectors?

![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/13147870/76989c90-7210-4e9b-8b19-1743e2f0c281)

https://learn.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#resource-selectors-preview

**Comment by anwather** [comment]
@jesseloudon that's a good idea - but requires people to add resource selectors into their assignments

**Comment by techlake** [comment]
This is a product group issue, nor an EPAC one. Therefore, we will not "fix" this.
