### ISSUE TITLE
Feature request: Integration between AzGovViz and Enterprise Policy as Code

### ISSUE THREAD

**Issue by Acenl12** [Azure/enterprise-azure-policy-as-code#312]
I would like to propose a integration between Azure Goverance Visualizer and Enterprise Policy as Code.
That the output from AzGovViz automatically gets assigned as policyassigments in EPAC
https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting

**Comment by techlake** [comment]
@JulianHayward : lets talk about this request. It sound interesting.

**Comment by anwather** [comment]
> I would like to propose a integration between Azure Goverance Visualizer and Enterprise Policy as Code. That the output from AzGovViz automatically gets assigned as policyassigments in EPAC https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting

Which output from your project would you want to turn into EPAC assignments? Is it just the assignments extracted in the ```json\assignments\policyAssignments``` folder?

**Comment by JulianHayward** [comment]
@techlake @anwather let´s discuss, however imho the AzGovViz concept is to report fact, not describe desired state 
@Acenl12 would you deploy policy in a dev tenant outside of epac and then use that azgvz data to feed epac with configuration for another tenant? Wildly guessing here :)

**Comment by Acenl12** [comment]
> > I would like to propose a integration between Azure Goverance Visualizer and Enterprise Policy as Code. That the output from AzGovViz automatically gets assigned as policyassigments in EPAC https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting
> 
> Which output from your project would you want to turn into EPAC assignments? Is it just the assignments extracted in the `json\assignments\policyAssignments` folder?

Yes and also the definitions

**Comment by anwather** [comment]
@Acenl12 You can already do that really easily using EPAC - try following this guide -> https://azure.github.io/enterprise-azure-policy-as-code/quick-start/ - or see https://azure.github.io/enterprise-azure-policy-as-code/extract-existing-policy-resources/ for more information.

**Comment by anwather** [comment]
Closing as resolution is suggested above - please re-open for further discussion
