### ISSUE TITLE
Private Endpoints Policy

### ISSUE THREAD

**Issue by Acenl12** [Azure/enterprise-azure-policy-as-code#328]
I'm testing with the private endpoints and the policy doesn't create any private endpoints, I created a storage account and waited 24 hours.. Please help.
```
                     "nodeName": "DNZZones",
                    "assignment": {
                        "name": "Deploy-Private-DNS-Zones",
                        "displayName": "Configure Azure PaaS services to use private DNS zones",
                        "description": "This policy initiative is a group of policies that ensures private endpoints to Azure PaaS services are integrated with Azure Private DNS zones."
                    },
                    "definitionEntry": {
                        "policySetName": "Deploy-Private-DNS-Zones",
                        "displayName": "Deploy Private DNS Zones"
                    },
```

**Comment by anwather** [comment]
That policy does not actually create a private endpoint - all it does is ensure that the private endpoint is using the correct private DNS zone. There is a built-in policy available (https://www.azadvertizer.net/azpolicyadvertizer/9f766f00-8d11-464e-80e1-4091d7874074.html) which actually creates the private endpoints - you could create an assignment for that. You will need to provide the subnet ID for private endpoint as a parameter.

**Comment by Acenl12** [comment]
> That policy does not actually create a private endpoint - all it does is ensure that the private endpoint is using the correct private DNS zone. There is a built-in policy available (https://www.azadvertizer.net/azpolicyadvertizer/9f766f00-8d11-464e-80e1-4091d7874074.html) which actually creates the private endpoints - you could create an assignment for that. You will need to provide the subnet ID for private endpoint as a parameter.

Thanks, is there also policyset which does it for all PaaS services?

**Comment by anwather** [comment]
There is not - you would have to create one.
