### ISSUE TITLE
Split-ScopeId Error

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#349]
Just ran a Sync-Repo, re-running a Gitlab pipeline, and getting a Split-ScopeId error about an empty string for $pacEnvironment.cloud. See error below. 

I've checked my global-settings.json and it looks okay. The mac-test1 pacEnvironment looks like:

		{
			"pacSelector": "mac-test1",
			"cloud": "AzureCloud",
			"tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
			"deploymentRootScope": "/providers/Microsoft.Management/managementGroups/TEST1",
			"desiredState": {
				"strategy": "full",
				"includeResourceGroups": false
			}

```
pwsh -c ./Scripts/Deploy/Build-DeploymentPlans.ps1 -pacEnvironmentSelector mac-test1
Set-AzCloudTenantSubscription: /builds/xcloud/azure/elz-epac/Scripts/Deploy/Build-DeploymentPlans.ps1:67
Line |
  67 |  Set-AzCloudTenantSubscription -cloud $pacEnvironment.cloud -tenantId  …
     |                                       ~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'cloud' because it is an
     | empty string.
===================================================================================================
Get scope tree for EPAC environment '' at root scope 
===================================================================================================
Write-Error: /builds/xcloud/azure/elz-epac/Scripts/Helpers/Get-AzScopeTree.ps1:15
Line |
  15 |      $scope = Split-ScopeId `
     |               ~~~~~~~~~~~~~~~
     | '' is not a valid scope.

Cleaning up project directory and file based variables
00:02
ERROR: Job failed: exit code 1
```

**Comment by glsutter** [comment]
I keep thinking this is something obvious, but I don't see the problem.

**Comment by glsutter** [comment]
Well, looks like this was caused by a Sync-Repo with the -supressDeleteFiles option. When I reran Sync-Repo w/o that option, working again. Closing this issue.

**Comment by glsutter** [comment]
Resolved by running Sync-Repo without -supressDeleteFiles.

**Comment by anwather** [comment]
Please use the PowerShell module to avoid these sync issues - it is more reliable and contains the same codebase.
