### ISSUE TITLE
Build-DeploymentPlans creates a plan with parameter value 'null'

### ISSUE THREAD

**Issue by tsunami28** [Azure/enterprise-azure-policy-as-code#354]
Script 'Export-AzPolicyResources' created output folder with all respective definitions and assignments.
Once running the 'Build-DeploymentPlans' I get a plan that has multiple 'null' values for parameters that are defined in assignments.
![Screenshot_332](https://github.com/Azure/enterprise-azure-policy-as-code/assets/46718446/784797e0-972c-4a48-a157-d2b828c9a3a3)
Also, not all parameters are injected to plan from assignment which can also be compared on attached screenshot.

**Comment by anwather** [comment]
Looks like an issue with array parameters, and the ones that are missing can you confirm if they are defaults values for the parameters?

**Comment by anwather** [comment]
Actually even for those parameters that have an array - are they default values as well?

**Comment by tsunami28** [comment]
Regarding the property type, it is not just for an array, but yes it has a default value:

![Screenshot_333](https://github.com/Azure/enterprise-azure-policy-as-code/assets/46718446/616e2f7d-522b-4673-a2cc-c1d15bd6dd67)

The "missing" parameters in plan do indeed have default values, so let's say that that is OK.

**Comment by tsunami28** [comment]
To make a nice trace for both cases.

1. KeyVault
- there is no policy definition since we are referencing built-in one
- within the policy set definition there is a default value of type array
- policy set assignment file has value that needs to be used
- the exported plan shows 'null'
2. SQL
- policy definition has a default value of type string
- policy set definition has a default value
- policy set assignment has value that needs to be used
- the exported plan shows 'null'

**Comment by anwather** [comment]
I'm having trouble replicating this issue - are you able to send me a sample set definition file and assignment file that I can use to reproduce this? Send to anwather@microsoft.com if possible?

**Comment by tsunami28** [comment]
Hi Anthony. I have shared the files from my company email account.

**Comment by anwather** [comment]
Thanks - was able to reproduce, it is caused by parameter values in the assignment and the policy set definition having different casing values. As we load these in as a hash table - having incorrect casing causes the key to be not matched. Azure Resource Graph is the main culprit as when you upload a policy set it applies a set of casing rules to the parameters. I'll publish a fix that should stop it. As above if you have assignment parameters specified in an assignment that match the default parameters they won't be included in the plan.

**Comment by tsunami28** [comment]
Great finding Anthony! I will work with my team too to match things like this in the future. As I am looking to switch from our automation process to EPAC, it will help a lot :) Thank you.
