### ISSUE TITLE
Get-AzScopeTree errors with old subscriptions

### ISSUE THREAD

**Issue by robsissons-contino** [Azure/enterprise-azure-policy-as-code#357]
Environment:

EPAC Version = 8.2.1
Powershell Version = 7.3.6

Root scope for deployment = Tenant Root Management Group

Issue: 

A number of subscriptions are in a disabled/unknown state in the current environment. 
When running a "Build-DeploymentPlan" we receive the following error:

`**Code bug: Our root is not in this tree**`

When triaging this error we notice this is due to the aforementioned subscriptions being returned by the "Search-AzGraphAllItems" function when returning all child resourceContainers however these subscriptions are not fully active/linked to the current tenant.

Workaround:

If we modify the "Get-AzScopeTree" function to silently continue instead of throwing the above error the plan builds and we are able to deploy.

Expected Behaviour:

Ideally we would like to be made aware of any such subscriptions or resourceContainers but if there is no subsequent issue with build/deploy due to these then we should be able to continue. 

_Note - The subscriptions in question are (mostly) legacy Visual Studio subscriptions which Microsoft Support have been unable to fully remove._

**Comment by anwather** [comment]
Not ideal - but I'd probably like to put a switch in ```Build-DeploymentPlans``` - maybe to ignore scope errors? It can then filter down to ```Get-AzScopeTree``` and force it do an ```-ErrorAction SilentlyContinue```. It's not an ideal fix but it is an edge case.... The comment in the code indicates it shouldn't happen
```
else {
                # should not be possible
                Write-Error "Code bug: Our root is not in this tree" -ErrorAction Stop
            }
```

**Comment by robsissons-contino** [comment]
switch sounds like the most suitable approach to me, appreciate this is probably an edge case but we did hit 63 such subscriptions so assume we aren't the first to notice this?

Could be related to the fact that we are targeting the tenant root group for our root scope rather than a child management group. Unfortunately we are unable to change this currently so the ability to switch to silentlyContinue would be ideal.

**Comment by anwather** [comment]
Is there anyway I can replicate this? E. G. Disable a subscription? I haven't seen anyone with this issue yet

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robsissons-contino** [comment]
Unfortunately I don't have the history on what actions were taken against these subscriptions and the output of the erroneous subscriptions we took show different status for each. Some are disabled, some are still enabled. 

The common factor is that these subscriptions are not visible using any other method than the Graph API query which is used to gather resource containers within the EPAC module. They are also showing no information under the "managedByTenants" property in the JSON output I generated from the modified EPAC code.

See below redacted output for two of the subscriptions which were throwing the error for us:

```
{
    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "name": "Visual Studio Enterprise Subscription",
    "type": "microsoft.resources/subscriptions",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "kind": "",
    "location": "",
    "resourceGroup": "",
    "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "managedBy": "",
    "sku": null,
    "plan": null,
    "properties": {
      "managementGroupAncestorsChain": [],
      "subscriptionPolicies": {
        "locationPlacementId": "Public_2014-09-01",
        "spendingLimit": "On",
        "quotaId": "MSDN_2014-09-01"
      },
      "managedByTenants": [],
      "state": "Enabled"
    },
    "tags": null,
    "identity": null,
    "zones": null,
    "extendedLocation": null,
    "ResourceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  },
{
    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "name": "Azure subscription 1",
    "type": "microsoft.resources/subscriptions",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "kind": "",
    "location": "",
    "resourceGroup": "",
    "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "managedBy": "",
    "sku": null,
    "plan": null,
    "properties": {
      "managementGroupAncestorsChain": [],
      "subscriptionPolicies": {
        "locationPlacementId": "Public_2014-09-01",
        "spendingLimit": "On",
        "quotaId": "FreeTrial_2014-09-01"
      },
      "managedByTenants": [],
      "state": "Disabled",
      "promotions": [
        {
          "endDateTime": "2024-08-13T05:01:51.362Z",
          "category": "freetier"
        }
      ]
    },
    "tags": null,
    "identity": null,
    "zones": null,
    "extendedLocation": null,
    "ResourceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  }
```

**Comment by anwather** [comment]
The ARG query is very simple that is used, I'll have a look at optimising it and only pulling from the signed in tenant. That may help filter out some things.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robsissons-contino** [comment]
These subscriptions were previously linked to the signed in tenant so may still return with such a filter. Given that we have not had any issues bypassing the current ErrorAction then an option to SilentlyContinue instead/as well would be preferred?

**Comment by anwather** [comment]
I can fix this next week or possibly tomorrow - can you let me know exactly where you made the change and I'll create a switch on Build-DeploymentPlans and filter it down?

**Comment by robsissons-contino** [comment]
Our workaround was to update line 130 in "Get-AzScopeTree" to SilentlyContinue on error. 

Snippet:

```
else {
                # should not be possible
                Write-Error "Code bug: Our root is not in this tree" -ErrorAction **SilentlyContinue**
            }
```

**Comment by anwather** [comment]
Thanks will push the fix tomorrow

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
-IgnoreScopeTreeErrors switch added to Build-DeploymentPlans
