### ISSUE TITLE
quick-start.md update New-EPACDefinitionsFolder function name in instructions

### ISSUE THREAD

**Issue by jgslalom** [Azure/enterprise-azure-policy-as-code#360]
Great stuff here, excited to try out. Small update to quick-start instructions I saw when tried calling the function New-EPACDefinitionFolder - just lose the "s" to match the function name that comes with the actual imported modules. 

current: New-EPACDefinitionsFolder -DefinitionsRootFolder Definitions
update: New-EPACDefinitionFolder -DefinitionsRootFolder Definitions

**Comment by anwather** [comment]
Thanks @jgslalom
