### ISSUE TITLE
Desired State(unknownOwner,ownedOnly) - no delete

### ISSUE THREAD

**Issue by robsissons-contino** [Azure/enterprise-azure-policy-as-code#363]
Apologies if I have missed documentation regarding this but when we run a plan we see a number of the following entries under the assignments section of the plan output:

```
Cleanup removed Policy Assignments (delete)
  Desired State(unknownOwner,ownedOnly) - no delete 'xxxxxxxxxxxxxxxxxxxxxxxx' at /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  Desired State(unknownOwner,ownedOnly) - no delete 'xxxxxxxxxxxxxxxxxxxxxxxx' at /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  Desired State(unknownOwner,ownedOnly) - no delete 'SecurityCenterBuiltIn' at /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  Desired State(unknownOwner,ownedOnly) - no delete 'SecurityCenterBuiltIn' at /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx


```

It isn't entirely clear what these are referring to other than the owner being unknown (assume referring to the pacSelector being unknown?). All resources being listed are existing (pre-EPAC) and being listed under a heading which states "(delete)" is causing confusion for reviewers of the Plan

**Comment by jeremiahhoward** [comment]
I checked through the code and found this:
.\epac-development\Scripts\Helpers\Build-AssignmentPlan.ps1
Line 314 is what you're looking for: Write-AssignmentDetails -DisplayName $name -Scope $Scope -Prefix "Desired State($pacOwner,$strategy) - no delete" -IdentityStatus $IdentityStatus
This indicates that the script acknowledges your desire not to delete existing policies that are not owned by EPAC.

That cmdlet is running line 12's as if=True. This indicates no need of a role change.

Does that answer the question?

**Comment by robsissons-contino** [comment]
Thanks Jeremiah,

I can see the section of code which is generating this output but just wonder what benefit this brings to anyone reviewing the plan file from a CI/CD approval perspective? The other sections of the report (policyDefinitions/policySetDefinitions) don't output a line for every resource that won't be affected by the deployment, this only happens under the assignment section.

Personally I think the section of the Plan which gives an overview of the objects managed by the current pacEnvironment is sufficient to advise of the scope and intention of the plan. If anything perhaps a count of the number of assignments that are not being affected would be less intrusive on the report?

Thanks

**Comment by jeremiahhoward** [comment]
Hey there! We talked it over and will get that update in. We can see how it can be confusing, and don't want that. Thank you!

**Comment by robsissons-contino** [comment]
Many thanks Jeremiah (and team!) Any idea when the release with this will be available?

**Comment by jeremiahhoward** [comment]
Should be in today.
