### ISSUE TITLE
Query on usage

### ISSUE THREAD

**Issue by chanakanissanka** [Azure/enterprise-azure-policy-as-code#365]
Hi There, 
This is great, and successfully deployed the starter KIT and the pipeline working fine. 
I want to set-up some policies to apply to our dev/test sub to stop any running VMs at night. May I ask for some guidance or entry point using this repo

**Comment by anwather** [comment]
You could the policy [here](https://github.com/Azure/Community-Policy/blob/main/policyDefinitions/Compute/deploy-vm-auto-shutdown/azurepolicy.json) to set up auto shutdown (I haven't tested). You can use EPAC to deploy the policy definition by adding it to the ```policyDefinitions``` folder - and then create an assignment in the ```policyAssignments``` folder. Use the files in the starter kit and the [documentation](https://aka.ms/epac) to help you write the assignment. Make sure you set the scope in the assignment to point to the dev/test subscription.
