### ISSUE TITLE
Issue when trying to remove expiration date on exemptions

### ISSUE THREAD

**Issue by quynhtranghbt** [Azure/enterprise-azure-policy-as-code#368]
When I tried to remove expiration dates on the exemption, I encountered an error that says:

 **_Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'Add'._**

That is line 330 in the Build-ExemptionsPlan.ps1 file in the Helper folder. We found the fix for it by changing the type of the exemption object in line 253 from **_[PSCustomObject]_** to an **_array_** (removing [PSCustomObject])

Do you think this will cause issue if I push the change to EPaC master branch?

**Comment by anwather** [comment]
No that won't work - do you have an existing exemption deployed (with an expiry) and you are trying to remove the expiry date? Just need some steps so I can reproduce.

**Comment by quynhtranghbt** [comment]
> No that won't work - do you have an existing exemption deployed (with an expiry) and you are trying to remove the expiry date? Just need some steps so I can reproduce.

Yes, that's what I did (removing expiration date from an existing exemption). I am trying to make the exemption permanent by removing its expiration date.
