### ISSUE TITLE
Using csv as a parameter file fails on array

### ISSUE THREAD

**Issue by tsunami28** [Azure/enterprise-azure-policy-as-code#371]
Case1 - Creating a plan with parameters within the assignment file - part of the plan (deployment works as expected):
"storage_allowed_sku_listOfAllowedSKUs": [
            "Standard_LRS",
            "Premium_LRS",
            "Standard_ZRS",
            "Premium_ZRS"
          ]

Case2 - Creating a plan with parameter file:
- line in param file:
"platform-storage-allowed-sku","","Custom","Storage","Platform - Storage - Allowed - SKU","Restrict the set of storage account SKUs that your organization can deploy.","","policySet-platform-storage-v1.0.0: Audit (default: storage_allowed_sku_policyEffect)","parameter: Audit,Disabled,Deny","Audit","{""storage_allowed_sku_listOfAllowedSKUs"":_""['Standard_LRS','Premium_LRS','Standard_ZRS','Premium_ZRS']""_}"
- generated plan:
"storage_allowed_sku_listOfAllowedSKUs": "['Standard_LRS','Premium_LRS','Standard_ZRS','Premium_ZRS']" - **Here is the issue - quotes around array are not accepted during the deployment. With them it is considered string.**

Expanded case2: If I remove quotes manually from the plan file, there is still an issue because the single quotes around values is not valid. Double quotes are expected.

Case3 - Removed the quotes in csv:
"platform-storage-allowed-sku","","Custom","Storage","Platform - Storage - Allowed - SKU","Restrict the set of storage account SKUs that your organization can deploy.","","policySet-platform-storage-v1.0.0: Audit (default: storage_allowed_sku_policyEffect)","parameter: Audit,Disabled,Deny","Audit","{""storage_allowed_sku_listOfAllowedSKUs"":_"['Standard_LRS','Premium_LRS','Standard_ZRS','Premium_ZRS']"_}"
Build returns an error:
Conversion from JSON failed with error: Unexpected end when deserializing object. Path 'storage_allowed_sku_listOfAllowedSKUs[0]'

Case4 - adding double quotes around values in csv:
"platform-storage-allowed-sku","","Custom","Storage","Platform - Storage - Allowed - SKU","Restrict the set of storage account SKUs that your organization can deploy.","","policySet-platform-storage-v1.0.0: Audit (default: storage_allowed_sku_policyEffect)","parameter: Audit,Disabled,Deny","Audit","{""storage_allowed_sku_listOfAllowedSKUs"":""["Standard_LRS","Premium_LRS","Standard_ZRS","Premium_ZRS"]""}"
returns an error - Conversion from JSON failed with error: Unexpected end when deserializing object. Path 'storage_allowed_sku_listOfAllowedSKUs'

**Comment by tsunami28** [comment]
I found a syntax that works (based on the StarterKit example):

"{""storage_allowed_sku_listOfAllowedSKUs"":[""Standard_LRS"",""Premium_LRS"",""Standard_ZRS"",""Premium_ZRS""]}"

It might be good to have this documented somewhere as an example, because Policy documentation outputs this:
"{""storage_allowed_sku_listOfAllowedSKUs"":""++ no default ++""}" which I misinterpret :/

**Comment by anwather** [comment]
We do kind of call this out in the documentation - where it talks about extracting an existing assignment into documentation. https://azure.github.io/enterprise-azure-policy-as-code/policy-assignments/#defining-parameters-overrides-and-noncompliancemessages-with-a-csv-file - when you do this you will see the format for array parameters is as you describe above.
