### ISSUE TITLE
Update exemption handling to ignore expired and/or orphaned exemptions correctly

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#377]
1. Add functionality to allow for PacOwned expired exemptions to not be deleted.  Default will be to delete these.
2. Add functionality to allow for PacOwned orphaned exemptions to not be deleted.  Default will be to delete these.
3. Update current logic that treats unowned exemptions as being owned by the currently executing PacEnv.  If an exemptions ownership is unknown it should be treated like otherPaC when determining if it should be deleted, meaning it should not be deleted.

**Comment by anwather** [comment]
What's the ETA on this enhancement?

**Comment by gregslack78** [comment]
Hoping to have time to retest on Wednesday.  I can start working on getting it in a branch for review before that though.
________________________________

**Comment by gregslack78** [comment]
Implemented in issue #385
