### ISSUE TITLE
error when running export non-compliance reports 

### ISSUE THREAD

**Issue by brianmooremsft** [Azure/enterprise-azure-policy-as-code#379]
running operations script Export-NonComplianceReports.ps1 generates error

Line |
 231 |          if ($allPolicyAssignments.ContainsKey($policyAssignmentId)) {
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
     
Reproduceable; issue began with version 8.1.

**Comment by brianmooremsft** [comment]
@anwather - may need your assistance resolving this with @techlake  out of pocket.

**Comment by anwather** [comment]
Fixed wit #380
