### ISSUE TITLE
Orphan Exemption deletion error when resource locks are used

### ISSUE THREAD

**Issue by logm2k1** [Azure/enterprise-azure-policy-as-code#389]
Currently the execution of pipeline fails if there is a resource lock which prevents deletion of orphan exemption. Could there be a switch or parameter which would define ErrorActionPreference or some kind of mechanism to bypass resources that are protected by lock.

Remove-AzPolicyExemption: D:\a\1\s\EPAC\Scripts\Deploy\Deploy-PolicyPlan.ps1:103
Line |
 103 |  …     $null = Remove-AzPolicyExemption -Id $id -Force -ErrorAction Cont …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ScopeLocked : The scope
     | 'XXXXXXXXX' cannot perform delete operation because following scope(s) are locked: 'XXXXX'. Please remove the lock and try again. CorrelationId: XXXXX

**Comment by anwather** [comment]
We could put some output when the plan is deployed - checking to see if an object has a lock on it may be too expensive.
e.g.
`Failed to remove exemption as scope is locked`

**Comment by anwather** [comment]
Added a switch to `Deploy-PolicyPlan` called `IgnoreScopeLockedErrors` - use this to generate a warning and not an error.
