### ISSUE TITLE
Anomalous escaping in JSON strings

### ISSUE THREAD

**Issue by EPinci** [Azure/enterprise-azure-policy-as-code#398]
Hello,

I'm trying to configure a policy with a parameter containng a regex.

- When specifying a literal `/`, I need to escape it in the string with a `\/`.
- When specifying a literal `.`:
  - if I use `\.` vscode signals me an error and the execution of the pipeline errors out with "Conversion from JSON failed with error: Bad JSON escape sequence"
  - if I use `\\.` pipeline runs fine but, when looking at the applied result, is see `\\.` instead of `\.` resulting in a botched evaluation of the regex

Example:
`"^(something\\.azurecr\\.io|docker\\.io\/istio)\/.+$"` results in 
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/6307145/e0a57080-55f8-4328-8bb1-5b177a51cf38)
Note the double backslash.

What am I missing?

Thank you.

**Comment by anwather** [comment]
I don't think your missing anything - it's a very weird edge case - I can replicate it so let me have a look. Basically when I exported the policy assignment out (I had to create it manually) it looked like the below:
```
"parameters": {
    "allowedContainerImagesRegex": "^[^\\/]+\\.azurecr\\.io\\/.+$"
  }
```
i.e. it had escaped the strings correctly. When I used EPAC to then assign it I had the issue as you had above.

**Comment by anwather** [comment]
Ok - so this is my view in the portal: - 
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/11281622/a6b9cd6a-9be5-44f1-b9c2-5ec4eb11ddac)

When I click on Edit Assignment and look at the parameters it looks like below: -
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/11281622/4e7637f9-b464-470b-b033-087cdd0285dd)

It's escaped correctly. Have you tested to see if the policy works? It could just be a visual anomaly in the portal?

**Comment by EPinci** [comment]
Yes, it looks like, indeed, is a portal bug.
I was taken aback by the policy delayed evaluation but they get applied OK.

Thanks for checking this out!
