### ISSUE TITLE
Exemptions not removed from Azure when removed from CSV

### ISSUE THREAD

**Issue by robsissons-contino** [Azure/enterprise-azure-policy-as-code#401]
When removing a line item from our exemptions CSV file this is not always picked up in a plan and therefore not removed.

The exemptions in question are deployed through EPAC successfully but then removing from the config CSV does not trigger a removal.

**Comment by anwather** [comment]
So they aren't appearing in the outputted plan at all?

**Comment by anwather** [comment]
So the exemptions removed from the CSV are not in the outputted plan file?

**Comment by robsissons-contino** [comment]
This is correct. 

tested on EPAC v 8.4.2, pwsh 7.3.8

Confirmed that the exemption is created and has the correct metadata tag. When I remove the row from the CSV I see this in my plan summary (note this is a testing pacselector so my test exemption was the only entry):

`Policy Exemption counts:
    0 unchanged
    0 orphaned
    0 expired
    0 changes`

Interestingly, if I re-run the plan it wants to try and recreate the exemption, as though it cannot find the exemption to confirm that it already exists:

`Policy Exemption counts:
    0 unchanged
    0 orphaned
    0 expired
    1 changes:
        new     = 1
        update  = 0
        replace = 0
        delete  = 0`

For information, this environment has the following configuration in our globalsettings:

`{
            "pacSelector": "xxxx",
            "cloud": "AzureCloud",
            "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "deploymentRootScope": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx",
            "desiredState": {
                "strategy": "ownedOnly",
                "includeResourceGroups": true
            }
        }`

Have now just tested re-running the deployment and it consitently wants to recreate this exemption:

`===================================================================================================
Create new Exemptions (1)
---------------------------------------------------------------------------------------------------
test_exemption1(/subscriptions/***/resourceGroups/xxxxxxxxxxxxxxxx/providers/Microsoft.Web/sites/testwebapp/providers/Microsoft.Authorization/policyExemptions/test_exemption1)`


Note - in our production environment we have over 22k exemptions and the plan does not try to recreate the exemptions. The global settings are also set to ownedOnly. The main difference with our production environment is that the root scope is a management group, rather than a subscription.

I will create a test exemption in our production environment and report back my findings.

**Comment by gregslack78** [comment]
The fact that you state that if you re-run the plan (presumably after adding the exemption back to the csv) it processes it as a new exemption makes me think that there is some difference between what is in the csv file and what is in Azure.  Can you run an export of that pac and compare the exported csv to the csv you are running the plan for.

**Comment by robsissons-contino** [comment]
Unfortunately the plan wants to create the exemption each time without modifying the CSV file at all. 

I have performed a similar test in our production environment however this has worked as expected - a second build does not want to "recreate" the exemption, and removing from the CSV results in the exemption being removed.

As requested I performed an export and can confirm that the exemptions added through these tests were not included in the exported "all-exemptions.csv" file.

I can only assume this is a permission issue with the SPN we are using in this environment. Can anyone advise what permissions we are missing for the ability to read these exemptions so I can raise with the IAM team to review?

Many thanks again for the EPAC team's support!

**Comment by gregslack78** [comment]
Required roles are defined here.  https://azure.github.io/enterprise-azure-policy-as-code/ci-cd-pipeline/#service-connections-for-devops-cicd

**Comment by robsissons-contino** [comment]
can anyone replicate this?

**Comment by gregslack78** [comment]
I'm going to try a few things out this morning to see if I can replicate.

Have you tried doing this with json exemptions instead of csv?  Curious if you get the same results
________________________________

**Comment by gregslack78** [comment]
I was unable to recreate this issue.

Setup a pacEnv similar to yours...

        {
            "pacSelector": "epac-test",
            "cloud": "AzureCloud",
            "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "deploymentRootScope": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // replaces rootScope
            "desiredState": { // [optional]
                "strategy": "ownedOnly", // default full
            }
         }

Deployed 3 exemptions

name,displayName,description,exemptionCategory,expiresOn,scope,policyAssignmentId,policyDefinitionReferenceIds,resourceSelectors,metadata,assignmentScopeValidation
asdfasdfsda,new,,Waiver,12/3/2023 4:00,/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/test/providers/microsoft.network/routetables/testrt,/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/microsoft.authorization/policyassignments/taginh-appnamenew,,,,
testrtExemptasdfasa,new2,,Waiver,12/3/2023 4:00,/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/test,/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/microsoft.authorization/policyassignments/taginh-appnamenew,,,,
asdfasdfsadfsdf,new3,,Waiver,12/3/2023 4:00,/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/microsoft.authorization/policyassignments/taginh-appnamenew,,,,

Redeployed and all were identified and so no redeploy was attempted.
Exported and everything exported.

Any details I'm missing that could help me in recreating this?
________________________________

**Comment by robsissons-contino** [comment]
What happens when you remove the row from the CSV in that PAC environment? Are the exemptions removed?

Have not tested with JSON exemptions but assume the same behaviour

_Please can we also remove the additional thread information which exposes email addresses in the body of the comments?_

**Comment by robsissons-contino** [comment]
Any update on this? I notice that the thread is marked as awaiting response?

**Comment by gregslack78** [comment]
Unable to reproduce.
