### ISSUE TITLE
Policy Exemption resourceSelectors cannot be passed correctly

### ISSUE THREAD

**Issue by DanZab** [Azure/enterprise-azure-policy-as-code#402]
In JSON format, the resourceSelector property of a policy exemption is expected to be an **array** object:

``` json
"resourceSelectors": [
    {
      "name": "CognitiveServices",
      "selectors": [
        {
          "in": [
            "Microsoft.CognitiveServices/accounts"
          ],
          "kind": "resourceType"
        }
      ]
    }
  ],
```

The CSV input required for exemptions expects that column/value to be passed in json format as well. However, if I try to create an exemption with a resource selector, it will not let me pass it as an array as the `Build-ExemptionsPlan` helper script will not accept the value unless it starts with a curly bracket or you get the following error:

```
Line |
 183 |  Build-ExemptionsPlan `
     |  ~~~~~~~~~~~~~~~~~~~~~~
     | 'all-exemptions.csv' has 1 errors: - Entry number 1:
     | - invalid resourceSelectors format, must be empty or legal JSON:
     | '[{"name":"CognitiveServices","selectors":[{"in":["Microsoft.CognitiveServices/accounts"],"kind":"resourceType"}]}]'
```

From [Build-ExemptionsPlan](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/Scripts/Helpers/Build-ExemptionsPlan.ps1) lines 172-186, see line 177 `if ($step2.StartsWith("{") -and (Test-Json $step2))`:

``` powershell
 # Convert resourceSelectors into array (if cell empty, set to Snull)
                        $resourceSelectors = $null
                        $step1 = $row.resourceSelectors
                        if (-not [string]::IsNullOrWhiteSpace($step1)) {
                            $step2 = $step1.Trim()
                            if ($step2.StartsWith("{") -and (Test-Json $step2)) {
                                $step3 = ConvertFrom-Json $step2 -AsHashTable -Depth 100 -NoEnumerate
                                if ($step3 -ne @{}) {
                                    $resourceSelectors = $step3
                                }
                            }
                            else {
                                Add-ErrorMessage -ErrorInfo $errorInfo -ErrorString "invalid resourceSelectors format, must be empty or legal JSON: '$step2'" -EntryNumber $entryNumber
                            }
                        }
```

If I wrap that section in curly brackets so it's accepted by the Build-ExemptionPlan script, then the API PUT call for the exemption fails with a 400 because the object is not an array:

```
Line |
 367 |              Set-AzPolicyExemptionRestMethod -ExemptionObj $exemption
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Policy Exemption error 400 -- {"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could
     | not be deserialized: 'Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type
     | 'Microsoft.WindowsAzure.Governance.PolicyService.Models.Policy.ResourceSelector[]' because the type requires a JSON array
     | (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or
     | change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type
     | like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to
     | force it to deserialize from a JSON object.\r\nPath 'properties.resourceSelectors.name', line 1, position 319.'."}}
```

## Workaround
I couldn't get this to work with any modification of the value in the CSV, however, I can workaround the issue using the following process:

1. I wrap the json array for the resourceSelectors in curly brackets
2. Run my Build-DeploymentPlans step to generate the plan file
3. Modify the plan file and remove the curly brackets from the **resourceSelectors** property to turn it back into an array
4. Run Deploy-PolicyPlan step

**Comment by DanZab** [comment]
As a side comment, it would be way more user-friendly to manage policy exemptions as individual JSON files instead of requiring a CSV.

**Comment by DanZab** [comment]
@gregslack78 I wish there was a facepalm reaction, yeah. That is what I will be doing going forward.

My personal issue is then solved, not sure if it's worth keeping this open given the original issue would still be a problem.

**Comment by gregslack78** [comment]
Glad that solves your issue.  I think this is still a bug so we'll take a look at it.  Thanks!
