### ISSUE TITLE
rename the child node

### ISSUE THREAD

**Issue by Arian75** [Azure/enterprise-azure-policy-as-code#404]
https://github.com/Azure/enterprise-azure-policy-as-code/blob/c17bbdcddbd5928c8c02188344fe5b228478e63b/Scripts/CloudAdoptionFramework/policyAssignments/ALZ-CorpMG-Default.jsonc#L31C34-L31C42

DNZZones should be DNSZones

**Comment by jeremiahhoward** [comment]
Great catch! I'll get this sorted and pushed. Thank you!
