### ISSUE TITLE
Adding validation pipeline/workflow to test policy resources

### ISSUE THREAD

**Issue by Dylan-Prins** [Azure/enterprise-azure-policy-as-code#408]
When merging the pull request there should be some tests that the data changed is valid.
I Would love to contribute, but do not know if I can design something myself :)

**Comment by techlake** [comment]
The best approach is to have a Policy testing area mimicking your production MG layout as outlined in the documentation. This pipeline would be done whenever you push a change to the feature branch. We will not add validation code, we rely on Azure to validate Policies. If this is still confusing after reading our documentation, reopen this issue and we will investigate how to document this better.
