### ISSUE TITLE
Non compliance report processing takes extremely long time

### ISSUE THREAD

**Issue by ddas-2020** [Azure/enterprise-azure-policy-as-code#409]
1) Non compliance report script takes almost 20 mins to process 5k records. In any large corporation where a large number of records are in non-compliance state, the amount of time it takes to process, makes it less useful. How can we increase the speed of processing records? (keep in mind, in many corporations a VM may be functional for 8 hrs, this script takes 15 hrs to complete 220k records)
2) While it process the records, there is no way we come to know if the system is alive or not. A progressive dial or some indicators that system is alive and processing would be great!

Thanx.

**Comment by anwather** [comment]
It looks like it makes a heap of calls back to ARM to get policy details - can you test setting the `deploymentRootScope` in your `global-settings.jsonc` file to the tenant level i.e. `/provider/Microsoft.Management/managementGroups/<<tenantId>>` ?

I haven't looked at this script in detail but when I run at a lower scope I get the same number of non-compliant items as at the higher scope - but no performance hit...

**Comment by ddas-2020** [comment]
I will let it run over night. Currently, root scope is at MG level. I can change it at tenant level and test.

**Comment by anwather** [comment]
Yeah because we pull in all policy objects at the `deploymentRootScope` only - every time it find something that exists outside of that scope it is calling back to ARM - I think this is causing the issues
