### ISSUE TITLE
Sync ALZ Policy Object missing single policy assingments?

### ISSUE THREAD

**Issue by ThomasStubergh** [Azure/enterprise-azure-policy-as-code#410]
Hi. We are trying to integrate EPAC with Azure Landing Zones, and pull all policies, policy sets, and assignments from there. This in itself seems to be working, but I am wondering if there are missing some the single policy assignments in ALZ. There are 3 databricks policies, which are not part of a policy set, but just single policies which also have an assignment, but they don't seem to be assigned in any of the assignments in EPAC. Not sure if this is a bug, or if I am missing something, and for now will keep these single policy assignments. Maybe there is a pending change where they shouldn't be assigned by default, or maybe they have been excluded in ALZ, even though they are listed. Is there any documentation on exactly what is synced, and is there a changelog which could explain if these policies no longer are part of the deployment as assignments?

Thanks in advance, and sorry if I have missed something somewhere. :)

**Comment by anwather** [comment]
They removed those assignments from the ALZ policy list so I removed them from the ALZ assignments in EPAC - I keep in sync with what they list at https://aka.ms/alz/policies. They did that a few months ago - not sure what the reasoning was...

**Comment by ThomasStubergh** [comment]
OK. Good to know. Thanks for the speedy response! Great work!
