### ISSUE TITLE
desiredState:excludedScopes

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#412]
In Desired State Strategy markdown, under [Child Scopes not Managed by any EPAC repo but Subject to these Policies], there's this sentence:

Any of the strings can contain simple wild cards.

Does that mean this is a valid excludedScopes array?

```
"excludedScopes": [ 
        "/subscriptions/*"
 ]
```

And can I assume that means that policies defined and assigned by any subscription owner will be ignored by EPAC? But, also that any policies assigned to the MG tree in which the subscription resides will still apply to the subscription?

Just want to confirm my understanding since that specific example is not included. 

Thanks

**Comment by anwather** [comment]
Yes this works the way you have described - `excludedScopes` tells EPAC to not try and manage anything at that subscription scope ( and the * works as a wildcard) - however policies you apply at the management group will not have these subbscriptions added as a `notScope`
