### ISSUE TITLE
Exemptions created outside of EPAC are deleted when a policy assignment is managed by EPAC (ownedOnly mode)

### ISSUE THREAD

**Issue by roddick-mark** [Azure/enterprise-azure-policy-as-code#413]
When running in "ownedOnly" mode, if an exemption is created outside of EPAC and the policy assignment is created by EPAC, the exemption will be deleted. 

When running in ownedOnly mode I would expect only those policy exemptions which are tagged as owned by EPAC are managed by EPAC.

**Comment by anwather** [comment]
Are you managing any exemptions using EPAC? If you are then this behavior is expected as EPAC would not know about the exemption and would remove it. The fix would be to export the exemptions and manage them using EPAC.

**Comment by roddick-mark** [comment]
yes we are. But surely in ownedOnly mode we should only be dealing with exemptions which have the metadata tag of the current "pacOwnerId"?

**Comment by anwather** [comment]
I have a feeling something is missing in the code (or it hasn't been implemented) - give me some time to check - I do agree though it probably shouldn't be removing those exemptions it doesn't own.
