### ISSUE TITLE
Unable to set displayname to a policy in an initiative

### ISSUE THREAD

**Issue by EPinci** [Azure/enterprise-azure-policy-as-code#414]
Hello,

when I create a policy assignment I can provide a displayName - this allows me to reuse multiple times a builtin policy with different parameters that have different "meanings" for us.

If I group those assignments in an initiative I lose the option of specifying a displayname resulting in a list of "different policies included that have the same name".
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/6307145/6627b41c-c0d9-4d2a-ad43-287bd079784c)
 
Is there a way to provide a displayName to a policy definition in an assignment?

Thank you.

**Comment by anwather** [comment]
No there isn't  - this is a limitation of the initiative - you would have to create those policies again as custom and assign them .
