### ISSUE TITLE
Policy Exemptions query not showing assignmentScopeValidation values

### ISSUE THREAD

**Issue by robsissons-contino** [Azure/enterprise-azure-policy-as-code#415]
exemptions in the CSV with assignmentScopeValidation set to DoNotValidate keep showing in a plan/deploy to re-apply the parameter.

Get-AzPolicyResources.ps1 uses the Search-AzGraphAllItems with the below query to pull back exemptions. 

`'PolicyResources | where type == "microsoft.authorization/policyexemptions"'`

When using this same KQL query to view the value for assignmentScopeValidation I am presented with only null values. Viewing the same data through REST API (GET query below) shows that the value is already set to DoNotValidate 

GET
https://management.azure.com/{scope}/providers/Microsoft.Authorization/policyExemptions/{exemption_name}?api-version=2022-07-01-preview

Looks like Graph does not provide this value through the PolicyResources table?

Powershell version 7.3.8
EPAC version 8.4.3

**Comment by anwather** [comment]
ICM has been raised 441237419
