### ISSUE TITLE
Defender for Cloud Auto-Assigned Policies

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#416]
This is probably more suited for Discussions, but those don't seem to be active. 

In our account, we are enabling selected Defender for Cloud plans for selected subscriptions on a case-by-case basis. When the plan is enabled, some policies are automatically assigned to the subscription. Since we have our desiredState:strategy set to "Full", EPAC wants to delete these Defender auto-assigned policies. 

Here are some options that we've considered for dealing with these Defender policies:

- Change the desiredState:strategy to "ownedOnly". That doesn't seem desirable because we do want to manage policies with a single team. 

- Manage Defender for Cloud plans with the MDFC initiative, using a CSV to selectively enable plans, and then assign to selected subscriptions using EPAC. That also doesn't seem like a good approach, because each subscription will want a different set of plans enabled, and we have over 100 subscriptions. 

- Manage Defender plans in the console, and exclude all subscriptions from EPAC management using something like "excludedScopes": [ "subscriptions/*" ]

Is there any recommended approach for handling Defender and it's auto-assigned policies? Or am I missing some obvious solution or misunderstanding how Defender works?

**Comment by anwather** [comment]
Could you use the `excludedPolicyAssignments`  with a wildcard to exclude these assignments as described [here](https://azure.github.io/enterprise-azure-policy-as-code/desired-state-strategy/#child-scopes-not-managed-by-any-epac-repo-but-subject-to-these-policies)?

**Comment by anwather** [comment]
```
"desiredState": {
    "strategy": "full",
    "excludedPolicyAssignments": [
"/subscriptions/*/providers/microsoft.authorization/policyassignments/opensourcerelationaldatabasesprotectionsecuritycenter",
"/subscriptions/*/providers/microsoft.authorization/policyassignments/dataprotectionsecuritycenter"
    ]
}
```
Not sure if there are others...

**Comment by glsutter** [comment]
That seems workable. Although as different Defender plans are enabled for each subscription, we might have excludedPolicyAssignments for each subscription. I will give it a try. 

I assume excludedPolicyAssignments works with assignments that include spaces. One of our excludedPolicyAssignments would look like:

"/subscriptions/*/providers/microsoft.authorization/policyassignments/defender for containers provisioning policy extension for arc-e"

**Comment by anwather** [comment]
I'm hoping you could just use the * pattern for subscriptions and they keep all the assignment names the same for each Defender auto assigned policy.
