### ISSUE TITLE
Role assignment retrieval failed with Managed Identity without role assignment

### ISSUE THREAD

**Issue by Patchfox** [Azure/enterprise-azure-policy-as-code#422]
Hi, 

we figured out that in the plan phase when the policy has a managed identity assigned but without a role, it can't be found in the search condition for assigned roles in specific scope.

You can reproduce the error when you assign the azure security benchmark policyset on a epac included scope and run the BuildDeplyomentPlan.

In the file Get-AzPolicyResource.ps1 in line 471 the $uniquePrincipalIds hashtable has a value but it can't be found in the $results of Get-AzRoleAssignment (e.g. line 467)
In my example the related policy in the policyset is: Key Vault secrets should have an expiration date. And its disabled by Microsoft per default 

Could you please check if this is a bug?

**Comment by anwather** [comment]
I'm trying to replicate this using the assignment below - however it doesn't generate a role plan since there are no policies with a modify or DINE effect - can you provide how you are doing the assignment? Hopefully I'm using the correct policy.
```
{
    "$schema": "https://raw.githubusercontent.com/Azure/enterprise-azure-policy-as-code/main/Schemas/policy-assignment-schema.json",
    "nodeName": "/root",
    "definitionEntry": {
        "policySetId": "/providers/Microsoft.Authorization/policySetDefinitions/1f3afdf9-d0c9-4c3d-847f-89da613e70a8",
        "displayName": "Microsoft Cloud Security Benchmark"
    },
    "assignment": {
        "name": "25ef7a6af77a",
        "displayName": "Microsoft Cloud Security Benchmark",
        "description": ""
    },
    "scope": {
        "test": [
            "/providers/Microsoft.Management/managementGroups/issue422"
        ]
    }
}
```

**Comment by anwather** [comment]
Closed due to no response.
