### ISSUE TITLE
Is System Assigned Managed Identities supposed to be removed when removing assignment?

### ISSUE THREAD

**Issue by ThomasStubergh** [Azure/enterprise-azure-policy-as-code#423]
Hi.

I am trying to switch from a working deployment with User Assigned Managed Identity to System Assigned Managed Identities. I have understood that it should manage to also remove RBAC roles assigned in roles when you remove an assigment, but I am not sure. I am therefore creating this issue to get some more information.

When I changed from UAMI to SAMI, the RBAC roles where automatically added at the correct management group scope. Now i tried to remove the same assignment to see if it removes the RBAC roles. It does remove the assigment along with the SAMI, but the RBAC roles at management group is not detected for removal, hence I end up with a list of unkown  identities in IAM on the management group. This has been one of my reasons to using UAMI in other policy as code deployments, as we potentially end up with a lot of unkown users in IAM.

![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/38495047/ab2b73a8-d360-4fa6-bedf-5d531fafa988)
and 
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/38495047/8f1c2c28-c88a-4bc0-b143-6f8210678fa5)

I am just curious if this is expected result, or if it should detect the removed roles. FYI there where 6 roles added when the assignment was changed from UAMI to SAMI, and I would expect the same 6 roles to be removed when i remove the assignment?

Hope i managed to explain ok and looking forward to hear from you.

Best Regards
Thomas

**Comment by anwather** [comment]
It should remove them yes - let me test and see if there is an issue - can you confirm that the account running the plan process has the correct permissions as documented -> https://azure.github.io/enterprise-azure-policy-as-code/ci-cd-pipeline/#role-assignments-for-cicd-spns

**Comment by ThomasStubergh** [comment]
Hi. Thanks for the quick reply. You were spot on about the permissions graph permissions. Since I had been using UAMI, I never needed to remove roles, as it was the same role assigned to all anyway, but changing to SAMI requires the MS Graph permissions. Now it lists them as removal, but it then fails on the confirm, where it actually tries to remove the roles. Again it seems to fail in regards to graph, but also in regards to teams in the github org?
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/38495047/878242ea-405e-42d7-aa61-c719f2cc1362)

Hope maybe you can shed some light into what it actually tried to do here? Is it relying on reviewer permissions in graph? This wouldn't work in our setup as our github is not integrated with Entra ID. Also since I am using the same OIDC for both build and deploy, the app registration has the graph permissions in regards to the build phaze, but it seems something else is happening during deploy.

I am running in github with a simplified workflow, but with OIDC instead of credentials.

Best regards,
Thomas

**Comment by ThomasStubergh** [comment]
Extra info.
I think, it's this that fails:
```github
          if (Get-ChildItem $env:planFolder -recurse -include roles-plan.json) {
            gh pr edit $env:PR_NUMBER --add-label 'RoleDeployment' --remove-label 'PolicyDeployment'
            gh pr edit $env:PR_NUMBER --title 'Approval Required for Role Deployment' --remove-reviewer $env:REVIEWER
            gh pr edit $env:PR_NUMBER --add-reviewer $env:REVIEWER
          }
```
It seems the Job/Deploy does not have needed permissions to do these changes even if it has write-all permission.
If I understand correctly, this tries to:
- remove existing label and add a new (this works)
- change the title of the PR and remove the existing reviewer (does not work)
- add the same reviewer again (does not work)

I guess the logic here is that it should update the label, title and reviewer of the PR in order to be approved again so that the roles-plan deployment will run.

There seems to be some different logics in the way that adding roles and removing roles are done in the deployment?

Is there any specific reason to why adding roles are done in the same deployment as creating policies, policy sets and assignments, while removing is separated in two deployments?

**Comment by ThomasStubergh** [comment]
FYI. I have the same error when deploying new policyset and assigning them. First it deploys the policyset and the assignment, then it tries to update the PR, which fails, but then i can reapprove the same PR and it works. Gonna test if that also works for removing policy set and assignment with RBAC as well. At leas we know it works, it's just the github logics which do not.

**Comment by ThomasStubergh** [comment]
I managed to solve it, but I had to make a change so it runs only once and needs to be approved only once. I added the second line so that both the PolicyPlan and the Rolesplan run in succession after being approved.
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/38495047/8bb2fb7b-4d18-42c2-bb48-882c633fa9ff)

**Comment by anwather** [comment]
Can you also check to make sure the box below is ticked (it might be missing from the documentation) - I think this would fix the issue you were having above. 

![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/11281622/8148abed-c34d-43e3-a060-db9e46ba62fa)

**Comment by ThomasStubergh** [comment]
> Can you also check to make sure the box below is ticked (it might be missing from the documentation) - I think this would fix the issue you were having above.
> 
> ![image](https://user-images.githubusercontent.com/11281622/284775501-8148abed-c34d-43e3-a060-db9e46ba62fa.png)

Unfortunately I have already tried that. After doing some googling it seems that github did a change 1-2 years ago limiting how the internal github.token works. I had an earlier post here as well where I also stated I needed to give the job write-all permissions to get it to work. Unfortunately I am running this all on a free version of github though, and if we had enterprise we could probably set it up with a private enterprise token instead. I don't like the PAT option as that is personal, but I also think that requires a paid plan. I am going to deploy this on a different tenant as well where they have enterprise github, so it will be interesting to see if it works better there.

**Comment by anwather** [comment]
I haven't tried using OIDC but I'll give the whole thing another test and see if I can work out what the issue might be, thanks for doing that investigation

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
