### ISSUE TITLE
Excluded Scopes Not Working As Expected

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#425]
In our pacSelector element in global-settings.jsonc, we have an excludedScopes like:

```
"excludedScopes": [ 
	"/subscriptions/*" // Ignore all subscription level policies 
]
```
Our intent is for EPAC to ignore all subscription managed policies. 

This seems to work in AzureCloud, but in AzureUSGovernment, the Build-DeploymentPlans.ps1 script reports that several subscription level policies will be deleted. For example, we see output like:

Delete 'Sandbox Policies' at /subscriptions/acb84c94-9bdf-43e8-982e-609c060c87b2

We don't see any obvious reason this behavior would be different between AzureCloud and AzureUSGovernment.

Any thoughts on what is happening and/or how we might debug?

Thanks

**Comment by glsutter** [comment]
Actually, this beahvior seems to be occurring in both AzureCloud and AzureUSGovernment. Reran our build plan in AzureCloud, and it is also deleting policies assigned at the subscription level. 

Maybe the "/subscriptions/*" isn't working as expected?

**Comment by techlake** [comment]
This was initially by design. We should add this as an option.

**Comment by glsutter** [comment]
Do you mean that "/subscriptions/*" was never working? And that it should be added as a feature?

**Comment by techlake** [comment]
Correct. It shouldn't be hard. I'll look into it later

**Comment by glsutter** [comment]
Thanks.

**Comment by techlake** [comment]
I will add a bool flag "excludeSubscriptions" to desired State. Wild cards cannot work (long story). I plan to implement this by the end of the week.

**Comment by techlake** [comment]
I believe this is fixed.

@glsutter can you test it against your scenario?

**Comment by glsutter** [comment]
I should be able to test this week. Will let you know how it goes. Thanks for the update.

**Comment by glsutter** [comment]
@techlake - Heinrich, sorry, I completely lost track of this item. But I just did a test and it didn't work as expected. The plan output included the deletion of 8 policy assignments at subscription level. 

I checked the Assigned By property on those assignments and it was NOT the pacOwnerid we're using.

**Comment by glsutter** [comment]
Do I need a specific version of EPAC for testing this change? We're running 10.0.0.

**Comment by glsutter** [comment]
I tried adding "excludeSubscriptions" under DesiredState first. Plan deleted some subscription assignments. Then I moved in under the 
"excludedScopes": [ 
	"/subscriptions/*" // Ignore all subscription level policies 
] 
approach and that deleted some subscription assignments. 
Not sure where I should be adding the new element.

**Comment by glsutter** [comment]
Checking to see if I still get a gh-issues-to-ado workflow error when posting.
