### ISSUE TITLE
Confirm-PacOwner error in Plan stage

### ISSUE THREAD

**Issue by cefasd** [Azure/enterprise-azure-policy-as-code#454]
This morning we upgrade to 9.01 in our test environment everything went smooth but in our production environment we get in de Plan - Run Build stage the following error

```===================================================================================================
Get Policy Resources for EPAC environment 'XXXX' at root scope /managementGroups/alz-XXXX
===================================================================================================
Retrieved 1000 Policy definitions, Policy Set definitions, and Policy Assignments
Retrieved 2000 Policy definitions, Policy Set definitions, and Policy Assignments
Retrieved 3000 Policy definitions, Policy Set definitions, and Policy Assignments
Retrieved 3605 Policy definitions, Policy Set definitions, and Policy Assignments
Processed 1000 Policy definitions, Policy Set definitions, and Policy Assignments
Processed 2000 Policy definitions, Policy Set definitions, and Policy Assignments
Processed 3000 Policy definitions, Policy Set definitions, and Policy Assignments
Confirm-PacOwner: /home/vsts/.local/share/powershell/Modules/EnterprisePolicyAsCode/9.0.1/internal/functions/Get-AzPolicyResources.ps1:146
Line |
 146 |  … .pacOwner = Confirm-PacOwner -ThisPacOwnerId $thisPacOwnerId -PolicyR …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

##[error]PowerShell exited with code '1'.
Finishing: Run Build
```

**Comment by anwather** [comment]
Can you post your global settings file for each environment? Remove any sensitive information of course.

**Comment by rbnmk** [comment]
We get the same error on 9.0.1

`{
    "pacOwnerId": "11111111-2222-3333-4444-555555555555",
    "pacEnvironments": [
        {
            "pacSelector": "epac-dev",
            "cloud": "AzureCloud",
            "tenantId": "*<TenantId>*",
            "deploymentRootScope": "*<Mg_ResourceId>*"
        },
        {
            "pacSelector": "tenant",
            "cloud": "AzureCloud",
            "tenantId": "*<TenantId>*",
            "deploymentRootScope": "*Mg_ResourceId>*", // replaces rootScope
            "inheritedDefinitionsScopes": [], // [optional] inherited definition scopes used but not managed by this repository, scopes must be visible from deploymentScope
            "desiredState": { // [optional]
                "strategy": "ownedOnly", // default full
                // full      = delete any unknown assignments and Policy/Set definitions in managed scope not containing metadata.pacOwnerId
                // ownedOnly = delete only our own assignments as indicated by metadata.pacOwnerId field
                "includeResourceGroups": false,
                "keepDfcSecurityAssignments": true,
                "excludedScopes": [
                    // Management Groups
                    // Subscriptions
                    // Resource Groups
                ],
                "excludedPolicyDefinitions": [
                    // wild cards allowed
                ],
                "excludedPolicySetDefinitions": [
                    // wild cards allowed
                ],
                "excludedPolicyAssignments": [
                    "*/providers/microsoft.authorization/policyassignments/newspokepolasmgt"
                ]
            }
        }
    ],
    "managedIdentityLocations": {
        "*": "westeurope"
    },
    "globalNotScopes": {
        "*": [
            "/resourceGroupPatterns/synapseworkspace-managedrg-*",
            "/resourceGroupPatterns/managed-rg-*",
            "/resourceGroupPatterns/databricks-*"
        ],
        "epac-dev": [
            "*<Mg_ResourceId>*"
        ],
        "tenant": [
            "*<Mg_ResourceId>*",
            "*<Mg_ResourceId>*"
        ]
    }
}`

**Comment by techlake** [comment]
If any of you have are using the Sync-Repo method, can we setup a devbg session, please.

**Comment by techlake** [comment]
Never mind, I may have found a missing check for $null. I'll release 9.0.2 shortly. This only happens if you have a Policy assignment at subscription or resource group level without a **description**. Can you confirm that you have at least one such assignment.

**Comment by techlake** [comment]
Please test v9.0.2

**Comment by cefasd** [comment]
Just did a full test run everything now works fine again

**Comment by techlake** [comment]
Thank you for testing this for us.
