### ISSUE TITLE
Some append policies can cause errors in the policy set plan

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#459]
STR

1. Add the attached policy to your project
[policy.json](https://github.com/Azure/enterprise-azure-policy-as-code/files/14039424/policy.json)
2. Add the policy to an initiative
3. Run a deployment plan

Results:  Below error happens on the policy set containing the above policy

![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/85254974/56e56e2b-1316-4c74-9c7d-bc521a837ddc)

**Comment by techlake** [comment]
I figured out the problem. Will fix shortly

**Comment by techlake** [comment]
@gregslack78 : can you try this code in Build-PolicyPlan.ps1 line 109:

```ps1
            # Calculate roleDefinitionIds for this Policy
            if ($null -ne $definitionProperties.policyRule.then.details) {
                $details = $definitionProperties.policyRule.then.details
                if ($details -isnot [array]) {
                    $roleDefinitionIdsInPolicy = $details.roleDefinitionIds
                    if ($null -ne $roleDefinitionIdsInPolicy) {
                        $null = $PolicyRoleIds.Add($id, $roleDefinitionIdsInPolicy)
                    }
                }
            }
```
