### ISSUE TITLE
Role Assignment error 400 -- {"error":{"code":"BadRequestFormat","message":"The request was incorrectly formatted."}}

### ISSUE THREAD

**Issue by arretesting** [Azure/enterprise-azure-policy-as-code#470]
### Discussed in https://github.com/Azure/enterprise-azure-policy-as-code/discussions/469

<div type='discussions-op-text'>

<sup>Originally posted by **arretesting** February  2, 2024</sup>
While using the newly uploaded Deploy-RolesPlan.ps1, which now includes Remove/Get/Set-AzRoleAssignmentRestMethod, I am receiving the following error message from the compilation for the @ splat.

Is there anyone who has faced the similar error message with the most recent push?

`> .\Deploy-RolesPlan.ps1

===================================================================================================
Read global settings from 'C:\Git\EpacTest\Definitions/global-settings.jsonc'.
===================================================================================================
PowerShell Versions: 7.4.1
PAC Environments: epac-dev, epac-prd
Definitions root folder: C:\Git\EpacTest\Definitions
Input folder: C:\Git\EpacTest\Output
Output folder: C:\Git\EpacTest\Output

Select Policy as Code environment [epac-dev, epac-prd]: epac-dev
Environment Selected: epac-dev
    cloud      = AzureCloud
    tenant     = <TENANT ID>
    root scope = /providers/Microsoft.Management/managementGroups/EPAC-DEV

Telemetry is disabled

***************************************************************************************************
Deploy Role assignments from plan in file 'C:\EpacTest\Output/plans-epac-dev/roles-plan.json'
Plan created on 2024-02-02 16:10:20Z.
***************************************************************************************************
===================================================================================================
Add (44) new Role assignments
---------------------------------------------------------------------------------------------------
_Assignment 'Virtual networks should be protected by Azure DDoS Network Protection', principalId 94dc2ae6-eb13-4991-9e6a-31945050563b, role Network Contributor(4d97b98b-1d4f-4787-a291-c67834d212e7) at /providers/Microsoft.Management/managementGroups/EPAC-DEV-Platform-Connectivity_
**Write-Error:** C:\Git\EpacTest\Scripts\Deploy\Deploy-RolesPlan.ps1:155
Line |
 155 |              Set-AzRoleAssignmentRestMethod @splat -IgnoreDuplicateErr …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Role Assignment error 400 -- {"error":{"code":"BadRequestFormat","message":"**The request was incorrectly formatted.**"}}`</div>

**Comment by arretesting** [comment]
Hi @techlake , @anwather , and the rest of you co-developers, 
Do you maybe have some ideas on how I can proceed from here?
I ran the deployment using the debug flag but that didn't make me any wiser as everything looks okay to me:

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/providers/Microsoft.Management/managementGroups/EPAC-DEV-Platform-Connectivity/providers/Microsoft.Authorization/roleAssignments/c12a4d26-e897-4ca2-8bb5-7ce8b09d4379?api-version=2022-04-01

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : _abc_

Body:
{
  "properties": {
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "4d97b98b-1d4f-4787-a291-c67834d212e7",
    "principalId": "94dc2ae6-eb13-4991-9e6a-31945050563b"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Set-Cookie                    : x-ms-gateway-slice=Production; path=/; secure; samesite=none; httponly
x-ms-request-id               : _def_
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-tenant-writes: 1198
x-ms-correlation-request-id   : _ghi_
x-ms-routing-request-id       : SWEDENCENTRAL:20240205T135635Z:_jkl_
X-Cache                       : CONFIG_NOCACHE
X-MSEdge-Ref                  : Ref A: _mno_ Ref B: _pqr_ Ref C: 2024-02-05T13:56:35Z
Date                          : Mon, 05 Feb 2024 13:56:35 GMT

Body:
{
  "error": {
    "code": "BadRequestFormat",
    "message": "The request was incorrectly formatted."
  }
}
```

**Comment by anwather** [comment]
Are you able to post part of the roles plan into this issue so we can validate the format - I've tested role deployment as of yesterday with no issues.

**Comment by arretesting** [comment]
Hi @anwather,
My sincere apologies for taking up your time.
I managed to solve the issue. I had a mismatch of files that originated from an old setup to the new fork I had synced with the repo (as the repo had some major changes as of the last few weeks). I started over and it worked out nicely! Thanks for being present! I will mark this bug as resolved.
