### ISSUE TITLE
Update additional role assignment functionality when assignments are present for the PAC under deployment

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#471]
The issue is if you have additional role assignments in an assignment file where a role assignment if for "*" and "myPAC" and are deploying to "myPac", the "*" roles assignments will also be deployed.  This is counter to how similar structures are handled elsewhere (e.g. notScope, MILocations)

**Comment by gregslack78** [comment]
Changing to a bug since the existing documentation appears to match up with the change to functionality.

**Comment by techlake** [comment]
Fixed in v10.0.0
