### ISSUE TITLE
How do you update powershell module here

### ISSUE THREAD

**Issue by chanakanissanka** [Azure/enterprise-azure-policy-as-code#474]
Hi Folks, 
We intend to use this EPAC for our Azure Governance initiative, and one thing that came up during the evaluation was how best to stay up-to-date with the releases here with our local copy. Apologies If I'm asking something obvious here, still we can't get our head around how releases can be automated. 

regards,
Chanaka

**Comment by anwather** [comment]
Use the PowerShell module from the gallery (EnterprisePolicyAsCode) - it is updated when releases are made via this GitHub repo

**Comment by chanakanissanka** [comment]
@anwather sorry for taking time to come back...Is this what's already been used here - https://github.com/Azure/enterprise-azure-policy-as-code/tree/main/Module ?

**Comment by anwather** [comment]
@chanakanissanka 
Please read https://azure.github.io/enterprise-azure-policy-as-code/quick-start/ for how to manage the module code.
You can either use the PowerShell module (EnterprisePolicyAsCode) or you can fork and clone this repository. Using the PowerShell module is recommended as you do not have to maintain the scripts folder to keep in sync with changes. All you need is a folder for you definitions etc. The ```Module``` folder is used internally by the development team to automatically build the PowerShell module when a new release is generated.

For instance - most of my projects only contain a single folder for Definitions - I use the PowerShell module to then run the commands to build and deploy policy and roles.

**Comment by chanakanissanka** [comment]
@anwather Thanks for this clear instructions and that makes sense.

**Comment by chanakanissanka** [comment]
@anwather I have no option but to fork the repo due to some bs regulations. Would it be possible to get an idea of the best way to accommodate future releases other than copying and pasting those scripts? Sorry if I'm asking something obvious.

**Comment by anwather** [comment]
There is a script called Sync-Repo.ps1 in the repository which can do the copy.

The PowerShell module has been created to accommodate future release.



________________________________
