### ISSUE TITLE
Draft 4 JSON Schema - No longer supported

### ISSUE THREAD

**Issue by sveno1990** [Azure/enterprise-azure-policy-as-code#475]
Powershell dropped the support for Draft 4 of JSON schema in 7.4 (by switching test-json from Newtonsoft.Json.Schema. to JsonSchema.Net. https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-74?view=powershell-7.4

In general draft 4 is used less and less and customers who would like to validate the json before running EPAC might run into issues. Would it be possible to update the schema to a new version of JSON schema?

Thank you for the response in advance.

**Comment by gregslack78** [comment]
Json validation was addressed in version [v8.4.6](https://github.com/Azure/enterprise-azure-policy-as-code/releases/tag/v8.4.6)

**Comment by techlake** [comment]
@sveno1990 what version should we use?

**Comment by sveno1990** [comment]
You are right the test-json was removed from the EPAC code in an earlier version. 
Any version higher than draft 04 should do the job. the latest is 2020-12

**Comment by techlake** [comment]
Move to schema   "$schema": "https://json-schema.org/draft/2020-12/schema"

**Comment by techlake** [comment]
Fixed in v10.0.0
