### ISSUE TITLE
How to get the access to create an issue for Azure/enterprise-azure-policy-as-code repository

### ISSUE THREAD

**Issue by naveensushanth** [Azure/enterprise-azure-policy-as-code#476]
I'm working in GSK organization, but using my GSK ORG ID unable to create an issue for repository Azure/enterprise-azure-policy-as-code.

Please let me know the process for create an issue

**Comment by techlake** [comment]
You just created one. This is an issue.

**Comment by naveensushanth** [comment]
I created using my personal account not using organization account, is it ok to create an issue?
