### ISSUE TITLE
Any document to separate the Azure exemption pipeline from Azure definition

### ISSUE THREAD

**Issue by naveensushanth** [Azure/enterprise-azure-policy-as-code#477]

**Comment by techlake** [comment]
Documented here: https://azure.github.io/enterprise-azure-policy-as-code/desired-state-strategy/#use-case-2-manage-policy-definitions-assignments-or-exemptions-differently

You can also use a single repo with to separate "Definitions" folders; for example:

- `Definitions` for Policy Assignments, and Definitions
- `Exemptions` for Exemptions only

**Comment by techlake** [comment]
Please close if this solves your problem
