### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#479]
Having some issues with documentation and want to ask about what I've experienced while running Build-PolicyDocumentation. 

1) I entered two representativeAssignments for two policy sets in my policyDocumentations json file, but the markdown output file  included only the first policy set. Is that behavior expected?
2) Can't use a policy assignment as a representativeAssignment. Only policy set documentation can be created. Is that still the limitation? 

What I'd like is to document all of the assignments (both policy sets and policies) to a specific management group. Can you confirm that is not possible with current EPAC scripts?

Thanks

**Comment by techlake** [comment]
Pease ask for a meeting to show me

**Comment by techlake** [comment]
Closed due to inaction
