### ISSUE TITLE
[ChinaCloud] PolicyAssignment is not recognizing as a PAC

### ISSUE THREAD

**Issue by naveensushanth** [Azure/enterprise-azure-policy-as-code#489]
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/45732282/64425177-8b45-4a18-a27e-c383c678ca9f)

We set up EPAC for Azure china, but while build a deployment plan it shows no change, but there is a changed file available under policyAssignment,

Please let me know how to troubleshoot this issue,

Thanks in advance,

**Comment by techlake** [comment]
@gregslack78 : please update this with the current state of fixing this.

**Comment by techlake** [comment]
Fixed in v10.0.0
