### ISSUE TITLE
EPAC Resource Policy Reader Role should have Microsoft.Authorization/roleAssignments/read

### ISSUE THREAD

**Issue by benjaminpieplow** [Azure/enterprise-azure-policy-as-code#496]
The `sc-pac-plan` App Registration ([Via](https://azure.github.io/enterprise-azure-policy-as-code/ci-cd-ado-pipelines/#single-tenant-stages)) does not receive the `Microsoft.Authorization/roleAssignments/read` role when given the custom EPAC Resource Policy Reader Role ([Via](https://azure.github.io/enterprise-azure-policy-as-code/ci-cd-app-registrations/#custom-epac-resource-policy-reader-role)), which is required to list role assignments on management groups. This causes the Plan stage to fail enumerating role assignments, leading to a warning during Plan, and always requiring the Deploy Roles stage to run when using a more advanced pipeline.

This role is defined in documentation in,
* https://azure.github.io/enterprise-azure-policy-as-code/ci-cd-app-registrations/#custom-epac-resource-policy-reader-role
* https://azure.github.io/enterprise-azure-policy-as-code/create-policy-reader-role/

**Comment by techlake** [comment]
- Needs update of script to generate reader role
- Fix documentation

**Comment by benjaminpieplow** [comment]
Hi @techlake, @anniebee6856,

Before any time is spent on this, I have created a pull request (#497) in which I have updated the role generation script, the mentioned role assignment documentation, and the images for the manual creation of the role. It just needs an approval.

**Comment by techlake** [comment]
Thank you for the contribution. I merged it into main
