### ISSUE TITLE
Confused how do I update CSV assignment file

### ISSUE THREAD

**Issue by artisticcheese** [Azure/enterprise-azure-policy-as-code#498]
Hello,

We have EPOC running for quite sometime and I have our own CSV file with parameters for Azure Security Benchmark which I beleive I got from sample folder upon original installation. This will is missing entries now from newer version of ASB and have some outdated entries as well.
I do not understand what is process of updating it.
I saw something about documentation but we are not using and not planning to use documentation, I just need this file to be updated to be consistent to what is deployed to cloud.
What shall I do get updated CSV file?

**Comment by techlake** [comment]
Hi, sorry it took me so long to repond. Here are the choices:

1. The best way to do this is to generate a new CSV file from the Policy Set (Initiative) definition via Buil-PolicyDocumentation. The resulting file will need to be merged manually to your existing CSV file. The warnings printed by EPAC tells you which lines from the generated file to add to your existing CSV file.
2. Regenerate the CSB file by using the Policy Assignment documentation feature in Build-PolicyDocumentaion. This will be preserving your existing CSV and having the new rows appear. After validating that it is correct, you can replace your existing CSV with the generated one. Note: If you use NIST in addition to ASB, delete the Manual effects - they are superflous.
3. I plan to add a script to generate this automatically (enhancement)

**Comment by artisticcheese** [comment]
How do I do number 1?
Build-PolicyDocumentation only exports already assigned polices and their parameter values, it does not export policies which do have customization of parameters.

**Comment by techlake** [comment]
I would recommend 2. instead (unless you added additional columns in your spreadsheet. Use assignment documentation It will create the CSV file of your current deployment including any added/deleted rows and will put the effective Effect in the right column.

- https://azure.github.io/enterprise-azure-policy-as-code/documenting-assignments-and-policy-sets/
- https://azure.github.io/enterprise-azure-policy-as-code/documenting-assignments-and-policy-sets/#assignment-documentation
- https://azure.github.io/enterprise-azure-policy-as-code/documenting-assignments-and-policy-sets/#example-documentation-specification-file

PS: I would delete all the Manual (effect) Policy rows (part of NIST and some other regulatory compliance Initiatives) in your spreadsheet.

**Comment by techlake** [comment]
I would recommend 2. instead (unless you added additional columns in your spreadsheet. Use assignment documentation It will create the CSV file of your current deployment including any added/deleted rows and will put the effective Effect in the right column. How to, see:

- https://azure.github.io/enterprise-azure-policy-as-code/documenting-assignments-and-policy-sets/
- https://azure.github.io/enterprise-azure-policy-as-code/documenting-assignments-and-policy-sets/#assignment-documentation
- https://azure.github.io/enterprise-azure-policy-as-code/documenting-assignments-and-policy-sets/#example-documentation-specification-file

**Comment by artisticcheese** [comment]
Build-Documentation generates report of policies which default value of paramater was overriden, it does not generate ALL policies. I get output of 200 rows across 2 environments, while policy itself on it's own have 1000K+ rows.

**Comment by artisticcheese** [comment]
Ok, found out a reason, it seems that `documentInitiatives` was renamed at some point to `documentPolicySets` and hence those were not exported as a result

**Comment by artisticcheese** [comment]
Actually it still did not work

**Comment by techlake** [comment]
v10.0.0 will have partial fix.
Slated a better script for 10.1.0

**Comment by techlake** [comment]
v10.0.0 released on 4/5/2024
