### ISSUE TITLE
Update GitHub actions using Node.js 16 before Spring 2024

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/enterprise-azure-policy-as-code#500]
Node.js 16 is deprecated and will be removed in GitHub hosted workers by "Spring 2024":

* https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Update GitHub actions using Node.js 16.

* automated-publish.yaml: <https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/.github/workflows/automated-publish.yaml>
  * `actions/checkout`: <https://github.com/actions/checkout>
* publish-docs.yaml: <https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/.github/workflows/publish-docs.yaml>
  * `actions/checkout`: <https://github.com/actions/checkout>
  * `actions/setup-python`: <https://github.com/actions/setup-python>

**Comment by anwather** [comment]
@techlake - this is fixed in development environment - I'll wait for you changes to be pulled to GH before closing

**Comment by techlake** [comment]
Fixed in v10.0.0 released on 4/5/2024
