### ISSUE TITLE
Feature: Add "assignedBy" property to globalSettings

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#502]
If an assignedBy value is not provided in the assignment metadata, it would be good to allow for a standard value to be used.  The currently thought is to create a new property in globalSettings kind of inline with the pacOwner and have the value of that property injected when no value is present in the assignment file. 

Possibly also/alternatively add this to the pacEnv as it may be desirable to have different values per environment.

**Comment by techlake** [comment]
If metadata in definition contains assignedBy - keep it,
else set to: epac/<pacOwnerId>/<pacSelector>

**Comment by techlake** [comment]
Implemented in v10.0.0, released 4/5/2024
