### ISSUE TITLE
PolicyAssignment resourceSelectors name is used as assignment name

### ISSUE THREAD

**Issue by edr-vlk** [Azure/enterprise-azure-policy-as-code#515]
We had exported an existing PolicyAssignment which was configured with several children in the json object.
Each child has assignment and resourceSelectors, but when applying through EPAC, the resourceSelectors name is used as the policy assignment name.

In the policy-assignment-schema.json

  "children": [
    {
      "nodeName": "/child-0",
      "assignment": {
        "name": "d52dab3fa50b4d47b85b1564",
        "displayName": "Configure Private Link for Azure Key Vault - FST",
        "description": ""
      },
      "parameters": {
      },
      "resourceSelectors": [
        {
          "name": "westeurope",
          "selectors": [
            {
              "in": [
                "westeurope"
              ],
              "kind": "resourceLocation"
            }
          ]
        }
      ],

this resulted to PolicyAssignment.   The following taken from Get-AzPolicyAssignment | ConvertTo-Json -Depth 9   for the generated policy assignment.

   "Location":  "westeurope",
    "Name":  "westeurope",
    "ResourceId":  "/subscriptions/xxxxxxxx/providers/Microsoft.Authorization/policyAssignments/westeurope",
    "ResourceName":  "westeurope",
    "ResourceGroupName":  null,
    "ResourceType":  "Microsoft.Authorization/policyAssignments",
 

Can this be resolved?
Kind regards,
Eric

**Comment by techlake** [comment]
Is fixed in v10.0.0, expected later today

**Comment by techlake** [comment]
Fixed in v10.0.0 released on 4/5/2024
