### ISSUE TITLE
Question: Summary of changes to be used in PR comments

### ISSUE THREAD

**Issue by teemukom** [Azure/enterprise-azure-policy-as-code#538]
Not a bug but a feature request / question

Is there a way to create a summary of the changes about to happen which could be used in PR comments? When creating the PR we can use the tenant plan workflow to review what is going to happen but it requires a few extra steps. What would be nice to have some kind of sanitized summary of the changes and assignments which we could use to create a PR comment with a workflow.

**Comment by anwather** [comment]
There is a global variable called ```epacInfoStream``` which all output is appended to, including the summary of changes. I've used this output in the body of a PR

**Comment by teemukom** [comment]
Oh nice one @anwather ! That would work but seems to require a bit of cleanup to be used in a PR comment
