### ISSUE TITLE
Help with setting up ADO pipeline - Question

### ISSUE THREAD

**Issue by chanakanissanka** [Azure/enterprise-azure-policy-as-code#542]
Would it be possible to give an idea of setting up the ADO pipeline with this new release or any link to a doc that we can follow? I'm a little bit confused at the moment about the new layout for setting up an ADO pipeline. 
I previously used this https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/Docs/ci-cd-ado-pipelines.md, and it seems it's not valid anymore. 

AB#44050

**Comment by chanakanissanka** [comment]
Was able to use the previously provided pipeline yaml ( singlet-tenant-pipeline.yml and multiple-tenant-pipeline.yml) . would this still be the recommended way or is there any other I have missed?

**Comment by arrerezai** [comment]
If it makes you feel any better, I am also utilizing the old pipeline (multiple-tenant-pipeline.yml) as the new layout is lacking any explanation on how we should use it. However, the old pipeline is working perfectly fine. Hopefully, a guide is presented hand-in-hand with the first bug fixes in v10.

**Comment by chanakanissanka** [comment]
@techlake  @anwather Any update on this kindly please, I'm on the edge of making this go live for our Env and this recent changes gives bit of uncertainty and need to have a solid understanding of it before dropping this into live. TIA

**Comment by anwather** [comment]
I haven't had time to go through this and the new pipelines - but I do know the templates folders need to be renamed to ```templates``` - and depending on if you use the PowerShell module or the scripts you simply pick the matching folder to rename.

**Comment by apybar** [comment]
Adding to backlog
