### ISSUE TITLE
WARNING: INITIALIZATION: Fallback context save mode to process because of error during checking token cache persistence.

### ISSUE THREAD

**Issue by arrerezai** [Azure/enterprise-azure-policy-as-code#544]
**Describe the bug**

_"WARNING: INITIALIZATION: Fallback context save mode to process because of error during checking token cache persistence: Persistence check fails due to unknown error."_

_"Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.
ClientAssertionCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH."_

These two messages (the first one being a warning message and the second one eventually being an error message) shows up with the new introduction of throttleLimit in v10+. It has to do with the ForEach-Object -Parallel loop in the Deploy-PolicyPlan.ps1.

**To Reproduce**
Run the Deploy-PolicyPlan.ps1 with a lot of new policies, policy sets, and assignments, while not using the very latest Az version (I use 11.3.1).

**Expected behavior**
Should handle parallel runs. Would also be beneficial to add better error handling (/a fail safe).

**Screenshots**
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/0e217150-7901-4a3e-86be-753a59cf2254)

**EPAC Version**
Versions 10.0.0-10.0.2

**Comment by arrerezai** [comment]
There is an old post on this same exact error [here](https://learn.microsoft.com/en-us/answers/questions/1390597/warning-in-powershell-az-accounts-module-when-sett)

**Comment by techlake** [comment]
Try rerunning it. I see this occasionally as an intermittent problem.

**Comment by arrerezai** [comment]
I ran it 10+ times before eventually giving up and specifying the throttleLimit = 1. Whether permanent or intermittent, there is no real error handling for this and no justification to speed things up a tiny bit by running things in parallel if it is only to work occasionally.

**Comment by HampusNL** [comment]
I see the same error and I agree with @arrerezai, the process should not prioritize speed over quality. I wrote a simple retry logic when working with some graph endpoints in larger environments that required me to speed up the execution but still make sure it works, it looks something like this.

$StartThreadCount = 4
do {
    try {
        Write-Verbose -Message "Running through all groups with {$StartThreadCount} threads."
        $Output = $Input | ForEach-Object -Parallel {
            # Run task with erroraction stop to catch errors.
        } -ThrottleLimit $StartThreadCount
        $Success = $true
    } catch {
        $StartThreadCount -= 2
        $Success = $false
    }
} until ($Success -eq $true -or $StartThreadCount -eq 0)
if ($Success -eq $false) {
    Write-Verbose -Message "Failed to run with parallel threads, retrying with only one thread."
    # Wait a bit before retrying with single thread.
    Start-Sleep -Seconds 60
    $Output = $Input | ForEach-Object {
        #Run task with one thread
    }
}

**Comment by techlake** [comment]
I'll remove the parallel execution

**Comment by techlake** [comment]
Fixed in latest version v10.1.1
