### ISSUE TITLE
EPAC Resource Policy Reader Role requires Microsoft.Resources/subscriptions/resourceGroups/read

### ISSUE THREAD

**Issue by benjaminpieplow** [Azure/enterprise-azure-policy-as-code#545]
**Describe the bug**
The custom role EPAC Resource Policy Reader defined in [App Registrations Setup](https://azure.github.io/enterprise-azure-policy-as-code/ci-cd-app-registrations/) does not define a permission to read resource groups. This causes the plan stage to see zero Resource Groups:
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/103761435/c8382d8e-cbb9-426d-a953-22a4cf756563)

This introduces further downstream issues planning dynamic [notScopes](https://azure.github.io/enterprise-azure-policy-as-code/policy-assignments/#assignment-scopes-and-excluded-scopes) as they require a list of resource groups to [calculate](https://azure.github.io/enterprise-azure-policy-as-code/settings-global-setting-file/#excluding-scopes-for-all-assignments-with-globalnotscopes)

**To Reproduce**
This should be reproducible in all greenfield deployments, unless additional permissions were granted to the sc-pac-plan service connections/App Registrations.

**Expected behavior**
Scope tree should include Resource group count >0

**Next Steps**
I think the easiest way to resolve this would be to add the previously mentioned permission to documentation, very similar to #496. I was able to resolve the issue by assigning the `Microsoft.Resources/subscriptions/resourceGroups/read` permission to the EPAC Resource Policy Reader custom role.

**EPAC Version**
Version of EPAC module you are using.

* EPAC: v10.0.2
* Azure PowerShell 5.237.9
* PowerShell 7.4.1
* Az version 11.3.1

**Comment by techlake** [comment]
Sorry, a regression
