### ISSUE TITLE
Using the documentation feature for policy assignments

### ISSUE THREAD

**Issue by RelicCornhusk** [Azure/enterprise-azure-policy-as-code#55]
Hello there,

I'm having trouble using the assignment documentation feature to document policy assignments (for both built-in and custom policies). It is able to document initiative assignments without a problem, pulling the correct name, description and effect(s). However, if I add an assignment of definition type policy to the assignment ID in the representativeAssignments block, the result looks like this:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/84695648/182943194-08a3341c-fddb-425a-9855-418342532c28.png">

I couldn't find anywhere in the [documentation](https://github.com/Azure/enterprise-azure-policy-as-code/tree/main/Definitions/Documentation) that it is meant to be used only with initiative assignments, so I wanted to confirm if this is working as expected or whether this is an error on my end.

Here is the assignment in question, should it be helpful in debugging this issue.
```json
{
    "nodeName": "parentNode",
    "parameters": {
        "resourceGroupLocation": "canadacentral"
    },
    "definitionEntry": {
        "policyName": "ffb6f416-7bd2-4488-8828-56585fef2be9",
        "friendlyNameToDocumentIfGuid": "Deploy export to Log Analytics workspace for Microsoft Defender for Cloud data"
    },
    "assignment": {
        "Name": "exportDefenderLogs",
        "displayName": "Deploy export to Log Analytics workspace for Microsoft Defender for Cloud data",
        "description": "Enable export to Log Analytics workspace of Microsoft Defender for Cloud data. This policy deploys an export to Log Analytics workspace configuration with your conditions and target workspace on the assigned scope. To deploy this policy on newly created subscriptions, open the Compliance tab, select the relevant non-compliant assignment and create a remediation task."
    },
    "children": [
        {
            "nodeName": "PRD",
            "parameters": {
                "resourceGroupName": "<rg-name>",
                "workspaceResourceId": "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.OperationalInsights/workspaces/<workspace-id>"
            },
            "scope": {
                "prod": [
                    "/providers/Microsoft.Management/managementGroups/<management-group-id>"
                ]
            }
        }
    ]
}
```

Thanks for the hard work put in this project!

**Comment by techlake** [comment]
The documentation feature works for initiative assignments only. I should document that caveat. There are no plans to support documentation for Policy  Assignments.
