### ISSUE TITLE
[Feature request] GitHub - Issue template for feature requests

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/enterprise-azure-policy-as-code#550]
Create a GitHub issue template for feature requests.

Or link to [Discussions -> Ideas](https://github.com/Azure/enterprise-azure-policy-as-code/discussions/categories/ideas) in the issue template if that's where you want them.

**Comment by techlake** [comment]
We are trying to keep it simple. Just input an Issue and tag it with the new tag I just added "feature request". I tagged this issue with it.

**Comment by anwather** [comment]
@techlake - I'll set this up
