### ISSUE TITLE
Assign Permissions setting ignored on parameters

### ISSUE THREAD

**Issue by sveno1990** [Azure/enterprise-azure-policy-as-code#561]
**Describe the bug**
When deploying a policy assignment for a definition that uses the assignPermissions attribute of parameters e.g. `e920df7f-9a64-4066-9b58-52684c02a091` to set a role assignment on a secondary scope, this scope is ignored.

From documentation:
assignPermissions: (Optional) Set as true to have Azure portal create role assignments during policy assignment. This property is useful in case you wish to assign permissions outside the assignment scope. There's one role assignment per role definition in the policy (or per role definition in all of the initiative's policies). The parameter value must be a valid resource or scope.

https://learn.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure-parameters

**To Reproduce**
Create a policy assignment for policy e920df7f-9a64-4066-9b58-52684c02a091 with a loganalytics workspace in a scope other than the network security group and the main scope of the policy. 

**Expected behavior**
I would expect the contributor role to be assigned on both the network security group scope and the log analytics workspace scope, but the role is only assigned to the main scope of the policy assignment

**Screenshots**
N/A

**EPAC Version**
10.0.2

**Comment by anwather** [comment]
@techlake - how long has this been available for? I've never seen it, we could add this value as an additionalRoleAssignment?

**Comment by anwather** [comment]
#562 looks like a regression introduced in v10

**Comment by techlake** [comment]
Currently, use "additionalRoleAssignments" as the solution (work around). We are looking into fixing this soon.

**Comment by sveno1990** [comment]
Thanks @techlake, I indeed use the additionalRoleAssignments for now.

**Comment by techlake** [comment]
Many Policies do not set this; therefore, we will continue using the additionalRoleAssignments workaround
