### ISSUE TITLE
Testing v10 introduces breaking changes for Role assignments

### ISSUE THREAD

**Issue by tsunami28** [Azure/enterprise-azure-policy-as-code#562]
**Describe the bug**
Same assignment type used with v8 has more than just update(metadata) within v10 for "additionalRoleAssignments"

**To Reproduce**
New branch with v10 and only mandatory adjustments for global-settings file.

**Expected behavior**
EPAC V8 deployed resource scoped role assignments as defined in the code (assignment files).
With same files, EPAC v10 is reporting that it will remove those assignments and push them to the highest level (level of the set assignment).
Provided screenshots are pointing to that.

**Screenshots**
![Screenshot_433](https://github.com/Azure/enterprise-azure-policy-as-code/assets/46718446/75e79359-d927-4970-adf3-1d99709b2eb4)
![Screenshot_432](https://github.com/Azure/enterprise-azure-policy-as-code/assets/46718446/c25220cf-67f6-4469-8978-5066a0c86bf3)

**EPAC Version**
Version of EPAC module you are using.
V8 in Production and testing switch to v10

**Comment by techlake** [comment]
We believe that we fixed this in v10.1.0. We had a nasty role assignment bug.
