### ISSUE TITLE
IgnoreScopeTreeErrors parameter removed from Build script

### ISSUE THREAD

**Issue by robsissons-contino** [Azure/enterprise-azure-policy-as-code#564]
**Describe the bug**
in v10.0.0 the "IgnoreScopeTreeErrors" parameter has been removed from the Build script.. There is no mention of this in the release notes that I can see.

**To Reproduce**
Running existing pipelines with the -IgnoreScopeTreeErrors switch fail due to the switch being deprecated.

Removing the switch from the build command appears to work (and ignore the errors previously seen in our environment) so this functionality appears to be handled natively without the switch now (assumed using the new "Build-ScopeTable" scripts.

**Expected behaviour**
Release notes should mention that a parameter has been removed from the build script and how this functionality has been modified.

**EPAC Version**
v10.0.0 and above

**Comment by techlake** [comment]
Correct, this is handled natively. My bad: I missed including this in the release notes.
