### ISSUE TITLE
V10 - unexpected policy assignment removals for a different pac selector when running in owned only

### ISSUE THREAD

**Issue by roddick-mark** [Azure/enterprise-azure-policy-as-code#565]
**Describe the bug**

When running in OwnedOnly, policy assignments which are not part of the current pac environment but within the current pacOwnerId are removed

**To Reproduce**
- 2 pacEnvironments, 1 scoped at a management group, 1 scoped at a child subscription. Both pacEnvironments with the same pacOwnerId and with "strategy": "ownedOnly"
- A policy assignment created for one of the pacEnvironments
- Run Build-DeploymentPlans against the pacEnvironment without the assignment
- Observe that EPAC wants to remove the policy assignment

**Expected behavior**

The policy assignment shouldn't be removed

**Screenshots**

V8.4.3:

No Policy Assignments are deleted

```
===================================================================================================
Summary
===================================================================================================
Policy counts:
    238 unchanged
    1 changes:
        new     = 0
        update  = 1
        replace = 0
        delete  = 0
Policy Set counts:
    38 unchanged
    0 changes
Policy Assignment counts:
    37 unchanged
    1 changes:
        new     = 0
        update  = 1
        replace = 0
        delete  = 0
```

V10.0.4:

2 Policy Assignments for assignments outside of the pacEnvironment are deleted:

```
===================================================================================================
Summary
===================================================================================================
Policy counts:
    0 unchanged
    239 changes:
        new     = 0
        update  = 239
        replace = 0
        delete  = 0
Policy Set counts:
    0 unchanged
    38 changes:
        new     = 0
        update  = 38
        replace = 0
        delete  = 0
Policy Assignment counts:
    0 unchanged
    40 changes:
        new     = 0
        update  = 38
        replace = 0
        delete  = 2
```

**EPAC Version**
- V8.4.3 (working)
- V10.0.4 (broken)

**Comment by techlake** [comment]
Can you share your global-settings.jsonc. I'm suspecting an issue with your globalNotScopes array. globalNotScopes are REALLY different in v10.0.0

**Comment by roddick-mark** [comment]
Hi @techlake we are not using globalNotScopes across either version.
It only seems to be assignments which are effected. We have some policies and policy sets managed via PAC at the subscription level under the management group, these don't show as "delete" in the plan.

**Comment by roddick-mark** [comment]
Thanks @techlake, globalNotScopes works.
I've just worked out what was happening and why it was working in v8 - the nested subscription pac environment had policy assignments at a resource group level with includeResourceGroups set to true. The management group pac selector had includeResourceGroups set to false. Because includeResourceGroups is removed in v10 thats why we ran into this issue.

**Comment by techlake** [comment]
Thank you for the update. Closing the issue!
