### ISSUE TITLE
additionalRoleAssignments has issues in EPAC v10+

### ISSUE THREAD

**Issue by arrerezai** [Azure/enterprise-azure-policy-as-code#571]
**Describe the bug**
In EPAC v9+, the role assignment was always Unknown. This could have been for different reasons, but it still managed to get it right once viewed in the Azure Portal.
Starting from EPAC v10, this is no longer the case. The additional role assignment isn't even detected while running the Build-DeploymentPlans and hence, there is no role to later deploy in the Deploy-RolesPlan.

**To Reproduce**
I went on and ran the same exact policyAssignments, Definitions, and SetDefinitions using the same service connections and to the same exact tenant. V9 created the role assignment, whereas V10 removed it as can be seen by the screenshots.

I am using the follopwing structure:
`"additionalRoleAssignments": {
                        "epac-prd": [
                            {
                                "roleDefinitionId": "/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7",
                                "scope": "/subscriptions/_<subscriptionId>_"
                            }
                        ]
                    }`

**Expected behavior**
For the role assignment to show up in the subscription that I am trying to assign it to.

**Screenshots**
V9:

Here, it gets added correctly:
![Deploy-RolesPlan adds the new role assignment correctly](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/d14a60be-410a-4952-b9ff-044f9a627f38)

And is correctly represented under the connectivity subscription in the Azure Portal:
![Viewing the Connectivity subscription in Azure Portal shows the successful role assignment](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/9eeb7c05-33e9-45fb-9693-2e3fa2cfb070)

V10:

Here, the Build-DeploymentPlans is already indicating the removal of the role assignment:
![Build-DeploymentPlans strangely returns the removal of the role](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/49616c95-62c4-4d2c-8903-ec380494fd35)

And it gets seen as an obsolete role assignment, which in turn gets removed, despite being declared in the ALZ-Corp-Default file the same way as before:
![Deploy-RolePlan removes the role incorrectly and updates the assignment on Corp, not linking it to the Subscription living in the Connectivity MG group anymore](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/a090a097-14f1-4ce4-a11d-e484d8fa30d1)

**EPAC Version**
v10.0.4

**Comment by techlake** [comment]
Bug fix was checked in with v10.1.0. Please verify that it fixes this issue.

**Comment by arrerezai** [comment]
Yes, indeed. Issue is solved in 10.1.0.

**Comment by arrerezai** [comment]
Hi @techlake,
Unfortunately, issue presented itself again in v10.1.5:

Plan:
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/519e3235-c937-485b-aecf-cbd5a0c0e6ca)

Deploy Role Assignment:
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/d33e3b7c-2351-4d92-8cf7-9f1c9a9a9f83)

**Comment by techlake** [comment]
Is this still an issue?

**Comment by arrerezai** [comment]
@techlake, just tried with v10.2.1 and must say unfortunately yes, and by the looks of the thumbs up, seems to be the case for others as well.

**Comment by techlake** [comment]
The current issue is a different bug. I have this fixed and will push shortly.

https://github.com/Azure/enterprise-azure-policy-as-code/issues/609

**Comment by arrerezai** [comment]
I can confirm Epac v10.2.2 has the issue fixed again, thanks!
