### ISSUE TITLE
Simplifying SPNs and RBAC: improve guidance,

### ISSUE THREAD

**Issue by techlake** [Azure/enterprise-azure-policy-as-code#573]
New guidance and test to verify (we need a pristine tenant) RBAC:
- SPN for Build-DeploymentPlans per tenant with tenant-level Reader (is regular Reader sufficient?)
  - If we are in China or UsGov, may need additional permissions since we are not using ARG queries for some items
  - Can we avoid configure MS Graph permissions
  - Do not subdivide the plan SPN by EPAC environment; I have some great ideas if we can do this!
- SPN to Deploy-PolicyPlan with Policy Contributor either at 
  - each tenant root or pseudo root (preferred)
  - each EPAC environment root (today's guidance)
- SPN to Deploy-RolesPlan with User Access Administrator
  - each tenant or pseudo root
  - needed for additional Role assignments

AB#44049

**Comment by apybar** [comment]
Adding to backlog
