### ISSUE TITLE
Changing Parameter values does not trigger update of policyDefintion, policySetDefintion and Assignment for parameters of type list

### ISSUE THREAD

**Issue by JBlchr** [Azure/enterprise-azure-policy-as-code#574]
**Describe the bug**
When updating default value of a parameter in either policyAssignment, policySetDefinition or policyDefinition that is a list type parameter the changes are not detected and no plan is created.

**To Reproduce**
Deploy a policy with a parameter that accepts a list like:         
```
"defaultValue": [
          "GeneralPurpose",
          "Hyperscale",
          "BusinessCritical"
        ],
```

After deployment change the default value to only first 1 item in the list. like:
```
"defaultValue": [
          "GeneralPurpose"
        ]
```

for assignment:
```
"SQL.21.listOfAllowedSkus": [
      "GeneralPurpose",
      "Hyperscale",
      "BusinessCritical"
    ]
```
to 
```
        "defaultValue": [
          "GeneralPurpose"
        ]
```

Build your deployment plan for the changes
In the plan no changes are detected, accordingly no plan files are generated

**Expected behavior**
A planfile with the changed values is created and can be rolled out.

**Screenshots**
Plan output:
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/106380221/6c602e6b-c53b-4656-a90e-f634bb0b3474)

**EPAC Version**
EnterprisePolicyAsCode 10.0.4

**Comment by techlake** [comment]
Definetly a bug. I can reproduce

**Comment by techlake** [comment]
Root cause:
$true -eq (@("S") -eq @("T","S","N")) is false
$true -eq (@("T","S","N") -eq @("S"))
This happens only when one of the arrays has one entry.

**Comment by techlake** [comment]
Really hard to fix.
Working on it.

**Comment by JBlchr** [comment]
Thanks so much for being this quick to respond and fixing the bug right away. I posted the issue and went on vacation right after (as I encountered the issue on my last working day) so that is why I am just responding now again. Again, thank you!
