### ISSUE TITLE
Scope counts are off based on the root scope type

### ISSUE THREAD

**Issue by gregslack78** [Azure/enterprise-azure-policy-as-code#578]
Depending on the type of scope the root scope is, that scope count will be off by one in the scope tree output.

The issue is in lines 130-14- in Build-ScopeTableForDeploymentRootScope it needs to leave the root scope out of the count.

**Comment by anwather** [comment]
@gregslack78 - any update on this issue?

**Comment by gregslack78** [comment]
@anwather - I think this was fixed as a side bug with something else so didn't get auto-closed.  I'll take a look today.

**Comment by gregslack78** [comment]
Looks like this is still a bug but found another bug while testing so I can't fully test this yet.  I'll get a fix in for both today.
