### ISSUE TITLE
EnterprisePolicyAsCode module - Catch and display errors instead of showing hardcoded error messages

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/enterprise-azure-policy-as-code#581]
**Is your feature request related to a problem? Please describe.**

EPAC PowerShell tooling should properly handle errors and display relevant error messages dynamically.

Example help script `Build-ScopeTableForDeploymentRootScope.ps1` called by EPAC module cmdlet `Export-AzPolicyResources` crashed for a collegue of mine. As error messages are hardcoded, like this example:

* <https://github.com/Azure/enterprise-azure-policy-as-code/blob/7092b094e75b14d802f8623bf2fd3def53b77cb5/Scripts/Helpers/Build-ScopeTableForDeploymentRootScope.ps1#L115>

We had little info for starting the debugging. In his example it turned out that Az modules where old, very old. And getting them up to date made this script work again.

So this had nothing to do with Azure RM permissions, like the hardcoded error message indicates.

**Describe the solution you'd like**

I'd like EPAC PowerShell scripts to properly handle errors, and display the actual error message/exception.

**Describe alternatives you've considered**

None yet.

**Additional context**

* PowerShell v7.4.2
* EnterprisePolicyAsCode v10.1.2
* Az.Accounts v2.9.1 (yes, I know, dirt old 🥲 )

**Comment by chaoscreater** [comment]
Same thing and we fixed it by updating AZ modules

**Comment by techlake** [comment]
Initial report is still valid. We'll stop intercepting the error and let azure bubble it to the user. It will be in the next version after 10.2.0, maybe named 10.2.1

**Comment by techlake** [comment]
Fixed in 10.2.1
