### ISSUE TITLE
EnterprisePolicyAsCode module - Check minimum required version of Az modules

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/enterprise-azure-policy-as-code#582]
**Is your feature request related to a problem? Please describe.**

Same example as #581

EnterprisePolicyAsCode could check what version of required Az modules is imported and see if they are recent enough.

**Describe the solution you'd like**

Add check for minimum required version of required Az modules.

**Describe alternatives you've considered**

None yet.

**Additional context**

#581

**Comment by anwather** [comment]
This has been added to the development environment and will be available in the next minor version

**Comment by o-l-a-v** [comment]
Where was this added? Seems it was added to the psd1, but then removed again, like here:

* <https://github.com/Azure/enterprise-azure-policy-as-code/commit/63a8fcd20be8381de73da2eb930a0ba5bd078bad>

It would be good if the issue remained open until a version with this feature actually has been published.

**Comment by anwather** [comment]
It caused the build process to fail so we had to revert the changes. Will fix next week.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by o-l-a-v** [comment]
Ok. For inspiration: AzOps does it in psd1 too, but with RequiredVersion instead:

* <https://www.powershellgallery.com/packages/AzOps/2.6.2/Content/AzOps.psd1>

While Az.Resources does it in ps1m:

* <https://www.powershellgallery.com/packages/Az.Resources/6.16.1/Content/Az.Resources.psm1>

**Comment by o-l-a-v** [comment]
@anwather 

As the OP says, export policies failed with Az.Accounts v2.9.1. So I don't get why EPAC specifies that as a working minimum version in the psd1.
