### ISSUE TITLE
Question about the format of the policies

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure/enterprise-azure-policy-as-code#59]
Hello,
Since we are working mainly with data services (Synapse, Cosmos, Purview) etc. We re-use some policies published here:
https://github.com/Azure/data-management-zone/tree/main/infra/Policies/PolicyDefinitions/SqlManagedInstance

This is one of the repos from Azure Cloud Scale analytics.
The policies here are in a different format that the one in the starter kit. Is there an automated way to "translate" the format?
Thanks,
Miguel

**Comment by techlake** [comment]
I have never seen this format. I recommend that you write a translation script in PowerShell (preferred if you plan to contribute it) or Python. If you do so, we would appreciate you contributing into EPAC? 
Thanks,
Heinrich

**Comment by MiguelElGallo** [comment]
Hi,
Sure, we will a Python script hopefully in the next two weeks.
Cheers,
Miguel

**Comment by techlake** [comment]
How is this going? any progress?

**Comment by MiguelElGallo** [comment]
Hello,
Yes, for policies is working now. For policies sets seems more challenging. 
Let's see how it goes with the Policies set this week, and then we will let you know.
Cheers,
