### ISSUE TITLE
GitHub action to run tests on PR

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/enterprise-azure-policy-as-code#592]
**Is your feature request related to a problem? Please describe.**

Increase quality of contributions and decrease chance of introducing regressions by creating automation for testing various things on PRs that must pass before merge in to main.

**Describe the solution you'd like**

Example of things to do:

* Insert dummy version number into psd1
* Run build
* Try to import and use the module from build artifact
  * Pester tests?
* Linting rules with PSScriptAnalyzer?

Example GitHub actions:

* Scoop: <https://github.com/ScoopInstaller/Extras/blob/master/.github/workflows/pull_request.yml>
  * Uses: <https://github.com/ScoopInstaller/GithubActions>
* PSResourceGet: <https://github.com/PowerShell/PSResourceGet/blob/master/.github/workflows/codeql-analysis.yml>

Other inspiration:

* <https://github.com/PSModule/Process-PSModule>

**Describe alternatives you've considered**

None yet.

**Additional context**

* <https://github.com/Azure/enterprise-azure-policy-as-code?tab=readme-ov-file#contributing>
* 2024-04-27: <https://github.com/Azure/enterprise-azure-policy-as-code/pull/591>
* 2024-04-26: <https://github.com/Azure/enterprise-azure-policy-as-code/actions/runs/8850190182>
* 2023-06-29: <https://github.com/Azure/enterprise-azure-policy-as-code/issues/277>

AB#44048

**Comment by apybar** [comment]
Adding to backlog

**Comment by anwather** [comment]
Closing as discussed with dev team - regression testing has been added to our internal ADO repo which has improved the quality of releases.
