### ISSUE TITLE
Latest Az.ResourceGraph (0.13.1) breaks all versions of EPAC: **FIXED in v10.1.11 and later**

### ISSUE THREAD

**Issue by techlake** [Azure/enterprise-azure-policy-as-code#598]
**Describe the bug**
0.13.1 was realeases on 4/29/2024.
It is unclear what kind of pipelines/workflows fail

AB#44046

**Comment by techlake** [comment]
Fix using REST call instead is in the works. ETA 1 day.

**Comment by apybar** [comment]
Adding to backlog

**Comment by anwather** [comment]
Closing due to multiple releases this is no longer an issue.
