### ISSUE TITLE
Failure running Build-ScopeTableForDeploymentRootScope.ps1

### ISSUE THREAD

**Issue by KennethBess** [Azure/enterprise-azure-policy-as-code#604]
**Describe the bug**
When the pipeline run Plan Prod (release flow) we get the below error (Plan nonprod is working fine)

===================================================================================================
Get scope tree for EPAC environment 'prod' at root scope /managementGroups/EMEA.prod
===================================================================================================
Write-Error: /home/vsts/.local/share/powershell/Modules/EnterprisePolicyAsCode/10.2.0/internal/functions/Build-ScopeTableForDeploymentRootScope.ps1:39
Line |
  39 |      $resourceGroups = Search-AzGraphAllItems `
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~
     | Search-AzGraph REST error for '' 403 -- {   "error": {     "code":
     | "AccessDenied",     "message": "Please provide below info when asking
     | for support: timestamp = 2024-05-01T15:41:35.9464438Z, correlationId =
     | 25135f3c-eb53-4b7e-8018-0b151ac1c954.",     "details": [       {        
     | "code": "AccessDenied",         "message": "Access is denied to the
     | requested resource. The user might not have enough permission."       } 
     | ]   } }

##[error]PowerShell exited with code '1'.

**Screenshots**
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/27630182/a82230fa-a553-4d12-a4d3-dd3884f9e91a)

**EPAC Version**
Version of EPAC module is 10.2.0.

**Comment by techlake** [comment]
The error message seems to indicate a missing RBAC role for the service connection. I have this code running in multiple environments. Azure directly generates this error, EPAC simply displays it.

**Comment by KennethBess** [comment]
> The error message seems to indicate a missing RBAC role for the service connection. I have this code running in multiple environments. Azure directly generates this error, EPAC simply displays it.

Yes, you are absolutely right. It is fixed
