### ISSUE TITLE
Policy definitions no longer found when assigning exemptions

### ISSUE THREAD

**Issue by arrerezai** [Azure/enterprise-azure-policy-as-code#611]
**Describe the bug**
Moving to Epac v10.2.2 introduces a new issue with policy exemptions. While the json files previously created work well with older Epac v10+ versions, this is no longer the case with v10.2.2.

**To Reproduce**
all-exemptions.jsonc:
`{
    "$schema": "https://raw.githubusercontent.com/Azure/enterprise-azure-policy-as-code/main/Schemas/policy-exemption-schema.json",
    "exemptions": [
        {
            "name": "<guid>",
            "displayName": "<name>",
            "description": "<description>",
            "exemptionCategory": "<category>",
            "expiresOn": "",
            "scopes": [
                "<scope>"
            ],
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/0b60c0b2-2dc2-4e1c-b5c9-abbed971de53"
        },
        {
            "name": "<guid>",
            "displayName": "<name>",
            "description": "<description>",
            "exemptionCategory": "<category>",
            "expiresOn": "",
            "scopes": [
                "<scope>"
            ],
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e66c121-a66a-4b1f-9b83-0fd99bf0fc2d"
        }
    ]
}`

**Expected behavior**
Assign exemptions if not present, keep them if previously assigned.
Confirmed that the policy does exist and on the appropriate scope, so the code shouldn't be throwing out a warning message, skipping the row. Nor should it delete the already assigned exemptions as can be seen in the screenshot below.

**Screenshots**
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/157028889/2e2ec43c-eb71-465e-ba07-8a1e32680fd4)

**EPAC Version**
Epac v10.2.2.

**Comment by techlake** [comment]
I'll fix this shortly
