### ISSUE TITLE
Existing ADO pipeline breaks due to authorization error at the plan stage

### ISSUE THREAD

**Issue by jennybeate** [Azure/enterprise-azure-policy-as-code#621]
I have been using the same service principal for several months without problem. Last time it ran successfully was april 18th. It has the custom EPAC Resource policy resource role and it has not been any changes made to its access at the root, which I have validated. Now, at the plan-stage, I am getting this error: 

_The client 'xx' with object id 'yy' does not have authorization to perform action 'Microsoft.Management/register/action' over scope '/_subscriptions/zzz or the scope is invalid. If access was recently granted, please refresh your credentials.__

**EPAC Version**
Latest, v10.2.5

**Comment by anwather** [comment]
Can you please post which actions you have specified in your custom role - so I can try and replicate?
