### ISSUE TITLE
Outdated Policy-Exemption Schema

### ISSUE THREAD

**Issue by apybar** [Azure/enterprise-azure-policy-as-code#637]
Review and update the schema to reflect EPAC v10+. For instance, policyId and policyName are not correct values as they are called policyDefinitionId and policyDefinitionName

**Comment by anwather** [comment]
@apybar any update on when this will be implemented?

**Comment by apybar** [comment]
@anwather  - This was pending a PR that was completed last week. This issue is now closed, and schema is updated as of v10.3.0.
