### ISSUE TITLE
Question about additionalRoleAssignments structure

### ISSUE THREAD

**Issue by alkozajac** [Azure/enterprise-azure-policy-as-code#64]
Hello,

I am trying to deploy policy with  additionalRoleAssignments, which requires roleDefinitionId and scope. Unfortunately, do not know why the assignment of additional roles does not work. Assigment applies to custom policy, could I ask for guidance on what the correct definition should look like.
Below is my definition of assignment, The policy works correctly but the additional role no longer. 
I will mention that I have one tenant. 

`
{

    "nodeName": "/7-DN-VMS-DeployRhelDscExtension/",
    "assignment": {
        "name": "7-DN-VMS-DeployRhelDscExtension",
        "displayName": "7-DN-VMS-DeployRhelDscExtension",
        "description": "Deploy DSC configuration for RHEL servers."
    },
    "definitionEntry": {
        "policyName": "7-DN-VMS-DeployRhelDscExtension",
        "friendlyNameToDocumentIfGuid": "7-DN-VMS-DeployRhelDscExtension"
    },
    "parameters": {
        "automationAccountSubscriptionId": "xxxxxxxxxxxxxxxx",
        "automationAccountRg": "scb-core-mgt-devdlp-rg",
        "automationAccountName": "scb-core-mgt-devdlp-aac",
        "nodeConfigurationName": "DSCforRHEL.localhost"
    },
    "scope": {
        "dev": [
            "/subscriptions/xxxxxxxxxxxxxxxxxxxxxx"
        ]
    },
    "additionalRoleAssignments": [
        {
            "roleDefinitionId": "/providers/microsoft.authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
            "scope": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxx"
        }
    ]
}
`
thanks in advance for your answer,
Aleksander

**Comment by techlake** [comment]
You do not need this unless a part of the remediation is in a different hierarchy. For example setting diagnostic settings and the Log Analytics Workspace is in a different subscription.

Assuming your policy is DeployIfNotExists, it should list the role definition id in the Policy detail section will be enabled.


Heinrich Gantenbein

From: alkozajac ***@***.***>
Sent: Wednesday, August 31, 2022 9:47 AM
To: Azure/enterprise-azure-policy-as-code ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/enterprise-azure-policy-as-code] Question about additionalRoleAssignments structure (Issue #64)


Hello,

I am trying to deploy policy with additionalRoleAssignments, which requires roleDefinitionId and scope. Unfortunately, do not know why the assignment of additional roles does not work. Assigment applies to custom policy, could I ask for guidance on what the correct definition should look like.
Below is my definition of assignment, The policy works correctly but the additional role no longer.
I will mention that I have one tenant.

`
{

"nodeName": "/7-DN-VMS-DeployRhelDscExtension/",

"assignment": {

    "name": "7-DN-VMS-DeployRhelDscExtension",

    "displayName": "7-DN-VMS-DeployRhelDscExtension",

    "description": "Deploy DSC configuration for RHEL servers."

},

"definitionEntry": {

    "policyName": "7-DN-VMS-DeployRhelDscExtension",

    "friendlyNameToDocumentIfGuid": "7-DN-VMS-DeployRhelDscExtension"

},

"parameters": {

    "automationAccountSubscriptionId": "xxxxxxxxxxxxxxxx",

    "automationAccountRg": "scb-core-mgt-devdlp-rg",

    "automationAccountName": "scb-core-mgt-devdlp-aac",

    "nodeConfigurationName": "DSCforRHEL.localhost"

},

"scope": {

    "dev": [

        "/subscriptions/xxxxxxxxxxxxxxxxxxxxxx"

    ]

},

"additionalRoleAssignments": [

    {

        "roleDefinitionId": "/providers/microsoft.authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",

        "scope": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxx"

    }

]

}
`
thanks in advance for your answer,
Aleksander

-

**Comment by alkozajac** [comment]
yes, policy has mode DeployIfNotExist and assigns dsc configuration from automation account which is in other subscription (hierarchy) - as you described in the example.
To clarify - the policy works in subscription A where policy service principal is assigned the role "Virtual Machine Contributor" (this part works for me), in addition, it must also use the automation account that is in subscription B. On subscription B or RG (from subscription B) i want to assign the Contributor role or sth like that.

below is part of the policy code:
`            

"then": {
                "effect": "deployIfNotExists",
                "details": {
                    "type": "Microsoft.Compute/virtualMachines/extensions",
                    "roleDefinitionIds": [
                        "/providers/microsoft.authorization/roleDefinitions/9980e02c-c2be-4d73-94e8-173b1dc7cf3c"
                    ],
                    "existenceCondition": {
                        "allOf": [
                            {
                                "field": "Microsoft.Compute/virtualMachines/extensions/publisher",
                                "equals": "Microsoft.OSTCExtensions"
                            },
                            {
                                "field": "Microsoft.Compute/virtualMachines/extensions/type",
                                "equals": "Microsoft.OSTCExtensions.DSCForLinux"
                            },
                            {
                                "field": "Microsoft.Compute/virtualMachines/extensions/provisioningState",
                                "equals": "Succeeded"
                            },
                            {
                                "field": "name",
                                "equals": "DSCForLinux"
                            }
                        ]
                    },`

**Comment by techlake** [comment]
For additionalRoleDefinition, the pipeline must have user administrator in that scope (or inherited at that scope). I hope this helps. Sorry for the long wait.

**Comment by techlake** [comment]
Do you get an error message. I'm suspecting that the identity running the deployment pipeline stage does not have permissions to do role assignments in the other subscription.


Heinrich Gantenbein
