### ISSUE TITLE
Sudden issues with 'Code bug: Our root is not in this tree'

### ISSUE THREAD

**Issue by donk-msft** [Azure/enterprise-azure-policy-as-code#644]
**Describe the bug**
This morning the allJob | Plan job started failing with the following error:

Get-AzScopeTree: /home/vsts/work/1/s/Scripts/Deploy/Build-DeploymentPlans.ps1:104
Line |
 104 |      $scopeTable = Get-AzScopeTree -PacEnvironment $pacEnvironment
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Code bug: Our root is not in this tree
##[error]PowerShell exited with code '1'.

Last time the pipeline ran successfully was yesterday. Today it fails repeatedly, running from new branch or main. No changes in MG structure or role assignments.

**To Reproduce**
Run pipeline

**Expected behavior**
allJob | Plan and planJob | Plan jobs succeeded.

**Screenshots**
Expected Output (output from yesterday):
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/17045753/b5bab7ed-68b3-4049-a3da-f918d6f89cdf)

Current output:
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/17045753/77f9f43c-ab51-43fb-9c9d-51cbfbc30bca)

With switch 'Ignore scope tree errors'
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/17045753/1912e0d0-5e68-474a-92b7-db7842095063)

But then fails in the Plan job for Production:
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/17045753/cb0f56c9-842e-4fd6-a070-54d3b3fdf301)

What stands out to me is that it now only reports 7 Management Groups while there are 10.

**EPAC Version**
Version of EPAC module you are using.
9.2.4

**Comment by donk-msft** [comment]
I get the same error when running the EPAC 'Create-AzRemediationTasks.ps1' script:

![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/17045753/f3574613-32bf-4edc-a037-4c3208fa1a08)

**Comment by anwather** [comment]
Can you please update to the latest version and try again?

**Comment by donk-msft** [comment]
@anwather, I could consider an upgrade, but could you clarify what changes in the latest version would address this issue? Since the problem also occurs when using the operational 'Create-AzRemediationTasks.ps1' script, I think it's unlikely that an upgrade alone will resolve it.

**Comment by anwather** [comment]
There will be changes to the Get-AzScopeTree function in a new version however the management group provider in Azure was extra flaky late last week so I would try running again and see if it was a transient issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by donk-msft** [comment]
@anwather - I re-ran the pipelines this morning and seems indeed that it was a transient issue. I heard about the management group provider issues, but I guess I was too early to retry before. Thanks!
