### ISSUE TITLE
Build-DeploymentPlans fails in workflow because az.login is using an earlier version of Az.Accounts

### ISSUE THREAD

**Issue by Jonatan-Bradley** [Azure/enterprise-azure-policy-as-code#645]
**Describe the bug**
The bug is related to https://github.com/Azure/login/issues/447 which effects the EPAC workflows. The Enterprise Policy-as-Code module relies on newer versions of the Az module as a whole, and any downgrading of az.accounts will effect the remaining workflow.

**To Reproduce**
Run the epac-dev-workflow.yml workflow and the plan job will fail.

**Expected behavior**
Build-DeploymentPlans module would run without Az.Accounts version 3.0.0 error

**Screenshots**
![build-deploymentplans](https://github.com/Azure/enterprise-azure-policy-as-code/assets/134266534/fceb2c8d-c30a-473a-975e-40cd393e6655)

![downgrading](https://github.com/Azure/enterprise-azure-policy-as-code/assets/134266534/313e888a-4a18-418a-a4ca-535e2ab14cef)

**EPAC Version**
Version of EPAC module you are using.
EnterprisePolicyAsCode 10.2.11

**Comment by anwather** [comment]
Did you try running with the ```uses: azure/login@hf_447_release``` release?

**Comment by Jonatan-Bradley** [comment]
I did try and run into the same issue where later steps relies on Az.Accounts version 3.0.0 and the workflow breaks. The Azure login job will work but not the plan job after.

**Comment by anwather** [comment]
I can bump the required version of Az.Accounts to 3.0.0 in the module - would that solve the problem do you think?

**Comment by anwather** [comment]
The other thing I need to check is if we even still required the Az.ResourceGraph module (which is causing all of these issues with versions)

**Comment by Jonatan-Bradley** [comment]
Isn't the requirement of version Az.Accounts 3.0.0 in the module what's causing the issue? Since the specific error is:

     | The 'Build-DeploymentPlans' command was found in the module
     | 'EnterprisePolicyAsCode', but the module could not be loaded due to the
     | following error: [The running command stopped because the preference
     | variable "ErrorActionPreference" or common parameter is set to Stop:
     | This module requires Az.Accounts version 3.0.0. An earlier version of
     | Az.Accounts is imported in the current PowerShell session. Please open a
     | new session before importing this module. This error could indicate that
     | multiple incompatible versions of the Azure PowerShell cmdlets are
     | installed on your system. Please see https://aka.ms/azps-version-error
     | for troubleshooting information.] For more information, run
     | 'Import-Module EnterprisePolicyAsCode'.
     
   Sorry if my interpretation is off here

**Comment by anwather** [comment]
I just checked the code, we don't need to use the resource graph module which also forced a newer version of Az.Accounts - give me 30 mins I'll remove all the required modules and then we'll see what hapoens

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
@Jonatan-Bradley - can you please test again for me?

**Comment by anwather** [comment]
Ensure if you have steps in the workflow that install the Az.ResourceGraph module you remove them as well.

**Comment by Jonatan-Bradley** [comment]
That did the trick! Thank you for the quick response and solution, much appreciated!
