### ISSUE TITLE
Sync-ALZPolicies outdated Assignment files

### ISSUE THREAD

**Issue by jbarrancos** [Azure/enterprise-azure-policy-as-code#659]
**Describe the bug**

The June updates are not synced into the assignments within this repository. This will result in assignment errors as AMA en AUM policies have been removed: https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#-ama-updates. I also get the impression that the May updates also have not been processed.

**To Reproduce**
Do a new Sync-ALZPolicies and do a Build-DeploymentPlans. Will result in errors.

**Expected behavior**
Up to date assignments.

**EPAC Version**

EnterprisePolicyAsCode\10.3.0

**Comment by jbarrancos** [comment]
Fixed in 10.3.1. More less a feature to sync up with Enterprise Scale changes

**Comment by anwather** [comment]
I've updated them again just today - am waiting on the PR to be approved internally and will be available in the next version.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
