### ISSUE TITLE
groupNames missing when exporting existing initiatives

### ISSUE THREAD

**Issue by flaviomeyer** [Azure/enterprise-azure-policy-as-code#664]
**Describe the bug**
When the existing Azure policies/initiatives are exported using **Export-AzPolicyResources**, the groupNames under policyDefinitions are not added to the output .jsonc file.

This results in an error during deployment, e.g. 
`PolicyDefinitionGroup
     | 'PCI_DSS_v4.0_1.1.1' not found in policyDefinitionGroups.`

**To Reproduce**
1. Duplicate a built-in initiative like **PCI DSS v4**
2. Export custom initiative with **Export-AzPolicyResources**
3. Copy Output *.jsonc to _Definitions/PolicySetDefinitions/Regulatory Compliance_
4. Plan and deploy via Azure DevOps or GitHub Actions
5. Plan fails with following error: `PolicyDefinitionGroup
     | 'PCI_DSS_v4.0_1.1.1' not found in policyDefinitionGroups.`

**Expected behavior**
Export of **groupNames** in **policyDefinitions** section

**Screenshots**

![Screenshot 2024-06-12 at 07 19 59](https://github.com/Azure/enterprise-azure-policy-as-code/assets/28959963/03a1990c-1176-4491-919a-c1cda69c6628)

![Screenshot 2024-06-12 at 07 21 03](https://github.com/Azure/enterprise-azure-policy-as-code/assets/28959963/adcd51f6-e420-467d-8a30-bf2b36a38c68)

**EPAC Version**
Latest -> 10.3.2

**Comment by anwather** [comment]
Thanks for finding this - I've got a PR raised - should be fixed in new version tomorrow

**Comment by flaviomeyer** [comment]
> Thanks for finding this - I've got a PR raised - should be fixed in new version tomorrow

Thank you for being able to look at the bug so quickly, including the fix via PR. I will be happy to test the new version tomorrow. 🚀
