### ISSUE TITLE
Support for Snowflakev2 policy parameter using builtin assignment ADF_allowed_linked_service_resource_types

### ISSUE THREAD

**Issue by luca-gervasi-od** [Azure/enterprise-azure-policy-as-code#668]
**Describe the bug**
We are trying to inject the new linked service connector "SnowflakeV2" to our assignment policy and getting invalid parameter.

**To Reproduce**
1. Add SnowflakeV2 connector to allowedLinkedServiceResourceTypes inside builtin/Data Factory/ADF_allowed_linked_service_resource_types.jsonc

**Expected behavior**
We expected the new connector to be supported assignment parameter to allow usage of SnowflakeV2.

**Screenshots**
\"SnowflakeV2\"\r\n]' is not allowed
     | for policy parameter 'allowedLinkedServiceResourceTypes' in policy
     | definition '6809a3d0-d354-42fb-b955-783d207c62a8'.

**EPAC Version**
ModuleVersion     = '7.0'

**Comment by anwather** [comment]
The SnowflakeV2 isn't an allowed parameter value - you could clone the policy and add it yourself. I'll try and find out the process for getting it updated as well.

**Comment by anwather** [comment]
Raise an issue here please https://github.com/Azure/azure-policy/issues
