### ISSUE TITLE
policyGroupName logic is reversed

### ISSUE THREAD

**Issue by luke-iseger91** [Azure/enterprise-azure-policy-as-code#676]
**Describe the bug**
If you define a policyGroupName in a policyset, but never use it in one of the policyDefinitions in the set, EPAC throws an error that the policyDefinitionGroup is not found. This is likely caused by a change in v10.3.2, which added an extra error check in Build-PolicySetPlan.ps1. 

I think the logic here needs to be slightly reversed. Rather then checking if `$usedPolicyGroupDefinitions.ContainsKey($groupName)`, where `$groupName` comes from the loop on `$policyDefinitionGroups` . It should be something like `$policyDefinitionGroups.ContainsKey($groupName)` where `$groupName` comes from the loop on `$usedPolicyGroupDefinitions`.

**To Reproduce**
- Create a policy set with various policyDefinitionsGroups defined
- Do not use one of the groups in the policyDefinitions in the set.
- Try to deploy the policySet

**Expected behavior**
The set should deploy. Empty groups are allowed in Azure.

**Screenshots**
![epac-groups](https://github.com/Azure/enterprise-azure-policy-as-code/assets/56301438/0e8dea96-ed2a-4fa3-bb55-3c813ab5ae79)

**EPAC Version**
V10.3.2 and above

**Comment by anwather** [comment]
Thanks - I've got a PR open for this - should be fixed tomorrow.

**Comment by flaviomeyer** [comment]
Thanks @luke-iseger91 I have just encountered the same problem.

Thanks for the quick fix @anwather

**Comment by anwather** [comment]
The PR is in our development environment waiting approval should be published tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
