### ISSUE TITLE
Get Existing AzureChinaCloud Exemptions not Returning Non-Management Group Scoped Exemptions

### ISSUE THREAD

**Issue by ahsulli** [Azure/enterprise-azure-policy-as-code#691]
**Describe the bug**
When getting existing exemptions within an AzureChinaCloud tenant, only management group level exemptions are included in the final returned list of existing exemptions.

**To Reproduce**
1. Run an Export-AzPolicyResources or Build-DeploymentPlans using a pacSelector whose type is AzureChinaCloud.

**Expected behavior**
All exemptions scoped to management groups, subscriptions, resource groups, and individual resources within the specified pacSelector configuration should be included in the list of existing exemptions that are factored into the final output.

**Screenshots**
N/A

**EPAC Version**
10.3.5

**Comment by anwather** [comment]
Closing as issue is defined in #692

**Comment by ahsulli** [comment]
@anwather, just to further clarify, you can also reproduce this issue by running Build-DeploymentPlans as well. However, this version of the repro steps produces an erroneous output that is less obvious to see but is still flawed for the same reason.

**Comment by ahsulli** [comment]
@anwather, issue is still present. Please fix. Cannot run deployment plans against China tenants as a result.

**Comment by anwather** [comment]
OK you mentioned you had code to fix this can you please submit a PR. I don't have access to a China tenant to run this against.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ahsulli** [comment]
@anwather, can someone please grant me access to create a branch and PR? I have the code already prepared on my local. The code has been successfully tested numerous times against my organization's China and Commercial tenants. Hopefully that helps too.

**Comment by anwather** [comment]
Just fork the repo, create a branch on the fork, make changes and create a pull request please.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ahsulli** [comment]
@anwather, I have created PR: https://github.com/Azure/enterprise-azure-policy-as-code/pull/702
