### ISSUE TITLE
EPAC Plan Taking 15min to run

### ISSUE THREAD

**Issue by tonydean37** [Azure/enterprise-azure-policy-as-code#697]
**Describe the bug**
We are finding that our EPAC plan is taking around 15min to run, which used to take around 2-5mins. It hangs on this section, which only has around 30 assignment files in the dev environment. This seemed to start when we downloaded the latest version of EPAC:

Processing Policy Assignments JSON files in folder './Definitions/policyAssignments'
Number of Policy Assignment files = 30

**To Reproduce**
This happens every time

**Expected behavior**
I'd like to understand why the plan is taking so much longer than it used too.

**Screenshots**
NA

**EPAC Version**
The latest version.

**Comment by anwather** [comment]
I'll push a fix for this shortly
