### ISSUE TITLE
Duplicate exemption Id

### ISSUE THREAD

**Issue by AzureStackNerd** [Azure/enterprise-azure-policy-as-code#700]
I am not sure if this is a bug, feature request or because the prerequisites are unclear in the documentation.

**Describe the bug**
File '/home/vsts/work/1/Definitions/policyExemptions/epac-dev/all-exemptions01.json' has 1 errors:
    0: Duplicate Exemption id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/providers/Microsoft.Authorization/policyExemptions/<policyexemptionname>' for name '<policyexemptionname>'.

**To Reproduce**
I noticed that this happens when the policyExemption is made with 
- _policySetDefinitionName_ or
- _policySetDefinitionId_

WITH 
the use of _PolicyDefinitionReferenceId_ 

AND
The policySet is assigned to the same scope (azure management group) twice with different policyEffects.

**Expected behavior**
I expected EPAC to create the exemption twice. One for each policyAssignmentIds. In which case the exemptionId could be an autogenerated guid, or the exemptionId name with an increment.

**EPAC Version**
**ModuleType Version    PreRelease Name**
Script     10.4.2                EnterprisePolicyAsCode

**Comment by anwather** [comment]
If you make the exemption names unique it works?

**Comment by AzureStackNerd** [comment]
This is what I think is happening:
There is 1 exemption (with a unique name) in the JSON-file, referred by policySetDefinitionName and policyDefinitionReferenceId. EPAC figures out which policyAssignmentId it should take for creating the exemption, but cannot. Since there are 2 assignments, it cannot create 2 exemptions based on 1 unique exemption name.

How can I create a unique exemption name in this scenario?

**Comment by anwather** [comment]
Are you able the share the exemption file so I can take a look at the structure?

Or email it to ***@***.***?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AzureStackNerd** [comment]
`{
  "$schema": "https://raw.githubusercontent.com/Azure/enterprise-azure-policy-as-code/main/Schemas/policy-exemption-schema.json",
  "exemptions": [
    // DOES NOT WORK Is trying to create 2 exemptions because there are 2 policy Assignments with different effects
    {
      "name": "3bc74b9b-91d5-4b47-bc66-574321e4322f",
      "displayName": "logging-oms-workspace",
      "description": "logging-oms-workspace description",
      "exemptionCategory": "Mitigated",
      "scope": "/subscriptions/95e44270-1e24-48f3-b4b2-34a8e7fbf558/resourceGroups/rg-test-resources-d",
      "expiresOn": null,
      "policySetDefinitionName": "diaglogs-la-initiative",
      "policyDefinitionReferenceIds": [
        "LALAAGENTWINDOWS"
      ]
    },
    // WORKS
    {
      "name": "62c963c1-00f4-4555-92c3-1dfc9d7207fc",
      "displayName": "security-center-pricing-policy via policyset",
      "description": "security-center-pricings via policyset description",
      "exemptionCategory": "Mitigated",
      "scope": "/subscriptions/95e44270-1e24-48f3-b4b2-34a8e7fbf558/resourceGroups/rg-test-resources-d",
      "expiresOn": null,
      "policySetDefinitionName": "mg-asc-settings-initiative",
      "policyDefinitionReferenceIds": [
        "ascstorage"
      ]
    }
  ]
}`

**Comment by anwather** [comment]
I wonder if you will have to use [this](https://azure.github.io/enterprise-azure-policy-as-code/policy-exemptions/#option-b-policy-assignment-id) method to assign the exemption - as it is getting confused because it doesn't know which assignment to look up?

**Comment by AzureStackNerd** [comment]
Yeah. I was afraid you might say that. I will look into that way. We migrating our old management group structure to the enterprise scale one. We probably have to calculate the new policyAssignmentIds then.
