### ISSUE TITLE
Error building exemptions with Build-DeploymentPlans

### ISSUE THREAD

**Issue by P-M-Carroll** [Azure/enterprise-azure-policy-as-code#701]
**Describe the bug**
When running Build-DeploymentPlans receive error 
Get-CalculatedPolicyAssignmentsAndReferenceIds: ****\EnterprisePolicyAsCode\10.4.2\internal\functions\Build-ExemptionsPlan.ps1:51:26
Line |
  51 |              -Assignments $sortedAssignments `
     |                           ~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Assignments' because it is null.
WARNING: Row 2: policyAssignmentId '/providers/Microsoft.Management/managementGroups/mgmt-grp/providers/Microsoft.Authorization/policyAssignments/np-loc' not found in current root scope /providers/Microsoft.Management/managementGroups/-mgmt-grp, skipping row
WARNING: Row 3: policyAssignmentId '/providers/Microsoft.Management/managementGroups/mgmt-grp/providers/Microsoft.Authorization/policyAssignments/pr-loc' not found in current root scope /providers/Microsoft.Management/managementGroups/mgmt-grp, skipping row

Do not get error when running Build-DeploymentPlans -BuildExemptionsOnly

**To Reproduce**
Using CSV with following headers. 
name,displayName,description,exemptionCategory,expiresOn,status,expiresInDays,scope,assignmentReferenceId,policyDefinitionReferenceIds,resourceSelectors,metadata,assignmentScopeValidation

Run Build-DeploymentPlans recireve error

**Expected behavior**
Processing of exemption file csv to work as it does when running Build-DeploymentPlans -BuildExemptionsOnly

**Screenshots**
![image](https://github.com/Azure/enterprise-azure-policy-as-code/assets/49420107/7da1e7ba-dcf8-410a-9c9c-e8191ee8bb93)

**EPAC Version**
10.4.2

**Comment by anwather** [comment]
Are you using EPAC to manage assignments? It's a bit weird that ```$sortedAssignments``` would be null since it is built from the deployed managed assignments.

**Comment by P-M-Carroll** [comment]
Yes using it to deploy assignments and that works as expected when I don't have a csv file for exemptions.

**Comment by anwather** [comment]
OK that's a bit weird, I spoke to Ajay this morning about what you're trying to do - if you have time today we can catch up and have a look? Ping me on teams at anwather at Microsoft dot com.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
Issue resolved - incorrect pac environment
