### ISSUE TITLE
Failed exemption deployments do not throw errors

### ISSUE THREAD

**Issue by robsissons-contino** [Azure/enterprise-azure-policy-as-code#706]
**Describe the bug**
When deploying exemptions, if a scope is not found a warning is thrown rather than an error. This means a deploy pipeline will not fail so the end user has no visibility of the failure to deploy the exemption without reviewing the logs in detail.

**To Reproduce**

Perform a deployment with an exemption which has a typo/mis-spelled scope. 

(note - "skipResourceValidationForExemptions" is set to 'true' in global settings for the environment due to amount of exemptions in environment to speed up build time)

**Expected behavior**

I would expect that, if a resource (in this case an exemption) that was intended to be deployed and failed, the pipeline result would reflect the failure.

**Screenshots**
![fail_warning](https://github.com/user-attachments/assets/3401a577-ded7-45a4-a747-df6b555041ae)

Warning comes from the "Set-AzPolicyExemptionsRestMethod" function, line 42.

**EPAC Version**
10.3.1

**Comment by apybar** [comment]
I've assigned this to myself @robsissons-contino  - Looking into it.

**Comment by apybar** [comment]
Will be fixed in v10.5.1

**Comment by apybar** [comment]
Fixed in v10.5.1
