### ISSUE TITLE
Policy Set with single parameter used across multiple definitions causes error in Build-DeploymentPlans

### ISSUE THREAD

**Issue by brianmooremsft** [Azure/enterprise-azure-policy-as-code#714]
**Describe the bug**
When running Build-DeploymentPlans, post reading in currently deployed custom policies, a policy set with a single parameter used across many definitions within the policy set causes error [31;1mException calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'LOGSENABLED'  Key being added: 'LOGSENABLED'"

**To Reproduce**
[1e86036638424db598ba3c56.jsonc](https://github.com/user-attachments/files/16393911/1e86036638424db598ba3c56.jsonc)

**Expected behavior**
No error when running Build-DeploymentPlans

**Screenshots**

**EPAC Version**
Version of EPAC module you are using:  10.5.0

**Comment by apybar** [comment]
Fixed in v10.5.1
