### ISSUE TITLE
PacSelector on Install-HydrationEpac

### ISSUE THREAD

**Issue by EdersonSC** [Azure/enterprise-azure-policy-as-code#732]
**Describe the bug**
After using the Install-HydrationEpac command, the configuration for my environment starts and the connection test is successful. When I try to install my PacSelector, I get the following error:

Result Verified for variable dxc01, which will be used to identify the deployment to this Tenant.

Write-Error: C:\Users\ecelestrino2\OneDrive - DXC Production\Documents\PowerShell\Modules\EnterprisePolicyAsCode\10.5.6\functions\Install-HydrationEpac.ps1:65
Line |
65 | Write-Error $error[0].Exception.Message
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot bind argument to parameter 'Exception' because it is null.

############################################################################ Creating repo Definitions folder... Install-HydrationEpac: Unable to create global-settings file. This is likely a flaw in the choices made above that should have been caught in earlier tests. Please retain your answer file and report this to the EPAC team.
Copy-Item: C:\Users\ecelestrino2\OneDrive - DXC Production\Documents\PowerShell\Modules\EnterprisePolicyAsCode\10.5.6\functions\Install-HydrationEpac.ps1:103 Line |
 103 | Copy-Item $AnswerFilePath -Destination $errorPath | ~~~~~~~~~~~~~~~ | Cannot bind argument to parameter 'Path' because it is an empty string.

############################################################################ Creating Pipeline... Install-HydrationEpac: Invalid response. This is a bug. Check to see if a new valid type was added and the switch was not updated properly.
PS D:\workspace\Epac\DEV>

**To Reproduce**
Use the Install-HydrationEpac command, start configuration for an environment, the connection test will be successful. In the next step of placing the PacSelector you will receive an error.

**Expected behavior**
Cannot bind argument to parameter 'Exception' because it is null.

**Screenshots**

**EPAC Version**
10.5.6

**Comment by anwather** [comment]
@jeremiahhoward can you take a look at this please?

**Comment by jeremiahhoward** [comment]
Greetings! Would you be able to send me the answer file at jeremiah.howard@microsoft.com please @EdersonSC ? It looks there may have been an error writing the file though, so that may not be possible. Please let me know, thank you!

**Comment by EdersonSC** [comment]
Thanks and I sent the e-mail

**Comment by EdersonSC** [comment]
I don't know what they did, but it was fixed in version 10.5.7.
Thanks

**Comment by EdersonSC** [comment]
I don't know what they did, but it was fixed in version 10.5.7.
Thanks
