### ISSUE TITLE
Get-AzExemptions.ps1 output isn't in the same order

### ISSUE THREAD

**Issue by teemukom** [Azure/enterprise-azure-policy-as-code#748]
**Describe the bug**
When running Get-AzExemptions.ps1 both outputs (CSV/JSON) are returning the metadata segment in random order. This makes it difficult to use the script in CI/CD pipeline with pull requests because the output of this script is random although the contents of the file hasn't changed.

**To Reproduce**
Run Get-AzExemptions.ps1 couple of times and compare the metadata section between the files.

**Expected behavior**
In every run the content of the files (JSON/CSV) are in the same order.

**Screenshots**
![image](https://github.com/user-attachments/assets/7f423db3-261e-49d2-8107-2c6b94dd451a)

**EPAC Version**
10.5.9

**Comment by apybar** [comment]
@teemukom  - are you using Build-ExemptionsPlan.ps1 by any chance?

This is the only place within the code the "epacMetadata" gets created. I can update it so that it is ordered when it is created.

However, I am not seeing it specifically referenced in Get-AzExemptions.ps1

**Comment by apybar** [comment]
Just updated it so now the metadata and the epacMetadata are now in Alphabetical order in both the creation and the export of exemptions. Fix will be part of next release and I will close this ticket once release is published.

I tested and validated deploying and getting the exemptions with Get-AzExemptions.ps1 (screenshot below):

![image](https://github.com/user-attachments/assets/0794459e-3459-4a39-857d-c379ec7f037f)

**Comment by anwather** [comment]
Fixed in 10.6.0
