### ISSUE TITLE
SuppressDocumentation doesn't do anything because Export-AzPolicyResources doesn't document resources

### ISSUE THREAD

**Issue by mrwalters1988** [Azure/enterprise-azure-policy-as-code#756]
**Describe the bug**
Running Export-AzPolicyResources should generate documentation. It currently does not. 

**To Reproduce**
Run: 
Export-AzPolicyResources -OutputFolder ./outputTest -IncludeChildScopes -mode export -InputPacSelector "epac-main"

Then run: 
Export-AzPolicyResources -OutputFolder ./outputTest -IncludeChildScopes -mode export -InputPacSelector "epac-main" -SuppressDocumentation

The output will be identical. 
**Expected behavior**
Export-AzPolicyResources should generate documentation. 

**EPAC Version**
Version of EPAC module you are using.
10.6.0

**Comment by mrwalters1988** [comment]
@anwather any explanation as to why this is a wontfix? 

If this is something you're not fixing, should documentation be update to state that Export-AZPolicyResources doesn't document resources?

**Comment by anwather** [comment]
Hi I've got a PR pending to update this function and the documentation. Discussed and we don't believe that generating the documentation during an export is of any value. If required you can generate documentation as part of the normal process.
