### ISSUE TITLE
Out-DocumentationForPolicyAssignments does not generate split tables for Category documentation

### ISSUE THREAD

**Issue by mrwalters1988** [Azure/enterprise-azure-policy-as-code#757]
**Describe the bug**
When running Build-PolicyDocumentation, there is a feature that documents the resources under a documentAllAssignments config, it will generate policy documents for each category. It is meant to add two tables. The first table is the Policy Effects. The second table should be the policy parameters. 

It applies both, but combines them as a single table, making it rather difficult to parse through.  

**To Reproduce**

Run Build-PolicyDocumentation using documentAllAssignments config

**Expected behavior**

There should be an additional markdown header and table header segment added to the markdown. 
This looks like it should be implemented in the code for out-DocumentationForPolicyAssignments at line 448. 

**Screenshots**
![image](https://github.com/user-attachments/assets/7e95426b-6a25-445d-a7bd-5564569f3c67)

**EPAC Version**
10.6.0

**Comment by anwather** [comment]
@apybar - is this one you can take a look at please?

**Comment by apybar** [comment]
@mrwalters1988 - Fixed. Default moving forward there will be an additional markdown header and table header segment added to the markdown.

Will be available in 10.6.1 - I will close this issue upon the release.

**Comment by mrwalters1988** [comment]
@apybar can you point me to a commit or branch to update the code locally in the meantime?

**Comment by anwather** [comment]
I will push out the new version hopefully in the next hour
