### ISSUE TITLE
Excluded Scopes Not Working as Expected

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#769]
**Describe the bug**
Reopen https://github.com/Azure/enterprise-azure-policy-as-code/issues/425. Testing with
```
"excludeSubscriptions": true
```
is not working as expected. Tried the flag within desiredState and also at other levels in JSON and unmanaged subscription assignments were deleted in the plan. 

The code in the merge request does not seem to process this flag. 

**To Reproduce**
Add "excludeSubscriptions": true to desiredState. create unmanaged policy assigning in a subscription, examine policy plan to check if assignment will be deleted. 

**Expected behavior**
Unmanaged subscription policy assignments should not be deleted. 

**Screenshots**

**EPAC Version**
10.0.0

**Comment by anwather** [comment]
That flag doesn't appear in the code anywhere. You can use ```excludedScopes```. I have tested in 10.6 by deploying an assignment to a subscription and using desired settings as below.
```
"desiredState": {
                "strategy": "full",
                "keepDfcSecurityAssignments": true,
                "excludedScopes": [
                    "/subscriptions/01e2f327-74ac-451e-8ad9-1f923a06d634"
                ]
            }
```
The output from the plan was as follows:
```
Output plan(s); if any, will be written to the following file(s):
    Skipping Policy deployment stage/step - no changes
    Skipping Role Assignment stage/step - no changes
```

**Comment by anwather** [comment]
Ok - could you just set the desiredState to ownedOnly?

**Comment by glsutter** [comment]
Sure, that was our workaround. But that won't remove old policies and assignments we have at MG scope. It ignores EVERYTHING that's unmanaged, not just what's at subscription scope. Not really the same thing.

**Comment by anwather** [comment]
No problems, will look at implementing as Heinrich suggested.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
Can you please test the code in the branch ```feature/aw/issue769``` and see if this resolves the issue? You can now add ```excludeSubscriptions: true``` to ```global-settings.jsonc```

**Comment by glsutter** [comment]
Hi, Anthony. We have the EPAC code in a Gitlab monorepo. Not Github. I really can't test a single branch very easily. And we're back on v10.0.0. There are probably other changes needed that were made after that release. 

I tried to identify what Scripts had changed and updated our repo. But that didn't seem to work. I updated in our monorepo:
Scripts/Helpers/RestMethods/Get-AzManagementGroupRestMethod.ps1
Scripts/Helpers/Build-ScopeTableForDeploymentRootScope.ps1
Scripts/Helpers/Build-ScopeTableForManagementGroup.ps1
Scripts/Helpers/Get-GlobalSettings.ps1

I'm attaching the -Verbose output of Build-DeploymentPlans.ps1. Show some errors and unexpected changes. Looks like there's something I'm missing. Do I need to upgrade to latest release, then apply changes in feature/aw/issue769?

**Comment by glsutter** [comment]
[issue769-job-out.txt](https://github.com/user-attachments/files/17330130/issue769-job-out.txt)

**Comment by glsutter** [comment]
The output may have some sensitive information. Need to send to you securely. Or we can look at it in a Teams meeting.

**Comment by glsutter** [comment]
By the way, how can I identify the version I'm running if I'm using the main branch?

**Comment by anwather** [comment]
If you are using the main branch of this project it is the latest one. The branch I have created for you to test is based off that (currently v10.6.2). The easiest way for you to test this is:
1. Clone the project locally and switch to my branch
2. Add your Definitions folder into the local project (from your current running configuration)
3. Run ```scripts\deploy\Build-DeploymentPlans.ps1``` as you would do in your pipeline (you can just run locally connected to Azure with your own credential - need to have Reader over the management group)
4. Check the build plan to see if the subscriptions are ignored. 

You can email me or ping on teams at anwather @ microsoft dot com. Also I'm in Australia so timezone will be something to think about :)

**Comment by glsutter** [comment]
Okay, thanks Anthony. I will try that later today. My timezone, ha ha.

**Comment by glsutter** [comment]
Testing delayed due to project demands. Hoping to get to it today.

**Comment by glsutter** [comment]
Anthony - Tested with 

`      "desiredState": {
        "strategy": "full",
        "excludeSubscriptions": true
      },`

and EPAC did not delete subscription policy assignments. Seems to work as intended based on my preliminary testing. 

Should we just wait on the release that contains this new code? 

Thanks

**Comment by anwather** [comment]
I'll hopefully push out a release this week with another couple of changes we have in flight - will more than likely be version 10.6.3 - but keep an eye out for it.

**Comment by glsutter** [comment]
Anthony – Quick question, I think. Looks like exemptions at subscription scope are still being deleted when excludeSubscriptions flag is true. Can you confirm that flag works only for assignments, not exemptions?

Thanks
Geary

From: Anthony Watherston ***@***.***>
Reply-To: Azure/enterprise-azure-policy-as-code ***@***.***>
Date: Wednesday, October 16, 2024 at 4:55 PM
To: Azure/enterprise-azure-policy-as-code ***@***.***>
Cc: Undisclosed Recipients ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [Azure/enterprise-azure-policy-as-code] Excluded Scopes Not Working as Expected (Issue #769)

I'll hopefully push out a release this week with another couple of changes we have in flight - will more than likely be version 10. 6. 3 - but keep an eye out for it. — Reply to this email directly, view it on GitHub, or unsubscribe. You


I'll hopefully push out a release this week with another couple of changes we have in flight - will more than likely be version 10.6.3 - but keep an eye out for it.

**Comment by anwather** [comment]
It removes all subscriptions from the scope for evaluation - I haven't tested with exemptions specifically - I'll have to set up an environment and test the effect...
________________________________

**Comment by glsutter** [comment]
My early testing showed subscription scope exemptions being deleted with excludeSubscriptions set to true. Not a big issue for us since we want EPAC to manage all exemptions. But I just wanted you to be aware of the behavior.

Geary

From: Anthony Watherston ***@***.***>
Sent: Tuesday, November 5, 2024 4:44 PM
To: Azure/enterprise-azure-policy-as-code ***@***.***>
Cc: Geary L Sutterfield ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [Azure/enterprise-azure-policy-as-code] Excluded Scopes Not Working as Expected (Issue #769)

It removes all subscriptions from the scope for evaluation - I haven&#39;t tested with exemptions specifically - I&#39;ll have to set up an environment and test the effect. . . <br> ________________________________ <br> From:
