### ISSUE TITLE
globalNotScrops not working

### ISSUE THREAD

**Issue by thyme51** [Azure/enterprise-azure-policy-as-code#774]
We started out with 

      "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/MyCompany"

Then a new subscription was added for a truck load of arc enabled servers, which should have no policies right now at all. In order mo remove 100s of non-compliant resources, we took the short-cut: (instead of exempting each policy/policy set) for that subscription

Therefore we added "/subscriptions/sub-arc-p/*"

            "globalNotScopes": [
                "/subscriptions/*/resourceGroups/cloud-shell-storage*",
                "/subscriptions/sub-arc-p/*"
            ]

But this has no effect at all. I can add exemptions manually for that subscription scope for eacy policy which works fine.

What am I missing ?

Thanks
Jørgen

**Comment by anwather** [comment]
To exclude the subscription you should list it as ```/subscriptions/<<subscriptionId>>```. Don't need to put the asterisk at the end.
