### ISSUE TITLE
[v10.6.2] Install-HydrationEpac fails when scriptType set to script and pipelineType is GitHubActions

### ISSUE THREAD

**Issue by ewlidd** [Azure/enterprise-azure-policy-as-code#775]
**Describe the bug**
Install-HydrationEpac throws an error at the step where it copies pipeline files if you select script type, and also github actions.

Renaming StarterKit/Pipelines/GitHubActions/templates-ps1-use-scripts to templates-ps1-scripts fixes this issue.
I don't see any references to templates-ps1-use-scripts in the code. Only templates-ps1-scripts.

**To Reproduce**
Run Install-HydrationEpac and select Git Hub Actions as the pipeline type and script as the script type.

**Screenshots**
```
Copying starter kit  GitHub Actions workflows (GitHub-Flow) from './StarterKit/Pipelines/GitHubActions/GitHub-Flow/*.yml' to ./.github/workflows
Copying starter kit  GitHub Actions reusable workflows (use scripts) from './StarterKit/Pipelines/GitHubActions/templates-ps1-scripts/*.yml' to ./.github/workflows
Press Enter to continue: 
Install-HydrationEpac: Unable to create pipeline. Please rerun hydration and confirm the pipeline responses in the New-HydrationAnswerFile cmdlet interview.
```

**EPAC Version**
10.6.2

**Comment by jeremiahhoward** [comment]
I'll take a look at that as well, thank you!
