### ISSUE TITLE
[v10.6.2] Install-HydrationEpac contains incorrect paths on case sensitive filesystems

### ISSUE THREAD

**Issue by ewlidd** [Azure/enterprise-azure-policy-as-code#776]
**Describe the bug**
The hydration script refers to some paths in all-lowercase, where the foldernames are not.
References to hkDefinitions for example are incorrect with all lowercase "hkdefinitions".

**To Reproduce**
Run Install-HydrationEpac on a case sensitive filesystem

**Screenshots**
```
Get-Content: CENSORED/.local/share/powershell/Modules/EnterprisePolicyAsCode/10.6.2/functions/Install-HydrationEpac.ps1:149:24
Line |
 149 |  … ignment = $(Get-Content (Join-Path $StarterKit "hkdefinitions" "polic …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'CENSORED/StarterKit/hkdefinitions/policyAssignments/pci-dss4.jsonc' because it does not exist.
```

**EPAC Version**
10.6.2

**Comment by jeremiahhoward** [comment]
Good catch! I'll get this updated. Thank you!
