### ISSUE TITLE
PAT expired for action gh-issues-to-ado

### ISSUE THREAD

**Issue by sdecker** [Azure/enterprise-azure-policy-as-code#778]
**Describe the bug**
Any new issue or update on an issue triggers the action gh-issues-to-ado which fails because of an expired PAT. The user then receives a confusing email about a run failure. 

**To Reproduce**
Open a new issue or comment on an existing issue. 

**Expected behavior**
Users don't get action errors when they submit or comment on issues

**EPAC Version**
N/A GH action issue

**Comment by anwather** [comment]
@apybar - was this your workflow?

**Comment by anwather** [comment]
In the meantime I've disabled the workflow.
