### ISSUE TITLE
notScopes Verification

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#786]
I doubt if this is a bug. Maybe more of a question about how to verify notScopes. 

**To Reproduce**
I have an allowed locations initiative assigned at the intermediate root that allows CONUS locations.  In the JSON, I have a scope and notScopes:

	"parameters": {
		"AllowedLocations": [
			"centralus",
			"eastus",
			"eastus2",
			"global",
			"northcentralus",
			"southcentralus",
			"westcentralus",
			"westus",
			"westus2",
			"westus3"
		]
	},
	"children": [
		{
			"nodeName": "mac-test",
			"scope": {
				"mac-test": [
					"/providers/Microsoft.Management/managementGroups/TEST1"
				]
			},
			"notScopes": {
				"mac-test": [
					"/providers/Microsoft.Management/managementGroups/TEST1-ecis-aus"
				]
			}
		}
	]

I have an additional assignment of the allowed locations initiative at scope TEST1-ecis-aus that restricts the location to Australia East and global:

`	"parameters": {
		"AllowedLocations": [
			"australiaeast",
			"global"
		]
	},
	"children": [
		{
			"nodeName": "mac-test",
			"scope": {
				"mac-test": [
					"/providers/Microsoft.Management/managementGroups/TEST1-ecis-aus"
				]
			}
		}
	]`

**Expected behavior**
A way to verify the CONUS location restriction does not apply to the TEST-ecis-aus MG. The only way I can see to verify that's true is by trying to create a RG in TEST1-ecis-aus in a CONUS region. I do not see any EPAC output or console output that indicates the CONUS location assignment is not applied to the TEST-ecis-aus MG. Am I missing something? Is there a way to verify the assignment notScope other than testing? 

**Screenshots**
May be appllcable - Screen![Image](https://github.com/user-attachments/assets/01231edd-bf2f-4bbe-be3c-3d9d9b8fad5f)
shot of assignments to TEST1 and TEST-ecis-aus show both initiative assignments. No exemptions, of course. 

**EPAC Version**
Just upgraded to 10.7.0.

**Comment by apybar** [comment]
@glsutter - On the last screenshot you sent, click the name of the assignment that you have the notScope applied to and on the "Essentials" section at the top, there should be a property called "Excluded scopes". 

![Image](https://github.com/user-attachments/assets/c217178f-d24c-411a-8493-32e81533ccb3)

Let me know if that works for you please!

**Comment by glsutter** [comment]
Ah ha! That's where it is. Thanks for helping me find that. Never noticed it before. Probably because it's always empty.
