### ISSUE TITLE
[Feature enhancement] AMBA Services

### ISSUE THREAD

**Issue by riosengineer** [Azure/enterprise-azure-policy-as-code#788]
I have integrated the ALZ Pattern from AMBA to EPAC with the help of @anwather's export repo, which was a great and easy addition to EPAC for us. However, I would like to integrate other Azure services listed in their initiative like SQL, for example, to Azure Policy: https://azure.github.io/azure-monitor-baseline-alerts/services/Sql/servers/

I will continue to try and put together all the definitions and such, to try and make it work in EPAC but it seems quite a painful process currently. Therefore, I'm wondering:

1) if anyone has done this before, and if so, what was your process to streamline the work and;
2) if EPAC may consider some guidance/or process that would enable us to do this just like the export repo? 

E.g. I have ALZ Pattern deployed via EPAC - now I want to add more Azure Policy Definitions to `policyDefinitions` from https://azure.github.io/azure-monitor-baseline-alerts/services, then have an `setDefinitions` for these, and then we can customise/assign them within the `policyAssignments` folder (like `alerting-sql-policySet.jsonc` for example).

**Comment by anwather** [comment]
So I had a look at this and you are right they don't provide set definitions for many of those services.

This is something I would raise as a request in the AMBA repo, see if they can produce a set definition along with all the policy definitions...

**Comment by riosengineer** [comment]
> So I had a look at this and you are right they don't provide set definitions for many of those services.
> 
> This is something I would raise as a request in the AMBA repo, see if they can produce a set definition along with all the policy definitions...

Cheers, I will raise their end then to see where I can take this.
