### ISSUE TITLE
Missing AzureUSGovernment Built-in Policies

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#793]
This may not be a EPAC bug. More likely an Enterprise-Scale ALZ initiative issue or a problem with our AzureUSGovernment account. Opened a ticket in Enterprise-Scale but not getting a response after a week (https://github.com/Azure/Enterprise-Scale/issues/1806). Would like perspective of EPAC team since it's a blocker for using EPAC in our AzureUSGovernment account. 

Problem - Enterprise-Scale ALZ initiative definitions with alzCloudEnvironments that include AzureUSGovernment reference built-in policies that are not available in our AzureUSGovernment account. I am trying to determine if that is an issue with our account or an issue with how the ALZ initiatives are tested. 
- If ALZ initiatives are tested successfully in AzureUSGovernment, then it's probably an issue with our account not being updated. 
- Or it could be an issue with the Enterprise-Scale ALZ initiatives having incorrect alzCloudEnvironments metadata. 

**To Reproduce**
Not sure how this could be reproduced unless you have an AzureUSGovernment account that is missing some build-in polices. I don't know if this is a common problem or a one-off problem with our account. 

**Expected behavior**
When an ALZ initiative include AzureUSGovernment in its alzCloudEnvironments metadata, then the EPAC initiative definition should see successful in our Government account. 

**Screenshots**
Attached output from EPAC Build-DeploymentPlans in our AzureUSGovernment account. This is one of the first failures. Have rerun at least 8 times, deleting initiatives and built-in policy references. Not sure how many more deletions need to be made for a successful run. I suspect it might be dozens. This is not a desirable approach to getting the ALZ initiatives deployed. 

**EPAC Version**
10.7.0

**Comment by glsutter** [comment]
![Image](https://github.com/user-attachments/assets/c7d2eeab-7a0d-4e34-8d09-29b5d98e6087)

**Comment by anwather** [comment]
When you run `Sync-ALZPolicies` we download from the Enterprise-Scale repo - and depending on the `-cloud` parameter filter applicable policies to sovereign clouds. If the definitions which are targeted at `AzureUSGovernment` contain policies which are not available in that cloud then as you have mentioned it is up to Enterprise Scale team to test and fix. We don't manipulate or change anything from that source - we only provide EPAC formatted assignments in this project.
