### ISSUE TITLE
Extended documentation for Multi-Tenant Definitions folder structure

### ISSUE THREAD

**Issue by Haakonak** [Azure/enterprise-azure-policy-as-code#799]
**Is your feature request related to a problem? Please describe.**
When implementing EPAC in a multi-tenant environment, it could be more clear how the Definitions folder structure should be set up. For the global-settings.jsonc file, it is shown an example for multi tenant setup, which is easy to understand and copy. 

**Describe the solution you'd like**
Something similar to the documentation for global-settings.jsonc would be great to have. An example could be having both the existing **Definitions Folder Structure** chapter, and an example **Definitions Multi-Tenant Folder Structure.** chapter.

**Describe alternatives you've considered**
We have landed this setup for the Definitions folder structure to support multi-tenant in the same folder structure:
* Definitions
  * policyAssignments
    * ALZ-policies
      * Tenant1-Platform-Default.jsonc
      * Tenant1-WorkloadGuardRails.jsonc
      * Tenant2-Platform.jsonc
      * Tenant2-WorkloadGuardRails.jsonc
    * Custom-policies
  * policyDefinitions
  * policySetDefinitions
  * global-settings.jsonc

By structuring the folders as per the example, we are able to separate different tenants and their policies while having them located in the same place. This setup also forces us to use multiple tenant-specific github workflows, such as tenant1-plan.yml, tenant1-deploy-policy.yml and so on. 

Me and @ThomasStubergh have been working on this structure, but we are unsure if this setup is the right way to go when trying to keep the maintenance and upkeep of EPAC in a multi-tenant environment as simple as possible. We are considering using parameters in a CSV file, but this is for now a "_next step_" when we have a better understanding of the entire deployment.

If anyone has any previous experience regarding multi-tenant EPAC setups, we would be very happy with some feedback or tips.

**Comment by anwather** [comment]
I'll add some more info to the documentation - but basically EPAC doesn't care how you structure those folders as we just read all the files in there recursively. The way you have organised above is perfectly acceptable - I did a similar thing for a customer except under the ALZ folder we also had folders for their tenant e.g. Tenant1, Tenant2 and placed assignments under that.

Do whatever makes sense for you :)

**Comment by Haakonak** [comment]
Want me to close this issue, or keep it open for a future PR? @anwather

**Comment by anwather** [comment]
I've completed it in our Dev environment so will copy it over and close out the issue in the next couple of days - thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
