### ISSUE TITLE
Incorrect Parameter Effect Values Generated during Plan

### ISSUE THREAD

**Issue by ahsulli** [Azure/enterprise-azure-policy-as-code#807]
**Describe the bug**
Some policies are being assigned effect values that differ from what is specified in the code. Upon switching the deployment scripts back to an older version within version 10, the policy effects only then accurately reflect the values they should have.

**To Reproduce**
1. See attached assignment file.
[assignment-policySet.jsonc](https://github.com/user-attachments/files/17603402/assignment-policySet.jsonc)
2. Run the Build-DeploymentPlans script.

**Expected behavior**
The policy effect produced in the plan would match the effect stated in the assignment. For most assignments of the policy using "CognitiveServicesAccountsEffect", that should be "Deny". The discrepancy in effects can be seen in other assignments and parameters in the larger code base.

**Screenshots**
See attached plan output to see how it differs from the inputs.
[policy-plan.json](https://github.com/user-attachments/files/17603408/policy-plan.json)
Please note, this output has been heavily modified to redact identifying information. Please let me know, if you need me to send the unredacted version through a secure medium.

**EPAC Version**
Version of EPAC module you are using.
10.7.1

Version of EPAC used to resolve issue:
commit 21812f76ba3e15918c66cf3cc9adebedf749f4c1

**Comment by anwather** [comment]
Can you check with that cognitive services policy if it is deprecated? I believe that when policies are marked as deprecated EPAC sets the effect to disabled.

**Comment by ahsulli** [comment]
That seems explain the difference. Is there a way to toggle that behavior off?

**Comment by anwather** [comment]
I don't believe so - you can duplicate the built in policy and manage it as custom if you wish to still use it - alternatively check the policy in a tool like AzAdvertizer to see if the policy has been superseded by another one. Do you have the policy which has been deprecated and I can have a look?

**Comment by ahsulli** [comment]
That works for me. I noticed it is also logging this detail, which is very helpful.

Unfortunately, I see the effect parameter matching the deprecated policy tied to the wrong policy assignment. It is claiming to be associated with a "CyberDefenseMonitoring" policy assignment, but it is actually associated with a "NetworkSecurityBenchmark" policy assignment.

I think this is a minor logging bug.
