### ISSUE TITLE
epac-tenant-workflow.yml fails to pass conditions and branch protection rules as per hydrationkit/wiki setup

### ISSUE THREAD

**Issue by ewlidd** [Azure/enterprise-azure-policy-as-code#812]
**Describe the bug**
Merging changes in the Definitions/** folder from a feat branch to main fails to trigger deployPolicy and deployRoles in epac-tenant-workflow.yml.

There are several issues:
-github.ref targets the source branch of the pull request, not the destination. It will not pass github.ref == 'refs/heads/main'
-deployPolicyChanges and deployRoleChanges don't get evaluated correctly until wrapped in ${{ }}
-on: pull_request runs in the context of the pullrequest branch. When it executes after fixing the above issues, it gets denied by branch protection of the two deploy environments. (branch protection mentioned under the hardening section at https://azure.github.io/enterprise-azure-policy-as-code/ci-cd-github-actions/)

I've uploaded a [patch.txt](https://github.com/user-attachments/files/17646367/patch.txt) file for the fix I implemented to get it working. Note it also updates "tenant" to "tenant01" which is your default from the hydration kit IIRC.
[EDIT]
My changes haven't fixed everything. Testing revealed that deployRoleChanges triggers despite not having any role changes available.
[/EDIT]

**To Reproduce**
merge to main using the github workflow files when updating Definitions/**

**Expected behavior**
jobs deployPolicy and deployRoles to run when merging to main with changes to Definitions/**.

**Screenshots**

**EPAC Version**
v10.6.2 but this problem exists in your main branch at the time of writing

**Comment by ewlidd** [comment]
Another discovery is that deployRoles and deployPolicy runs simultaneously. deployRoles fails.
I've added this dependency:
```
  deployRoles:
    needs: [plan, deployPolicy]
```

**Comment by ewlidd** [comment]
The patch.txt I uploaded has errors. I have a new one coming soon if anyone is interested.

**Comment by apybar** [comment]
@jeremiahhoward  - do you have any insight to this?

**Comment by anwather** [comment]
@apybar this could be something in the Starter Kit workflows as I believe the Hydration Kit pulls from there

**Comment by apybar** [comment]
@anwather  - I'm checking. Just wanted to confirm from @jeremiahhoward it pulled clean from the StarterKit. Will assign to myself

**Comment by apybar** [comment]
I created a test GitHub repo and configured my actions based on the starter kit [epac-tenant-workflow.yml](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Pipelines/GitHubActions/GitHub-Flow/epac-tenant-workflow.yml) file.

I used the supplementary files for [plan](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Pipelines/GitHubActions/templates-ps1-module/plan.yml), [deploy-policy](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Pipelines/GitHubActions/templates-ps1-module/deploy-policy.yml), [deploy-roles](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/StarterKit/Pipelines/GitHubActions/templates-ps1-module/deploy-roles.yml).

Based my testing, changes to the 'Definitions/**' file path works as expected - The closing of a PR will trigger a GitHub actions that will kickoff the "Plan" Job, once that is created AND if the artifacts exist for deploy-policy and deploy-roles will the following jobs actually run.

![Image](https://github.com/user-attachments/assets/4d4e07d4-bc3f-4a43-830c-665f02ea9eaa)

In the screenshot above, I have branch protection rules that requires an approval before the deploy-policy and deploy-roles job runs.

Based on your summary above, I want to confirm this what you are experiencing. The changes to the 'Definitions/**' folder will not automatically kickoff the "deploy-policy" and/or "deploy-roles job", rather the "Plan" job is required to run and will generate the required files to trigger the "deploy-policy" and/or "deploy-roles job". 

Can you please confirm? I am happy to hop on a call to ensure it is configured correctly @ewlidd.
