### ISSUE TITLE
Update schema and documentation for global-settings - Missing information on excludeSubscriptions

### ISSUE THREAD

**Issue by cjtous1** [Azure/enterprise-azure-policy-as-code#814]
**Describe the bug**
In release 10.7.0, a new parameter was added to the global-settings.jsonc file: "excludeSubscriptions"
This setting seems to be missing from the schema file and the documentation.

**Comment by CharlesNRU** [comment]
Schema is updated but not documentation. Can we have some documentation about the feature?

**Comment by anwather** [comment]
It is documented here -> https://azure.github.io/enterprise-azure-policy-as-code/settings-desired-state/#the-desiredstate-element
