### ISSUE TITLE
Policy Plan cannot create per-resource exemptions using Policy Reader role

### ISSUE THREAD

**Issue by benjaminpieplow** [Azure/enterprise-azure-policy-as-code#822]
**Describe the bug**
When attempting to deploy an exemption scoped to a single resource, Policy Plan fails with the following error:
> WARNING: Row 0: Resource '/subscriptions/SUBSCRIPTION_GUID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/STORAGEACCOUNT' does not exist, skipping entry.

This is quite similar to https://github.com/Azure/enterprise-azure-policy-as-code/issues/545.

**To Reproduce**
In a greenfield EPAC environment,
* Create a policy assignment at a subscription/management group scope (probably works on RG too)
* Create a storage account in that scope
* Create an exemption for that storage account for a single policy

**Expected behavior**
Ideally, EPAC would plan to create the policy assignment.

**Possible Solution**
I was able to resolve this issue in our environment by adding `Microsoft.Resources/subscriptions/resources/read` to the Policy Reader Role, and I believe this to be the least-privileged permission for this use-case.

**EPAC Version**
v10.5.8

**Comment by apybar** [comment]
@benjaminpieplow  -  I believe there was some logic that fixed this perhaps in the v10.6.0+ version of EPAC. We also updated our documentation which originally called for custom permissions, but now we have defaulted to "Reader" for the "Plan" stage to see the resource and create the exemption, as well as "Resource Policy Contributor" for "Deploy Policy" stage that creates the exemption.

I tested using v10.7.3 with the permissions I just described as was able to create an exemption on a single resource without an error. I do remember coming across your issue in particular back around your version of EPAC and was able to resolve it with the exact permissions you listed in the issue.
