### ISSUE TITLE
"Name" property location inconsistent

### ISSUE THREAD

**Issue by amoona6** [Azure/enterprise-azure-policy-as-code#828]
Description:
When executing the `Sync-ALZPolicies` cmdlet, the resulting policy files are generated inconsistently, particularly in terms of the position of the `name` property within the output JSON. Depending on the operating system or PowerShell version, the `name `property may appear at the top or at the bottom of the JSON structure. This inconsistency seems related to how `ConvertTo-Json` serializes attributes, potentially ordering them alphabetically before writing to the file.

This inconsistency becomes problematic when committing changes to a Git repository, as it appears that multiple properties have changed, whereas in reality, the only change is the ordering of properties in the JSON file.

To Reproduce

> Run `Sync-ALZPolicies` on a Linux runner.
> Run the same command on a local Windows machine.
> Observe that the JSON files generated show differences in the ordering of properties, particularly the `name` property.

Expected Behavior

The `name ` property should always be positioned at the top of the JSON file for consistent output, regardless of the operating system or PowerShell version.

Screenshot included

EPAC Version
10.5.2

Proposed Fix
To ensure consistent ordering of properties in the generated JSON files, modify Sync-ALZPolicies.ps1 to explicitly specify the order before serialization:

Current Code:
`$baseTemplate | ConvertTo-Json -Depth 50 | Out-File -FilePath $DefinitionsRootFolder\policySetDefinitions\ALZ\$category\$fileName.json -Force`

Proposed Update:
`$baseTemplate | Select-Object Name, Properties | ConvertTo-Json -Depth 50 | Out-File -FilePath $DefinitionsRootFolder\policySetDefinitions\ALZ\$category\$fileName.json -Force`

This change ensures that the name property appears consistently at the top of the JSON output, regardless of the operating system or PowerShell version, thereby reducing unnecessary noise in Git diffs and simplifying code reviews.![Image](https://github.com/user-attachments/assets/56e308e8-e03e-4116-8ded-33e8f78a88c5)

**Comment by anwather** [comment]
Thanks - I'll get this done shortly
