### ISSUE TITLE
explicitely set output to json instead of relying on prefered user output

### ISSUE THREAD

**Issue by wetwicky** [Azure/enterprise-azure-policy-as-code#83]
https://github.com/Azure/enterprise-azure-policy-as-code/blob/406ccce7538121a462a9777bb0619cc914ebdae4/Scripts/Helpers/Set-AzCloudTenantSubscription.ps1#L30

Since converting from json, it should be no matter what is the default output format configure by the users
```
$accountJson = az account show --output json
```

**Comment by techlake** [comment]
I agree. I'm in the process of converting everything from az cli to Az.Modules (PowerShell).
The mixed az cli/Az.Module approach has proven itself as not workable. While I wanted to switch everything to az cli, az policy assignment currently does not support assignment metadata I need for housekeeping.

Please note that this will be a breaking change for the ADO pipeline. I'm also doing other significant improvements which require a breaking change. I will focus on breaking things only once.
