### ISSUE TITLE
Getting error when obsolete role assignment need to be removed

### ISSUE THREAD

**Issue by chasdesj** [Azure/enterprise-azure-policy-as-code#84]
When running the pipeline we get the following error whenever an obsolete role assignment need deletion,

```
ERROR: Please run 'az login' to setup account.
 ##[error]Command exited with error
 ##[error]PowerShell exited with code '1'.
```

We think it might be related to the fact that `Invoke-AzCli` is used in this specific section: https://github.com/Azure/enterprise-azure-policy-as-code/blob/406ccce7538121a462a9777bb0619cc914ebdae4/Scripts/Deploy/Set-AzPolicyRolesFromPlan.ps1#L74

We are currently using a service principal and we obviously want it to be used in this case also

**Comment by techlake** [comment]
You (or the pipeline need to be logged in to az cli for this script. I'm in the process of removing az cli dependencies, should simplify the login problems (plural)

**Comment by techlake** [comment]
Closing it due to inactivity. feel free to open if proposed solution didn't work.
