### ISSUE TITLE
Feature: Override support in Policy Assignments

### ISSUE THREAD

**Issue by techlake** [Azure/enterprise-azure-policy-as-code#89]
Parameter override feature: https://learn.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#overrides-preview and https://learn.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#resource-selectors-preview.

Plan: January 2023

**Comment by artisticcheese** [comment]
While this is not implemented - will PAC deleted override which is added `manually` after assignment is already deployed via PAC?

**Comment by techlake** [comment]
Correct (sorry). I'm working on override right now

**Comment by artisticcheese** [comment]
`Resource selectors` will be separate release from `override` release or both are being done at the same time?

**Comment by techlake** [comment]
Likely at the same time
