### ISSUE TITLE
Child MG does not contain a scope property when evaluating globalNotScope on AssignmentsPlan

### ISSUE THREAD

**Issue by jacerm** [Azure/enterprise-azure-policy-as-code#92]
Running the `Build-AzPoliciesInitiativesAssignmentsPlan`, `Get-NotScope` fails to find a value for the [property `scope`](https://github.com/Azure/enterprise-azure-policy-as-code/blob/main/Scripts/Helpers/Get-NotScope.ps1#L49) on the `currentMg` or the `child` objects.

Similar to a previous [issue](https://github.com/Azure/enterprise-azure-policy-as-code/issues/87), this is occurring on an empty management group that contains multiple child management groups.

![image](https://user-images.githubusercontent.com/10948023/200962287-29dc5a2b-9b07-46cf-a441-dbb0a096534c.png)
![image](https://user-images.githubusercontent.com/10948023/200962305-319160c2-a7dc-4b06-90a3-b5f00b6d2974.png)

**Comment by techlake** [comment]
You are finding all the edge cases. I need to hire you as my permanent tester :-). In all seriousness, thank you for finding all the problems. I will work on a solution right away.

**Comment by techlake** [comment]
What version of az cli are your running?

**Comment by techlake** [comment]
For everybody else, if it's working do not fetch this. I'm working on a major update.

**Comment by jacerm** [comment]
> What version of az cli are your running?

2.28.0

> You are finding all the edge cases. I need to hire you as my permanent tester :-). In all seriousness, thank you for finding all the problems. I will work on a solution right away.

You are welcome. I love the solution, and am more than happy to help. As I get more familiar with the code base, I'll look to contribute :)

**Comment by techlake** [comment]
That's awesome. I look forward to your contributions.

Note: I' currently finishing a major improvements. I'm replacing az cli with Az PowerShell modules throughout. So, don't start your contributions yet.

Heinrich Gantenbein
