### ISSUE TITLE
Feature: Operational guidance for longer-term lifecycle management of policies

### ISSUE THREAD

**Issue by PatTelford** [Azure/enterprise-azure-policy-as-code#94]
As organizations implement and operate policy-as-code, lifecycle operations will be needed. It would be helpful to have guidance and examples of those lifecycle operations and how to manage them. As examples, these are situations likely to arise as policy-as-code is used longer term:

- Onboarding a new Azure service that requires additional policy
- Changes in an Azure service that invalidates or requires expansion of policy checks
- The organization refreshes their compliance standards and requires new/updated/removed policy checks
- Versioning where older resources are subject to older policy versions while new resources are subject to a newer version
- Policy that no longer applies to any resources can be retired
- Policy exemptions need to be managed over time as the reasons for the exemptions are addressed

**Comment by techlake** [comment]
Instead of adding this to the PAC documentation, we will cover this in a blog post on [Microsoft Tech Community's Core Infrastructure and Security Blog](https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/bg-p/CoreInfrastructureandSecurityBlog).
